<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\AdditionalSettingsResponse1;
use Core\Utils\CoreHelper;

/**
 * Builder for model AdditionalSettingsResponse1
 *
 * @see AdditionalSettingsResponse1
 */
class AdditionalSettingsResponse1Builder
{
    /**
     * @var AdditionalSettingsResponse1
     */
    private $instance;

    private function __construct(AdditionalSettingsResponse1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Additional Settings Response 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new AdditionalSettingsResponse1());
    }

    /**
     * Sets exclude Event Codes field.
     *
     * @param string[]|null $value
     */
    public function excludeEventCodes(?array $value): self
    {
        $this->instance->setExcludeEventCodes($value);
        return $this;
    }

    /**
     * Sets include Event Codes field.
     *
     * @param string[]|null $value
     */
    public function includeEventCodes(?array $value): self
    {
        $this->instance->setIncludeEventCodes($value);
        return $this;
    }

    /**
     * Sets properties field.
     *
     * @param array<string,bool>|null $value
     */
    public function properties(?array $value): self
    {
        $this->instance->setProperties($value);
        return $this;
    }

    /**
     * Initializes a new Additional Settings Response 1 object.
     */
    public function build(): AdditionalSettingsResponse1
    {
        return CoreHelper::clone($this->instance);
    }
}
