<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\AdditionalDataOpenInvoice;
use Core\Utils\CoreHelper;

/**
 * Builder for model AdditionalDataOpenInvoice
 *
 * @see AdditionalDataOpenInvoice
 */
class AdditionalDataOpenInvoiceBuilder
{
    /**
     * @var AdditionalDataOpenInvoice
     */
    private $instance;

    private function __construct(AdditionalDataOpenInvoice $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Additional Data Open Invoice Builder object.
     */
    public static function init(): self
    {
        return new self(new AdditionalDataOpenInvoice());
    }

    /**
     * Sets openinvoicedata merchant Data field.
     *
     * @param string|null $value
     */
    public function openinvoicedataMerchantData(?string $value): self
    {
        $this->instance->setOpeninvoicedataMerchantData($value);
        return $this;
    }

    /**
     * Sets openinvoicedata number Of Lines field.
     *
     * @param string|null $value
     */
    public function openinvoicedataNumberOfLines(?string $value): self
    {
        $this->instance->setOpeninvoicedataNumberOfLines($value);
        return $this;
    }

    /**
     * Sets openinvoicedata recipient First Name field.
     *
     * @param string|null $value
     */
    public function openinvoicedataRecipientFirstName(?string $value): self
    {
        $this->instance->setOpeninvoicedataRecipientFirstName($value);
        return $this;
    }

    /**
     * Sets openinvoicedata recipient Last Name field.
     *
     * @param string|null $value
     */
    public function openinvoicedataRecipientLastName(?string $value): self
    {
        $this->instance->setOpeninvoicedataRecipientLastName($value);
        return $this;
    }

    /**
     * Sets openinvoicedata Line item Nr currency Code field.
     *
     * @param string|null $value
     */
    public function openinvoicedataLineItemNrCurrencyCode(?string $value): self
    {
        $this->instance->setOpeninvoicedataLineItemNrCurrencyCode($value);
        return $this;
    }

    /**
     * Sets openinvoicedata Line item Nr description field.
     *
     * @param string|null $value
     */
    public function openinvoicedataLineItemNrDescription(?string $value): self
    {
        $this->instance->setOpeninvoicedataLineItemNrDescription($value);
        return $this;
    }

    /**
     * Sets openinvoicedata Line item Nr item Amount field.
     *
     * @param string|null $value
     */
    public function openinvoicedataLineItemNrItemAmount(?string $value): self
    {
        $this->instance->setOpeninvoicedataLineItemNrItemAmount($value);
        return $this;
    }

    /**
     * Sets openinvoicedata Line item Nr item Id field.
     *
     * @param string|null $value
     */
    public function openinvoicedataLineItemNrItemId(?string $value): self
    {
        $this->instance->setOpeninvoicedataLineItemNrItemId($value);
        return $this;
    }

    /**
     * Sets openinvoicedata Line item Nr item Vat Amount field.
     *
     * @param string|null $value
     */
    public function openinvoicedataLineItemNrItemVatAmount(?string $value): self
    {
        $this->instance->setOpeninvoicedataLineItemNrItemVatAmount($value);
        return $this;
    }

    /**
     * Sets openinvoicedata Line item Nr item Vat Percentage field.
     *
     * @param string|null $value
     */
    public function openinvoicedataLineItemNrItemVatPercentage(?string $value): self
    {
        $this->instance->setOpeninvoicedataLineItemNrItemVatPercentage($value);
        return $this;
    }

    /**
     * Sets openinvoicedata Line item Nr number Of Items field.
     *
     * @param string|null $value
     */
    public function openinvoicedataLineItemNrNumberOfItems(?string $value): self
    {
        $this->instance->setOpeninvoicedataLineItemNrNumberOfItems($value);
        return $this;
    }

    /**
     * Sets openinvoicedata Line item Nr return Shipping Company field.
     *
     * @param string|null $value
     */
    public function openinvoicedataLineItemNrReturnShippingCompany(?string $value): self
    {
        $this->instance->setOpeninvoicedataLineItemNrReturnShippingCompany($value);
        return $this;
    }

    /**
     * Sets openinvoicedata Line item Nr return Tracking Number field.
     *
     * @param string|null $value
     */
    public function openinvoicedataLineItemNrReturnTrackingNumber(?string $value): self
    {
        $this->instance->setOpeninvoicedataLineItemNrReturnTrackingNumber($value);
        return $this;
    }

    /**
     * Sets openinvoicedata Line item Nr return Tracking Uri field.
     *
     * @param string|null $value
     */
    public function openinvoicedataLineItemNrReturnTrackingUri(?string $value): self
    {
        $this->instance->setOpeninvoicedataLineItemNrReturnTrackingUri($value);
        return $this;
    }

    /**
     * Sets openinvoicedata Line item Nr shipping Company field.
     *
     * @param string|null $value
     */
    public function openinvoicedataLineItemNrShippingCompany(?string $value): self
    {
        $this->instance->setOpeninvoicedataLineItemNrShippingCompany($value);
        return $this;
    }

    /**
     * Sets openinvoicedata Line item Nr shipping Method field.
     *
     * @param string|null $value
     */
    public function openinvoicedataLineItemNrShippingMethod(?string $value): self
    {
        $this->instance->setOpeninvoicedataLineItemNrShippingMethod($value);
        return $this;
    }

    /**
     * Sets openinvoicedata Line item Nr tracking Number field.
     *
     * @param string|null $value
     */
    public function openinvoicedataLineItemNrTrackingNumber(?string $value): self
    {
        $this->instance->setOpeninvoicedataLineItemNrTrackingNumber($value);
        return $this;
    }

    /**
     * Sets openinvoicedata Line item Nr tracking Uri field.
     *
     * @param string|null $value
     */
    public function openinvoicedataLineItemNrTrackingUri(?string $value): self
    {
        $this->instance->setOpeninvoicedataLineItemNrTrackingUri($value);
        return $this;
    }

    /**
     * Initializes a new Additional Data Open Invoice object.
     */
    public function build(): AdditionalDataOpenInvoice
    {
        return CoreHelper::clone($this->instance);
    }
}
