<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\AdditionalDataRiskStandalone;
use Core\Utils\CoreHelper;

/**
 * Builder for model AdditionalDataRiskStandalone
 *
 * @see AdditionalDataRiskStandalone
 */
class AdditionalDataRiskStandaloneBuilder
{
    /**
     * @var AdditionalDataRiskStandalone
     */
    private $instance;

    private function __construct(AdditionalDataRiskStandalone $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Additional Data Risk Standalone Builder object.
     */
    public static function init(): self
    {
        return new self(new AdditionalDataRiskStandalone());
    }

    /**
     * Sets Pay Pal Country Code field.
     *
     * @param string|null $value
     */
    public function payPalCountryCode(?string $value): self
    {
        $this->instance->setPayPalCountryCode($value);
        return $this;
    }

    /**
     * Sets Pay Pal Email Id field.
     *
     * @param string|null $value
     */
    public function payPalEmailId(?string $value): self
    {
        $this->instance->setPayPalEmailId($value);
        return $this;
    }

    /**
     * Sets Pay Pal First Name field.
     *
     * @param string|null $value
     */
    public function payPalFirstName(?string $value): self
    {
        $this->instance->setPayPalFirstName($value);
        return $this;
    }

    /**
     * Sets Pay Pal Last Name field.
     *
     * @param string|null $value
     */
    public function payPalLastName(?string $value): self
    {
        $this->instance->setPayPalLastName($value);
        return $this;
    }

    /**
     * Sets Pay Pal Payer Id field.
     *
     * @param string|null $value
     */
    public function payPalPayerId(?string $value): self
    {
        $this->instance->setPayPalPayerId($value);
        return $this;
    }

    /**
     * Sets Pay Pal Phone field.
     *
     * @param string|null $value
     */
    public function payPalPhone(?string $value): self
    {
        $this->instance->setPayPalPhone($value);
        return $this;
    }

    /**
     * Sets Pay Pal Protection Eligibility field.
     *
     * @param string|null $value
     */
    public function payPalProtectionEligibility(?string $value): self
    {
        $this->instance->setPayPalProtectionEligibility($value);
        return $this;
    }

    /**
     * Sets Pay Pal Transaction Id field.
     *
     * @param string|null $value
     */
    public function payPalTransactionId(?string $value): self
    {
        $this->instance->setPayPalTransactionId($value);
        return $this;
    }

    /**
     * Sets avs Result Raw field.
     *
     * @param string|null $value
     */
    public function avsResultRaw(?string $value): self
    {
        $this->instance->setAvsResultRaw($value);
        return $this;
    }

    /**
     * Sets bin field.
     *
     * @param string|null $value
     */
    public function bin(?string $value): self
    {
        $this->instance->setBin($value);
        return $this;
    }

    /**
     * Sets cvc Result Raw field.
     *
     * @param string|null $value
     */
    public function cvcResultRaw(?string $value): self
    {
        $this->instance->setCvcResultRaw($value);
        return $this;
    }

    /**
     * Sets risk Token field.
     *
     * @param string|null $value
     */
    public function riskToken(?string $value): self
    {
        $this->instance->setRiskToken($value);
        return $this;
    }

    /**
     * Sets three D Authenticated field.
     *
     * @param string|null $value
     */
    public function threeDAuthenticated(?string $value): self
    {
        $this->instance->setThreeDAuthenticated($value);
        return $this;
    }

    /**
     * Sets three D Offered field.
     *
     * @param string|null $value
     */
    public function threeDOffered(?string $value): self
    {
        $this->instance->setThreeDOffered($value);
        return $this;
    }

    /**
     * Sets token Data Type field.
     *
     * @param string|null $value
     */
    public function tokenDataType(?string $value): self
    {
        $this->instance->setTokenDataType($value);
        return $this;
    }

    /**
     * Initializes a new Additional Data Risk Standalone object.
     */
    public function build(): AdditionalDataRiskStandalone
    {
        return CoreHelper::clone($this->instance);
    }
}
