<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Address11;
use Core\Utils\CoreHelper;

/**
 * Builder for model Address11
 *
 * @see Address11
 */
class Address11Builder
{
    /**
     * @var Address11
     */
    private $instance;

    private function __construct(Address11 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Address 11 Builder object.
     */
    public static function init(): self
    {
        return new self(new Address11());
    }

    /**
     * Sets city field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets company Name field.
     *
     * @param string|null $value
     */
    public function companyName(?string $value): self
    {
        $this->instance->setCompanyName($value);
        return $this;
    }

    /**
     * Sets country field.
     *
     * @param string|null $value
     */
    public function country(?string $value): self
    {
        $this->instance->setCountry($value);
        return $this;
    }

    /**
     * Sets postal Code field.
     *
     * @param string|null $value
     */
    public function postalCode(?string $value): self
    {
        $this->instance->setPostalCode($value);
        return $this;
    }

    /**
     * Sets state Or Province field.
     *
     * @param string|null $value
     */
    public function stateOrProvince(?string $value): self
    {
        $this->instance->setStateOrProvince($value);
        return $this;
    }

    /**
     * Sets street Address field.
     *
     * @param string|null $value
     */
    public function streetAddress(?string $value): self
    {
        $this->instance->setStreetAddress($value);
        return $this;
    }

    /**
     * Sets street Address 2 field.
     *
     * @param string|null $value
     */
    public function streetAddress2(?string $value): self
    {
        $this->instance->setStreetAddress2($value);
        return $this;
    }

    /**
     * Initializes a new Address 11 object.
     */
    public function build(): Address11
    {
        return CoreHelper::clone($this->instance);
    }
}
