<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\AfterpayTouchInfo;
use Core\Utils\CoreHelper;

/**
 * Builder for model AfterpayTouchInfo
 *
 * @see AfterpayTouchInfo
 */
class AfterpayTouchInfoBuilder
{
    /**
     * @var AfterpayTouchInfo
     */
    private $instance;

    private function __construct(AfterpayTouchInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Afterpay Touch Info Builder object.
     *
     * @param string $supportUrl
     */
    public static function init(string $supportUrl): self
    {
        return new self(new AfterpayTouchInfo($supportUrl));
    }

    /**
     * Sets support Email field.
     *
     * @param string|null $value
     */
    public function supportEmail(?string $value): self
    {
        $this->instance->setSupportEmail($value);
        return $this;
    }

    /**
     * Initializes a new Afterpay Touch Info object.
     */
    public function build(): AfterpayTouchInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
