<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\AmexInfo;
use Core\Utils\CoreHelper;

/**
 * Builder for model AmexInfo
 *
 * @see AmexInfo
 */
class AmexInfoBuilder
{
    /**
     * @var AmexInfo
     */
    private $instance;

    private function __construct(AmexInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Amex Info Builder object.
     *
     * @param string $serviceLevel
     */
    public static function init(string $serviceLevel): self
    {
        return new self(new AmexInfo($serviceLevel));
    }

    /**
     * Sets mid Number field.
     *
     * @param string|null $value
     */
    public function midNumber(?string $value): self
    {
        $this->instance->setMidNumber($value);
        return $this;
    }

    /**
     * Sets reuse Mid Number field.
     *
     * @param bool|null $value
     */
    public function reuseMidNumber(?bool $value): self
    {
        $this->instance->setReuseMidNumber($value);
        return $this;
    }

    /**
     * Initializes a new Amex Info object.
     */
    public function build(): AmexInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
