<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Amount17;
use Core\Utils\CoreHelper;

/**
 * Builder for model Amount17
 *
 * @see Amount17
 */
class Amount17Builder
{
    /**
     * @var Amount17
     */
    private $instance;

    private function __construct(Amount17 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Amount 17 Builder object.
     *
     * @param string $currency
     * @param int $value
     */
    public static function init(string $currency, int $value): self
    {
        return new self(new Amount17($currency, $value));
    }

    /**
     * Initializes a new Amount 17 object.
     */
    public function build(): Amount17
    {
        return CoreHelper::clone($this->instance);
    }
}
