<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Amount28;
use Core\Utils\CoreHelper;

/**
 * Builder for model Amount28
 *
 * @see Amount28
 */
class Amount28Builder
{
    /**
     * @var Amount28
     */
    private $instance;

    private function __construct(Amount28 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Amount 28 Builder object.
     *
     * @param string $currency
     * @param int $value
     */
    public static function init(string $currency, int $value): self
    {
        return new self(new Amount28($currency, $value));
    }

    /**
     * Initializes a new Amount 28 object.
     */
    public function build(): Amount28
    {
        return CoreHelper::clone($this->instance);
    }
}
