<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\AndroidPay;
use Core\Utils\CoreHelper;

/**
 * Builder for model AndroidPay
 *
 * @see AndroidPay
 */
class AndroidPayBuilder
{
    /**
     * @var AndroidPay
     */
    private $instance;

    private function __construct(AndroidPay $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Android Pay Builder object.
     */
    public static function init(): self
    {
        return new self(new AndroidPay());
    }

    /**
     * Sets checkout Attempt Id field.
     *
     * @param string|null $value
     */
    public function checkoutAttemptId(?string $value): self
    {
        $this->instance->setCheckoutAttemptId($value);
        return $this;
    }

    /**
     * Sets sdk Data field.
     *
     * @param string|null $value
     */
    public function sdkData(?string $value): self
    {
        $this->instance->setSdkData($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Initializes a new Android Pay object.
     */
    public function build(): AndroidPay
    {
        return CoreHelper::clone($this->instance);
    }
}
