<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\ApplePaySessionRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model ApplePaySessionRequest
 *
 * @see ApplePaySessionRequest
 */
class ApplePaySessionRequestBuilder
{
    /**
     * @var ApplePaySessionRequest
     */
    private $instance;

    private function __construct(ApplePaySessionRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Apple Pay Session Request Builder object.
     *
     * @param string $displayName
     * @param string $domainName
     * @param string $merchantIdentifier
     */
    public static function init(string $displayName, string $domainName, string $merchantIdentifier): self
    {
        return new self(new ApplePaySessionRequest($displayName, $domainName, $merchantIdentifier));
    }

    /**
     * Initializes a new Apple Pay Session Request object.
     */
    public function build(): ApplePaySessionRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
