<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\BillingAddress1;
use Core\Utils\CoreHelper;

/**
 * Builder for model BillingAddress1
 *
 * @see BillingAddress1
 */
class BillingAddress1Builder
{
    /**
     * @var BillingAddress1
     */
    private $instance;

    private function __construct(BillingAddress1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Billing Address 1 Builder object.
     *
     * @param string $city
     * @param string $country
     * @param string $houseNumberOrName
     * @param string $postalCode
     * @param string $street
     */
    public static function init(
        string $city,
        string $country,
        string $houseNumberOrName,
        string $postalCode,
        string $street
    ): self {
        return new self(new BillingAddress1($city, $country, $houseNumberOrName, $postalCode, $street));
    }

    /**
     * Sets state Or Province field.
     *
     * @param string|null $value
     */
    public function stateOrProvince(?string $value): self
    {
        $this->instance->setStateOrProvince($value);
        return $this;
    }

    /**
     * Initializes a new Billing Address 1 object.
     */
    public function build(): BillingAddress1
    {
        return CoreHelper::clone($this->instance);
    }
}
