<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\CartesBancairesInfo;
use AdyenApIsLib\Models\TransactionDescriptionInfo1;
use Core\Utils\CoreHelper;

/**
 * Builder for model CartesBancairesInfo
 *
 * @see CartesBancairesInfo
 */
class CartesBancairesInfoBuilder
{
    /**
     * @var CartesBancairesInfo
     */
    private $instance;

    private function __construct(CartesBancairesInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cartes Bancaires Info Builder object.
     *
     * @param string $siret
     */
    public static function init(string $siret): self
    {
        return new self(new CartesBancairesInfo($siret));
    }

    /**
     * Sets transaction Description field.
     *
     * @param TransactionDescriptionInfo1|null $value
     */
    public function transactionDescription(?TransactionDescriptionInfo1 $value): self
    {
        $this->instance->setTransactionDescription($value);
        return $this;
    }

    /**
     * Initializes a new Cartes Bancaires Info object.
     */
    public function build(): CartesBancairesInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
