<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Amount13;
use AdyenApIsLib\Models\Amount14;
use AdyenApIsLib\Models\Amount15;
use AdyenApIsLib\Models\CheckoutVoucherAction;
use Core\Utils\CoreHelper;

/**
 * Builder for model CheckoutVoucherAction
 *
 * @see CheckoutVoucherAction
 */
class CheckoutVoucherActionBuilder
{
    /**
     * @var CheckoutVoucherAction
     */
    private $instance;

    private function __construct(CheckoutVoucherAction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Checkout Voucher Action Builder object.
     */
    public static function init(): self
    {
        return new self(new CheckoutVoucherAction());
    }

    /**
     * Sets alternative Reference field.
     *
     * @param string|null $value
     */
    public function alternativeReference(?string $value): self
    {
        $this->instance->setAlternativeReference($value);
        return $this;
    }

    /**
     * Sets collection Institution Number field.
     *
     * @param string|null $value
     */
    public function collectionInstitutionNumber(?string $value): self
    {
        $this->instance->setCollectionInstitutionNumber($value);
        return $this;
    }

    /**
     * Sets download Url field.
     *
     * @param string|null $value
     */
    public function downloadUrl(?string $value): self
    {
        $this->instance->setDownloadUrl($value);
        return $this;
    }

    /**
     * Sets entity field.
     *
     * @param string|null $value
     */
    public function entity(?string $value): self
    {
        $this->instance->setEntity($value);
        return $this;
    }

    /**
     * Sets expires At field.
     *
     * @param string|null $value
     */
    public function expiresAt(?string $value): self
    {
        $this->instance->setExpiresAt($value);
        return $this;
    }

    /**
     * Sets initial Amount field.
     *
     * @param Amount13|null $value
     */
    public function initialAmount(?Amount13 $value): self
    {
        $this->instance->setInitialAmount($value);
        return $this;
    }

    /**
     * Sets instructions Url field.
     *
     * @param string|null $value
     */
    public function instructionsUrl(?string $value): self
    {
        $this->instance->setInstructionsUrl($value);
        return $this;
    }

    /**
     * Sets issuer field.
     *
     * @param string|null $value
     */
    public function issuer(?string $value): self
    {
        $this->instance->setIssuer($value);
        return $this;
    }

    /**
     * Sets masked Telephone Number field.
     *
     * @param string|null $value
     */
    public function maskedTelephoneNumber(?string $value): self
    {
        $this->instance->setMaskedTelephoneNumber($value);
        return $this;
    }

    /**
     * Sets merchant Name field.
     *
     * @param string|null $value
     */
    public function merchantName(?string $value): self
    {
        $this->instance->setMerchantName($value);
        return $this;
    }

    /**
     * Sets merchant Reference field.
     *
     * @param string|null $value
     */
    public function merchantReference(?string $value): self
    {
        $this->instance->setMerchantReference($value);
        return $this;
    }

    /**
     * Sets pass Creation Token field.
     *
     * @param string|null $value
     */
    public function passCreationToken(?string $value): self
    {
        $this->instance->setPassCreationToken($value);
        return $this;
    }

    /**
     * Sets payment Data field.
     *
     * @param string|null $value
     */
    public function paymentData(?string $value): self
    {
        $this->instance->setPaymentData($value);
        return $this;
    }

    /**
     * Sets payment Method Type field.
     *
     * @param string|null $value
     */
    public function paymentMethodType(?string $value): self
    {
        $this->instance->setPaymentMethodType($value);
        return $this;
    }

    /**
     * Sets reference field.
     *
     * @param string|null $value
     */
    public function reference(?string $value): self
    {
        $this->instance->setReference($value);
        return $this;
    }

    /**
     * Sets shopper Email field.
     *
     * @param string|null $value
     */
    public function shopperEmail(?string $value): self
    {
        $this->instance->setShopperEmail($value);
        return $this;
    }

    /**
     * Sets shopper Name field.
     *
     * @param string|null $value
     */
    public function shopperName(?string $value): self
    {
        $this->instance->setShopperName($value);
        return $this;
    }

    /**
     * Sets surcharge field.
     *
     * @param Amount14|null $value
     */
    public function surcharge(?Amount14 $value): self
    {
        $this->instance->setSurcharge($value);
        return $this;
    }

    /**
     * Sets total Amount field.
     *
     * @param Amount15|null $value
     */
    public function totalAmount(?Amount15 $value): self
    {
        $this->instance->setTotalAmount($value);
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Initializes a new Checkout Voucher Action object.
     */
    public function build(): CheckoutVoucherAction
    {
        return CoreHelper::clone($this->instance);
    }
}
