<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\CheckoutQrCodeAction;
use Core\Utils\CoreHelper;

/**
 * Builder for model CheckoutQrCodeAction
 *
 * @see CheckoutQrCodeAction
 */
class CheckoutQrCodeActionBuilder
{
    /**
     * @var CheckoutQrCodeAction
     */
    private $instance;

    private function __construct(CheckoutQrCodeAction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Checkout Qr Code Action Builder object.
     */
    public static function init(): self
    {
        return new self(new CheckoutQrCodeAction());
    }

    /**
     * Sets expires At field.
     *
     * @param string|null $value
     */
    public function expiresAt(?string $value): self
    {
        $this->instance->setExpiresAt($value);
        return $this;
    }

    /**
     * Sets payment Data field.
     *
     * @param string|null $value
     */
    public function paymentData(?string $value): self
    {
        $this->instance->setPaymentData($value);
        return $this;
    }

    /**
     * Sets payment Method Type field.
     *
     * @param string|null $value
     */
    public function paymentMethodType(?string $value): self
    {
        $this->instance->setPaymentMethodType($value);
        return $this;
    }

    /**
     * Sets qr Code Data field.
     *
     * @param string|null $value
     */
    public function qrCodeData(?string $value): self
    {
        $this->instance->setQrCodeData($value);
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Initializes a new Checkout Qr Code Action object.
     */
    public function build(): CheckoutQrCodeAction
    {
        return CoreHelper::clone($this->instance);
    }
}
