<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Company2;
use AdyenApIsLib\Models\CompanyLinks2;
use AdyenApIsLib\Models\DataCenter;
use Core\Utils\CoreHelper;

/**
 * Builder for model Company2
 *
 * @see Company2
 */
class Company2Builder
{
    /**
     * @var Company2
     */
    private $instance;

    private function __construct(Company2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Company 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new Company2());
    }

    /**
     * Sets links field.
     *
     * @param CompanyLinks2|null $value
     */
    public function links(?CompanyLinks2 $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Sets data Centers field.
     *
     * @param DataCenter[]|null $value
     */
    public function dataCenters(?array $value): self
    {
        $this->instance->setDataCenters($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets reference field.
     *
     * @param string|null $value
     */
    public function reference(?string $value): self
    {
        $this->instance->setReference($value);
        return $this;
    }

    /**
     * Sets status field.
     *
     * @param string|null $value
     */
    public function status(?string $value): self
    {
        $this->instance->setStatus($value);
        return $this;
    }

    /**
     * Initializes a new Company 2 object.
     */
    public function build(): Company2
    {
        return CoreHelper::clone($this->instance);
    }
}
