<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Destination1;
use Core\Utils\CoreHelper;

/**
 * Builder for model Destination1
 *
 * @see Destination1
 */
class Destination1Builder
{
    /**
     * @var Destination1
     */
    private $instance;

    private function __construct(Destination1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Destination 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new Destination1());
    }

    /**
     * Sets country Code field.
     *
     * @param string|null $value
     */
    public function countryCode(?string $value): self
    {
        $this->instance->setCountryCode($value);
        return $this;
    }

    /**
     * Sets postal Code field.
     *
     * @param string|null $value
     */
    public function postalCode(?string $value): self
    {
        $this->instance->setPostalCode($value);
        return $this;
    }

    /**
     * Sets state Or Province field.
     *
     * @param string|null $value
     */
    public function stateOrProvince(?string $value): self
    {
        $this->instance->setStateOrProvince($value);
        return $this;
    }

    /**
     * Initializes a new Destination 1 object.
     */
    public function build(): Destination1
    {
        return CoreHelper::clone($this->instance);
    }
}
