<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\DeviceRenderOptions;
use Core\Utils\CoreHelper;

/**
 * Builder for model DeviceRenderOptions
 *
 * @see DeviceRenderOptions
 */
class DeviceRenderOptionsBuilder
{
    /**
     * @var DeviceRenderOptions
     */
    private $instance;

    private function __construct(DeviceRenderOptions $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Device Render Options Builder object.
     */
    public static function init(): self
    {
        return new self(new DeviceRenderOptions());
    }

    /**
     * Sets sdk Interface field.
     *
     * @param string|null $value
     */
    public function sdkInterface(?string $value): self
    {
        $this->instance->setSdkInterface($value);
        return $this;
    }

    /**
     * Sets sdk Ui Type field.
     *
     * @param string[]|null $value
     */
    public function sdkUiType(?array $value): self
    {
        $this->instance->setSdkUiType($value);
        return $this;
    }

    /**
     * Initializes a new Device Render Options object.
     */
    public function build(): DeviceRenderOptions
    {
        return CoreHelper::clone($this->instance);
    }
}
