<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Address3;
use AdyenApIsLib\Models\FundOrigin1;
use AdyenApIsLib\Models\Name1;
use Core\Utils\CoreHelper;

/**
 * Builder for model FundOrigin1
 *
 * @see FundOrigin1
 */
class FundOrigin1Builder
{
    /**
     * @var FundOrigin1
     */
    private $instance;

    private function __construct(FundOrigin1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Fund Origin 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new FundOrigin1());
    }

    /**
     * Sets billing Address field.
     *
     * @param Address3|null $value
     */
    public function billingAddress(?Address3 $value): self
    {
        $this->instance->setBillingAddress($value);
        return $this;
    }

    /**
     * Sets shopper Email field.
     *
     * @param string|null $value
     */
    public function shopperEmail(?string $value): self
    {
        $this->instance->setShopperEmail($value);
        return $this;
    }

    /**
     * Sets shopper Name field.
     *
     * @param Name1|null $value
     */
    public function shopperName(?Name1 $value): self
    {
        $this->instance->setShopperName($value);
        return $this;
    }

    /**
     * Sets telephone Number field.
     *
     * @param string|null $value
     */
    public function telephoneNumber(?string $value): self
    {
        $this->instance->setTelephoneNumber($value);
        return $this;
    }

    /**
     * Sets wallet Identifier field.
     *
     * @param string|null $value
     */
    public function walletIdentifier(?string $value): self
    {
        $this->instance->setWalletIdentifier($value);
        return $this;
    }

    /**
     * Initializes a new Fund Origin 1 object.
     */
    public function build(): FundOrigin1
    {
        return CoreHelper::clone($this->instance);
    }
}
