<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\LineItem;
use Core\Utils\CoreHelper;

/**
 * Builder for model LineItem
 *
 * @see LineItem
 */
class LineItemBuilder
{
    /**
     * @var LineItem
     */
    private $instance;

    private function __construct(LineItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Line Item Builder object.
     */
    public static function init(): self
    {
        return new self(new LineItem());
    }

    /**
     * Sets amount Excluding Tax field.
     *
     * @param int|null $value
     */
    public function amountExcludingTax(?int $value): self
    {
        $this->instance->setAmountExcludingTax($value);
        return $this;
    }

    /**
     * Sets amount Including Tax field.
     *
     * @param int|null $value
     */
    public function amountIncludingTax(?int $value): self
    {
        $this->instance->setAmountIncludingTax($value);
        return $this;
    }

    /**
     * Sets brand field.
     *
     * @param string|null $value
     */
    public function brand(?string $value): self
    {
        $this->instance->setBrand($value);
        return $this;
    }

    /**
     * Sets color field.
     *
     * @param string|null $value
     */
    public function color(?string $value): self
    {
        $this->instance->setColor($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets image Url field.
     *
     * @param string|null $value
     */
    public function imageUrl(?string $value): self
    {
        $this->instance->setImageUrl($value);
        return $this;
    }

    /**
     * Sets item Category field.
     *
     * @param string|null $value
     */
    public function itemCategory(?string $value): self
    {
        $this->instance->setItemCategory($value);
        return $this;
    }

    /**
     * Sets manufacturer field.
     *
     * @param string|null $value
     */
    public function manufacturer(?string $value): self
    {
        $this->instance->setManufacturer($value);
        return $this;
    }

    /**
     * Sets marketplace Seller Id field.
     *
     * @param string|null $value
     */
    public function marketplaceSellerId(?string $value): self
    {
        $this->instance->setMarketplaceSellerId($value);
        return $this;
    }

    /**
     * Sets product Url field.
     *
     * @param string|null $value
     */
    public function productUrl(?string $value): self
    {
        $this->instance->setProductUrl($value);
        return $this;
    }

    /**
     * Sets quantity field.
     *
     * @param int|null $value
     */
    public function quantity(?int $value): self
    {
        $this->instance->setQuantity($value);
        return $this;
    }

    /**
     * Sets receiver Email field.
     *
     * @param string|null $value
     */
    public function receiverEmail(?string $value): self
    {
        $this->instance->setReceiverEmail($value);
        return $this;
    }

    /**
     * Sets size field.
     *
     * @param string|null $value
     */
    public function size(?string $value): self
    {
        $this->instance->setSize($value);
        return $this;
    }

    /**
     * Sets sku field.
     *
     * @param string|null $value
     */
    public function sku(?string $value): self
    {
        $this->instance->setSku($value);
        return $this;
    }

    /**
     * Sets tax Amount field.
     *
     * @param int|null $value
     */
    public function taxAmount(?int $value): self
    {
        $this->instance->setTaxAmount($value);
        return $this;
    }

    /**
     * Sets tax Percentage field.
     *
     * @param int|null $value
     */
    public function taxPercentage(?int $value): self
    {
        $this->instance->setTaxPercentage($value);
        return $this;
    }

    /**
     * Sets upc field.
     *
     * @param string|null $value
     */
    public function upc(?string $value): self
    {
        $this->instance->setUpc($value);
        return $this;
    }

    /**
     * Initializes a new Line Item object.
     */
    public function build(): LineItem
    {
        return CoreHelper::clone($this->instance);
    }
}
