<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\LinksElement15;
use Core\Utils\CoreHelper;

/**
 * Builder for model LinksElement15
 *
 * @see LinksElement15
 */
class LinksElement15Builder
{
    /**
     * @var LinksElement15
     */
    private $instance;

    private function __construct(LinksElement15 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Links Element 15 Builder object.
     */
    public static function init(): self
    {
        return new self(new LinksElement15());
    }

    /**
     * Sets href field.
     *
     * @param string|null $value
     */
    public function href(?string $value): self
    {
        $this->instance->setHref($value);
        return $this;
    }

    /**
     * Initializes a new Links Element 15 object.
     */
    public function build(): LinksElement15
    {
        return CoreHelper::clone($this->instance);
    }
}
