<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\LinksElement4;
use Core\Utils\CoreHelper;

/**
 * Builder for model LinksElement4
 *
 * @see LinksElement4
 */
class LinksElement4Builder
{
    /**
     * @var LinksElement4
     */
    private $instance;

    private function __construct(LinksElement4 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Links Element 4 Builder object.
     */
    public static function init(): self
    {
        return new self(new LinksElement4());
    }

    /**
     * Sets href field.
     *
     * @param string|null $value
     */
    public function href(?string $value): self
    {
        $this->instance->setHref($value);
        return $this;
    }

    /**
     * Initializes a new Links Element 4 object.
     */
    public function build(): LinksElement4
    {
        return CoreHelper::clone($this->instance);
    }
}
