<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\LinksElement2;
use Core\Utils\CoreHelper;

/**
 * Builder for model LinksElement2
 *
 * @see LinksElement2
 */
class LinksElement2Builder
{
    /**
     * @var LinksElement2
     */
    private $instance;

    private function __construct(LinksElement2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Links Element 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new LinksElement2());
    }

    /**
     * Sets href field.
     *
     * @param string|null $value
     */
    public function href(?string $value): self
    {
        $this->instance->setHref($value);
        return $this;
    }

    /**
     * Initializes a new Links Element 2 object.
     */
    public function build(): LinksElement2
    {
        return CoreHelper::clone($this->instance);
    }
}
