<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Links2;
use AdyenApIsLib\Models\LinksElement6;
use Core\Utils\CoreHelper;

/**
 * Builder for model Links2
 *
 * @see Links2
 */
class Links2Builder
{
    /**
     * @var Links2
     */
    private $instance;

    private function __construct(Links2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Links 2 Builder object.
     *
     * @param LinksElement6 $self
     */
    public static function init(LinksElement6 $self): self
    {
        return new self(new Links2($self));
    }

    /**
     * Initializes a new Links 2 object.
     */
    public function build(): Links2
    {
        return CoreHelper::clone($this->instance);
    }
}
