<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Localization;
use Core\Utils\CoreHelper;

/**
 * Builder for model Localization
 *
 * @see Localization
 */
class LocalizationBuilder
{
    /**
     * @var Localization
     */
    private $instance;

    private function __construct(Localization $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Localization Builder object.
     */
    public static function init(): self
    {
        return new self(new Localization());
    }

    /**
     * Sets language field.
     *
     * @param string|null $value
     */
    public function language(?string $value): self
    {
        $this->instance->setLanguage($value);
        return $this;
    }

    /**
     * Sets secondary Language field.
     *
     * @param string|null $value
     */
    public function secondaryLanguage(?string $value): self
    {
        $this->instance->setSecondaryLanguage($value);
        return $this;
    }

    /**
     * Sets timezone field.
     *
     * @param string|null $value
     */
    public function timezone(?string $value): self
    {
        $this->instance->setTimezone($value);
        return $this;
    }

    /**
     * Initializes a new Localization object.
     */
    public function build(): Localization
    {
        return CoreHelper::clone($this->instance);
    }
}
