<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\LocalizedInformation;
use AdyenApIsLib\Models\LocalShopperStatement;
use Core\Utils\CoreHelper;

/**
 * Builder for model LocalizedInformation
 *
 * @see LocalizedInformation
 */
class LocalizedInformationBuilder
{
    /**
     * @var LocalizedInformation
     */
    private $instance;

    private function __construct(LocalizedInformation $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Localized Information Builder object.
     *
     * @param LocalShopperStatement[] $localShopperStatement
     */
    public static function init(array $localShopperStatement): self
    {
        return new self(new LocalizedInformation($localShopperStatement));
    }

    /**
     * Initializes a new Localized Information object.
     */
    public function build(): LocalizedInformation
    {
        return CoreHelper::clone($this->instance);
    }
}
