<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Logo;
use Core\Utils\CoreHelper;

/**
 * Builder for model Logo
 *
 * @see Logo
 */
class LogoBuilder
{
    /**
     * @var Logo
     */
    private $instance;

    private function __construct(Logo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Logo Builder object.
     */
    public static function init(): self
    {
        return new self(new Logo());
    }

    /**
     * Sets data field.
     *
     * @param string|null $value
     */
    public function data(?string $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new Logo object.
     */
    public function build(): Logo
    {
        return CoreHelper::clone($this->instance);
    }
}
