<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\LinksElement;
use AdyenApIsLib\Models\LinksElement6;
use AdyenApIsLib\Models\MerchantLinks2;
use Core\Utils\CoreHelper;

/**
 * Builder for model MerchantLinks2
 *
 * @see MerchantLinks2
 */
class MerchantLinks2Builder
{
    /**
     * @var MerchantLinks2
     */
    private $instance;

    private function __construct(MerchantLinks2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Merchant Links 2 Builder object.
     *
     * @param LinksElement6 $self
     */
    public static function init(LinksElement6 $self): self
    {
        return new self(new MerchantLinks2($self));
    }

    /**
     * Sets api Credentials field.
     *
     * @param LinksElement|null $value
     */
    public function apiCredentials(?LinksElement $value): self
    {
        $this->instance->setApiCredentials($value);
        return $this;
    }

    /**
     * Sets users field.
     *
     * @param LinksElement|null $value
     */
    public function users(?LinksElement $value): self
    {
        $this->instance->setUsers($value);
        return $this;
    }

    /**
     * Sets webhooks field.
     *
     * @param LinksElement|null $value
     */
    public function webhooks(?LinksElement $value): self
    {
        $this->instance->setWebhooks($value);
        return $this;
    }

    /**
     * Initializes a new Merchant Links 2 object.
     */
    public function build(): MerchantLinks2
    {
        return CoreHelper::clone($this->instance);
    }
}
