<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\MerchantDevice2;
use Core\Utils\CoreHelper;

/**
 * Builder for model MerchantDevice2
 *
 * @see MerchantDevice2
 */
class MerchantDevice2Builder
{
    /**
     * @var MerchantDevice2
     */
    private $instance;

    private function __construct(MerchantDevice2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Merchant Device 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new MerchantDevice2());
    }

    /**
     * Sets os field.
     *
     * @param string|null $value
     */
    public function os(?string $value): self
    {
        $this->instance->setOs($value);
        return $this;
    }

    /**
     * Sets os Version field.
     *
     * @param string|null $value
     */
    public function osVersion(?string $value): self
    {
        $this->instance->setOsVersion($value);
        return $this;
    }

    /**
     * Sets reference field.
     *
     * @param string|null $value
     */
    public function reference(?string $value): self
    {
        $this->instance->setReference($value);
        return $this;
    }

    /**
     * Initializes a new Merchant Device 2 object.
     */
    public function build(): MerchantDevice2
    {
        return CoreHelper::clone($this->instance);
    }
}
