<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Moto;
use Core\Utils\CoreHelper;

/**
 * Builder for model Moto
 *
 * @see Moto
 */
class MotoBuilder
{
    /**
     * @var Moto
     */
    private $instance;

    private function __construct(Moto $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Moto Builder object.
     */
    public static function init(): self
    {
        return new self(new Moto());
    }

    /**
     * Sets enable Moto field.
     *
     * @param bool|null $value
     */
    public function enableMoto(?bool $value): self
    {
        $this->instance->setEnableMoto($value);
        return $this;
    }

    /**
     * Sets max Amount field.
     *
     * @param int|null $value
     */
    public function maxAmount(?int $value): self
    {
        $this->instance->setMaxAmount($value);
        return $this;
    }

    /**
     * Initializes a new Moto object.
     */
    public function build(): Moto
    {
        return CoreHelper::clone($this->instance);
    }
}
