<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Moto1;
use Core\Utils\CoreHelper;

/**
 * Builder for model Moto1
 *
 * @see Moto1
 */
class Moto1Builder
{
    /**
     * @var Moto1
     */
    private $instance;

    private function __construct(Moto1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Moto 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new Moto1());
    }

    /**
     * Sets enable Moto field.
     *
     * @param bool|null $value
     */
    public function enableMoto(?bool $value): self
    {
        $this->instance->setEnableMoto($value);
        return $this;
    }

    /**
     * Sets max Amount field.
     *
     * @param int|null $value
     */
    public function maxAmount(?int $value): self
    {
        $this->instance->setMaxAmount($value);
        return $this;
    }

    /**
     * Initializes a new Moto 1 object.
     */
    public function build(): Moto1
    {
        return CoreHelper::clone($this->instance);
    }
}
