<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\MinorUnitsMonetaryValue;
use AdyenApIsLib\Models\OfflineProcessing;
use Core\Utils\CoreHelper;

/**
 * Builder for model OfflineProcessing
 *
 * @see OfflineProcessing
 */
class OfflineProcessingBuilder
{
    /**
     * @var OfflineProcessing
     */
    private $instance;

    private function __construct(OfflineProcessing $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Offline Processing Builder object.
     */
    public static function init(): self
    {
        return new self(new OfflineProcessing());
    }

    /**
     * Sets chip Floor Limit field.
     *
     * @param int|null $value
     */
    public function chipFloorLimit(?int $value): self
    {
        $this->instance->setChipFloorLimit($value);
        return $this;
    }

    /**
     * Sets offline Swipe Limits field.
     *
     * @param MinorUnitsMonetaryValue[]|null $value
     */
    public function offlineSwipeLimits(?array $value): self
    {
        $this->instance->setOfflineSwipeLimits($value);
        return $this;
    }

    /**
     * Initializes a new Offline Processing object.
     */
    public function build(): OfflineProcessing
    {
        return CoreHelper::clone($this->instance);
    }
}
