<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Opi1;
use Core\Utils\CoreHelper;

/**
 * Builder for model Opi1
 *
 * @see Opi1
 */
class Opi1Builder
{
    /**
     * @var Opi1
     */
    private $instance;

    private function __construct(Opi1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Opi 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new Opi1());
    }

    /**
     * Sets enable Pay At Table field.
     *
     * @param bool|null $value
     */
    public function enablePayAtTable(?bool $value): self
    {
        $this->instance->setEnablePayAtTable($value);
        return $this;
    }

    /**
     * Sets pay At Table Store Number field.
     *
     * @param string|null $value
     */
    public function payAtTableStoreNumber(?string $value): self
    {
        $this->instance->setPayAtTableStoreNumber($value);
        return $this;
    }

    /**
     * Sets pay At Table URL field.
     *
     * @param string|null $value
     */
    public function payAtTableUrl(?string $value): self
    {
        $this->instance->setPayAtTableUrl($value);
        return $this;
    }

    /**
     * Initializes a new Opi 1 object.
     */
    public function build(): Opi1
    {
        return CoreHelper::clone($this->instance);
    }
}
