<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\OrderItem;
use Core\Utils\CoreHelper;

/**
 * Builder for model OrderItem
 *
 * @see OrderItem
 */
class OrderItemBuilder
{
    /**
     * @var OrderItem
     */
    private $instance;

    private function __construct(OrderItem $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Order Item Builder object.
     */
    public static function init(): self
    {
        return new self(new OrderItem());
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets installments field.
     *
     * @param int|null $value
     */
    public function installments(?int $value): self
    {
        $this->instance->setInstallments($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets quantity field.
     *
     * @param int|null $value
     */
    public function quantity(?int $value): self
    {
        $this->instance->setQuantity($value);
        return $this;
    }

    /**
     * Initializes a new Order Item object.
     */
    public function build(): OrderItem
    {
        return CoreHelper::clone($this->instance);
    }
}
