<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Passenger;
use Core\Utils\CoreHelper;

/**
 * Builder for model Passenger
 *
 * @see Passenger
 */
class PassengerBuilder
{
    /**
     * @var Passenger
     */
    private $instance;

    private function __construct(Passenger $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Passenger Builder object.
     */
    public static function init(): self
    {
        return new self(new Passenger());
    }

    /**
     * Sets date Of Birth field.
     *
     * @param \DateTime|null $value
     */
    public function dateOfBirth(?\DateTime $value): self
    {
        $this->instance->setDateOfBirth($value);
        return $this;
    }

    /**
     * Sets first Name field.
     *
     * @param string|null $value
     */
    public function firstName(?string $value): self
    {
        $this->instance->setFirstName($value);
        return $this;
    }

    /**
     * Sets last Name field.
     *
     * @param string|null $value
     */
    public function lastName(?string $value): self
    {
        $this->instance->setLastName($value);
        return $this;
    }

    /**
     * Sets phone Number field.
     *
     * @param string|null $value
     */
    public function phoneNumber(?string $value): self
    {
        $this->instance->setPhoneNumber($value);
        return $this;
    }

    /**
     * Sets traveller Type field.
     *
     * @param string|null $value
     */
    public function travellerType(?string $value): self
    {
        $this->instance->setTravellerType($value);
        return $this;
    }

    /**
     * Initializes a new Passenger object.
     */
    public function build(): Passenger
    {
        return CoreHelper::clone($this->instance);
    }
}
