<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Passcodes;
use Core\Utils\CoreHelper;

/**
 * Builder for model Passcodes
 *
 * @see Passcodes
 */
class PasscodesBuilder
{
    /**
     * @var Passcodes
     */
    private $instance;

    private function __construct(Passcodes $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Passcodes Builder object.
     */
    public static function init(): self
    {
        return new self(new Passcodes());
    }

    /**
     * Sets admin Menu Pin field.
     *
     * @param string|null $value
     */
    public function adminMenuPin(?string $value): self
    {
        $this->instance->setAdminMenuPin($value);
        return $this;
    }

    /**
     * Sets refund Pin field.
     *
     * @param string|null $value
     */
    public function refundPin(?string $value): self
    {
        $this->instance->setRefundPin($value);
        return $this;
    }

    /**
     * Sets screen Lock Pin field.
     *
     * @param string|null $value
     */
    public function screenLockPin(?string $value): self
    {
        $this->instance->setScreenLockPin($value);
        return $this;
    }

    /**
     * Sets tx Menu Pin field.
     *
     * @param string|null $value
     */
    public function txMenuPin(?string $value): self
    {
        $this->instance->setTxMenuPin($value);
        return $this;
    }

    /**
     * Initializes a new Passcodes object.
     */
    public function build(): Passcodes
    {
        return CoreHelper::clone($this->instance);
    }
}
