<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\PaymentValidationsNameResultResponse;
use Core\Utils\CoreHelper;

/**
 * Builder for model PaymentValidationsNameResultResponse
 *
 * @see PaymentValidationsNameResultResponse
 */
class PaymentValidationsNameResultResponseBuilder
{
    /**
     * @var PaymentValidationsNameResultResponse
     */
    private $instance;

    private function __construct(PaymentValidationsNameResultResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payment Validations Name Result Response Builder object.
     */
    public static function init(): self
    {
        return new self(new PaymentValidationsNameResultResponse());
    }

    /**
     * Sets first Name field.
     *
     * @param string|null $value
     */
    public function firstName(?string $value): self
    {
        $this->instance->setFirstName($value);
        return $this;
    }

    /**
     * Sets full Name field.
     *
     * @param string|null $value
     */
    public function fullName(?string $value): self
    {
        $this->instance->setFullName($value);
        return $this;
    }

    /**
     * Sets last Name field.
     *
     * @param string|null $value
     */
    public function lastName(?string $value): self
    {
        $this->instance->setLastName($value);
        return $this;
    }

    /**
     * Sets middle Name field.
     *
     * @param string|null $value
     */
    public function middleName(?string $value): self
    {
        $this->instance->setMiddleName($value);
        return $this;
    }

    /**
     * Initializes a new Payment Validations Name Result Response object.
     */
    public function build(): PaymentValidationsNameResultResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
