<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\PayoutSettingsRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model PayoutSettingsRequest
 *
 * @see PayoutSettingsRequest
 */
class PayoutSettingsRequestBuilder
{
    /**
     * @var PayoutSettingsRequest
     */
    private $instance;

    private function __construct(PayoutSettingsRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Payout Settings Request Builder object.
     *
     * @param string $transferInstrumentId
     */
    public static function init(string $transferInstrumentId): self
    {
        return new self(new PayoutSettingsRequest($transferInstrumentId));
    }

    /**
     * Sets enabled field.
     *
     * @param bool|null $value
     */
    public function enabled(?bool $value): self
    {
        $this->instance->setEnabled($value);
        return $this;
    }

    /**
     * Sets enabled From Date field.
     *
     * @param string|null $value
     */
    public function enabledFromDate(?string $value): self
    {
        $this->instance->setEnabledFromDate($value);
        return $this;
    }

    /**
     * Initializes a new Payout Settings Request object.
     */
    public function build(): PayoutSettingsRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
