<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\PayPay;
use Core\Utils\CoreHelper;

/**
 * Builder for model PayPay
 *
 * @see PayPay
 */
class PayPayBuilder
{
    /**
     * @var PayPay
     */
    private $instance;

    private function __construct(PayPay $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pay Pay Builder object.
     */
    public static function init(): self
    {
        return new self(new PayPay());
    }

    /**
     * Sets checkout Attempt Id field.
     *
     * @param string|null $value
     */
    public function checkoutAttemptId(?string $value): self
    {
        $this->instance->setCheckoutAttemptId($value);
        return $this;
    }

    /**
     * Sets recurring Detail Reference field.
     *
     * @param string|null $value
     */
    public function recurringDetailReference(?string $value): self
    {
        $this->instance->setRecurringDetailReference($value);
        return $this;
    }

    /**
     * Sets sdk Data field.
     *
     * @param string|null $value
     */
    public function sdkData(?string $value): self
    {
        $this->instance->setSdkData($value);
        return $this;
    }

    /**
     * Sets stored Payment Method Id field.
     *
     * @param string|null $value
     */
    public function storedPaymentMethodId(?string $value): self
    {
        $this->instance->setStoredPaymentMethodId($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Initializes a new Pay Pay object.
     */
    public function build(): PayPay
    {
        return CoreHelper::clone($this->instance);
    }
}
