<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\PayToInfo;
use Core\Utils\CoreHelper;

/**
 * Builder for model PayToInfo
 *
 * @see PayToInfo
 */
class PayToInfoBuilder
{
    /**
     * @var PayToInfo
     */
    private $instance;

    private function __construct(PayToInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pay To Info Builder object.
     *
     * @param string $merchantName
     * @param string $payToPurpose
     */
    public static function init(string $merchantName, string $payToPurpose): self
    {
        return new self(new PayToInfo($merchantName, $payToPurpose));
    }

    /**
     * Initializes a new Pay To Info object.
     */
    public function build(): PayToInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
