<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\PayToPaymentMethod;
use Core\Utils\CoreHelper;

/**
 * Builder for model PayToPaymentMethod
 *
 * @see PayToPaymentMethod
 */
class PayToPaymentMethodBuilder
{
    /**
     * @var PayToPaymentMethod
     */
    private $instance;

    private function __construct(PayToPaymentMethod $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Pay To Payment Method Builder object.
     */
    public static function init(): self
    {
        return new self(new PayToPaymentMethod());
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets shopper Reference field.
     *
     * @param string|null $value
     */
    public function shopperReference(?string $value): self
    {
        $this->instance->setShopperReference($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Pay To Payment Method object.
     */
    public function build(): PayToPaymentMethod
    {
        return CoreHelper::clone($this->instance);
    }
}
