<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Phone;
use Core\Utils\CoreHelper;

/**
 * Builder for model Phone
 *
 * @see Phone
 */
class PhoneBuilder
{
    /**
     * @var Phone
     */
    private $instance;

    private function __construct(Phone $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Phone Builder object.
     */
    public static function init(): self
    {
        return new self(new Phone());
    }

    /**
     * Sets cc field.
     *
     * @param string|null $value
     */
    public function cc(?string $value): self
    {
        $this->instance->setCc($value);
        return $this;
    }

    /**
     * Sets subscriber field.
     *
     * @param string|null $value
     */
    public function subscriber(?string $value): self
    {
        $this->instance->setSubscriber($value);
        return $this;
    }

    /**
     * Initializes a new Phone object.
     */
    public function build(): Phone
    {
        return CoreHelper::clone($this->instance);
    }
}
