<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\ReceiptOptions1;
use Core\Utils\CoreHelper;

/**
 * Builder for model ReceiptOptions1
 *
 * @see ReceiptOptions1
 */
class ReceiptOptions1Builder
{
    /**
     * @var ReceiptOptions1
     */
    private $instance;

    private function __construct(ReceiptOptions1 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Receipt Options 1 Builder object.
     */
    public static function init(): self
    {
        return new self(new ReceiptOptions1());
    }

    /**
     * Sets logo field.
     *
     * @param string|null $value
     */
    public function logo(?string $value): self
    {
        $this->instance->setLogo($value);
        return $this;
    }

    /**
     * Sets prompt Before Printing field.
     *
     * @param bool|null $value
     */
    public function promptBeforePrinting(?bool $value): self
    {
        $this->instance->setPromptBeforePrinting($value);
        return $this;
    }

    /**
     * Sets qr Code Data field.
     *
     * @param string|null $value
     */
    public function qrCodeData(?string $value): self
    {
        $this->instance->setQrCodeData($value);
        return $this;
    }

    /**
     * Initializes a new Receipt Options 1 object.
     */
    public function build(): ReceiptOptions1
    {
        return CoreHelper::clone($this->instance);
    }
}
