<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\ForceRebootDetails;
use AdyenApIsLib\Models\InstallAndroidAppDetails;
use AdyenApIsLib\Models\InstallAndroidCertificateDetails;
use AdyenApIsLib\Models\ReleaseUpdateDetails;
use AdyenApIsLib\Models\ScheduleTerminalActionsResponse;
use AdyenApIsLib\Models\TerminalActionScheduleDetail;
use AdyenApIsLib\Models\UninstallAndroidAppDetails;
use AdyenApIsLib\Models\UninstallAndroidCertificateDetails;
use Core\Utils\CoreHelper;

/**
 * Builder for model ScheduleTerminalActionsResponse
 *
 * @see ScheduleTerminalActionsResponse
 */
class ScheduleTerminalActionsResponseBuilder
{
    /**
     * @var ScheduleTerminalActionsResponse
     */
    private $instance;

    private function __construct(ScheduleTerminalActionsResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Schedule Terminal Actions Response Builder object.
     */
    public static function init(): self
    {
        return new self(new ScheduleTerminalActionsResponse());
    }

    /**
     * Sets action Details field.
     *
     * @param ForceRebootDetails|InstallAndroidAppDetails|InstallAndroidCertificateDetails|ReleaseUpdateDetails|UninstallAndroidAppDetails|UninstallAndroidCertificateDetails|null $value
     */
    public function actionDetails($value): self
    {
        $this->instance->setActionDetails($value);
        return $this;
    }

    /**
     * Sets items field.
     *
     * @param TerminalActionScheduleDetail[]|null $value
     */
    public function items(?array $value): self
    {
        $this->instance->setItems($value);
        return $this;
    }

    /**
     * Sets scheduled At field.
     *
     * @param string|null $value
     */
    public function scheduledAt(?string $value): self
    {
        $this->instance->setScheduledAt($value);
        return $this;
    }

    /**
     * Sets store Id field.
     *
     * @param string|null $value
     */
    public function storeId(?string $value): self
    {
        $this->instance->setStoreId($value);
        return $this;
    }

    /**
     * Sets terminals With Errors field.
     *
     * @param array|null $value
     */
    public function terminalsWithErrors(?array $value): self
    {
        $this->instance->setTerminalsWithErrors($value);
        return $this;
    }

    /**
     * Sets total Errors field.
     *
     * @param int|null $value
     */
    public function totalErrors(?int $value): self
    {
        $this->instance->setTotalErrors($value);
        return $this;
    }

    /**
     * Sets total Scheduled field.
     *
     * @param int|null $value
     */
    public function totalScheduled(?int $value): self
    {
        $this->instance->setTotalScheduled($value);
        return $this;
    }

    /**
     * Initializes a new Schedule Terminal Actions Response object.
     */
    public function build(): ScheduleTerminalActionsResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
