<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\SplitConfiguration;
use AdyenApIsLib\Models\SplitConfigurationList;
use Core\Utils\CoreHelper;

/**
 * Builder for model SplitConfigurationList
 *
 * @see SplitConfigurationList
 */
class SplitConfigurationListBuilder
{
    /**
     * @var SplitConfigurationList
     */
    private $instance;

    private function __construct(SplitConfigurationList $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Split Configuration List Builder object.
     */
    public static function init(): self
    {
        return new self(new SplitConfigurationList());
    }

    /**
     * Sets data field.
     *
     * @param SplitConfiguration[]|null $value
     */
    public function data(?array $value): self
    {
        $this->instance->setData($value);
        return $this;
    }

    /**
     * Initializes a new Split Configuration List object.
     */
    public function build(): SplitConfigurationList
    {
        return CoreHelper::clone($this->instance);
    }
}
