<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\StandalonePaymentCancelResponse;
use Core\Utils\CoreHelper;

/**
 * Builder for model StandalonePaymentCancelResponse
 *
 * @see StandalonePaymentCancelResponse
 */
class StandalonePaymentCancelResponseBuilder
{
    /**
     * @var StandalonePaymentCancelResponse
     */
    private $instance;

    private function __construct(StandalonePaymentCancelResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Standalone Payment Cancel Response Builder object.
     *
     * @param string $merchantAccount
     * @param string $paymentReference
     * @param string $pspReference
     */
    public static function init(string $merchantAccount, string $paymentReference, string $pspReference): self
    {
        return new self(new StandalonePaymentCancelResponse($merchantAccount, $paymentReference, $pspReference));
    }

    /**
     * Sets reference field.
     *
     * @param string|null $value
     */
    public function reference(?string $value): self
    {
        $this->instance->setReference($value);
        return $this;
    }

    /**
     * Initializes a new Standalone Payment Cancel Response object.
     */
    public function build(): StandalonePaymentCancelResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
