<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Standalone;
use Core\Utils\CoreHelper;

/**
 * Builder for model Standalone
 *
 * @see Standalone
 */
class StandaloneBuilder
{
    /**
     * @var Standalone
     */
    private $instance;

    private function __construct(Standalone $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Standalone Builder object.
     */
    public static function init(): self
    {
        return new self(new Standalone());
    }

    /**
     * Sets currency Code field.
     *
     * @param string|null $value
     */
    public function currencyCode(?string $value): self
    {
        $this->instance->setCurrencyCode($value);
        return $this;
    }

    /**
     * Sets enable Gratuities field.
     *
     * @param bool|null $value
     */
    public function enableGratuities(?bool $value): self
    {
        $this->instance->setEnableGratuities($value);
        return $this;
    }

    /**
     * Sets enable Standalone field.
     *
     * @param bool|null $value
     */
    public function enableStandalone(?bool $value): self
    {
        $this->instance->setEnableStandalone($value);
        return $this;
    }

    /**
     * Initializes a new Standalone object.
     */
    public function build(): Standalone
    {
        return CoreHelper::clone($this->instance);
    }
}
