<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\StarInfo;
use AdyenApIsLib\Models\TransactionDescriptionInfo1;
use Core\Utils\CoreHelper;

/**
 * Builder for model StarInfo
 *
 * @see StarInfo
 */
class StarInfoBuilder
{
    /**
     * @var StarInfo
     */
    private $instance;

    private function __construct(StarInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Star Info Builder object.
     *
     * @param string $processingType
     */
    public static function init(string $processingType): self
    {
        return new self(new StarInfo($processingType));
    }

    /**
     * Sets transaction Description field.
     *
     * @param TransactionDescriptionInfo1|null $value
     */
    public function transactionDescription(?TransactionDescriptionInfo1 $value): self
    {
        $this->instance->setTransactionDescription($value);
        return $this;
    }

    /**
     * Initializes a new Star Info object.
     */
    public function build(): StarInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
