<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\MinorUnitsMonetaryValue;
use AdyenApIsLib\Models\StoreAndForward;
use AdyenApIsLib\Models\SupportedCardTypes2;
use Core\Utils\CoreHelper;

/**
 * Builder for model StoreAndForward
 *
 * @see StoreAndForward
 */
class StoreAndForwardBuilder
{
    /**
     * @var StoreAndForward
     */
    private $instance;

    private function __construct(StoreAndForward $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Store And Forward Builder object.
     */
    public static function init(): self
    {
        return new self(new StoreAndForward());
    }

    /**
     * Sets max Amount field.
     *
     * @param MinorUnitsMonetaryValue[]|null $value
     */
    public function maxAmount(?array $value): self
    {
        $this->instance->setMaxAmount($value);
        return $this;
    }

    /**
     * Sets max Payments field.
     *
     * @param int|null $value
     */
    public function maxPayments(?int $value): self
    {
        $this->instance->setMaxPayments($value);
        return $this;
    }

    /**
     * Sets supported Card Types field.
     *
     * @param SupportedCardTypes2|null $value
     */
    public function supportedCardTypes(?SupportedCardTypes2 $value): self
    {
        $this->instance->setSupportedCardTypes($value);
        return $this;
    }

    /**
     * Initializes a new Store And Forward object.
     */
    public function build(): StoreAndForward
    {
        return CoreHelper::clone($this->instance);
    }
}
