<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Surcharge;
use Core\Utils\CoreHelper;

/**
 * Builder for model Surcharge
 *
 * @see Surcharge
 */
class SurchargeBuilder
{
    /**
     * @var Surcharge
     */
    private $instance;

    private function __construct(Surcharge $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Surcharge Builder object.
     *
     * @param int $value
     */
    public static function init(int $value): self
    {
        return new self(new Surcharge($value));
    }

    /**
     * Initializes a new Surcharge object.
     */
    public function build(): Surcharge
    {
        return CoreHelper::clone($this->instance);
    }
}
