<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Amount;
use AdyenApIsLib\Models\TaxTotal2;
use Core\Utils\CoreHelper;

/**
 * Builder for model TaxTotal2
 *
 * @see TaxTotal2
 */
class TaxTotal2Builder
{
    /**
     * @var TaxTotal2
     */
    private $instance;

    private function __construct(TaxTotal2 $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Tax Total 2 Builder object.
     */
    public static function init(): self
    {
        return new self(new TaxTotal2());
    }

    /**
     * Sets amount field.
     *
     * @param Amount|null $value
     */
    public function amount(?Amount $value): self
    {
        $this->instance->setAmount($value);
        return $this;
    }

    /**
     * Initializes a new Tax Total 2 object.
     */
    public function build(): TaxTotal2
    {
        return CoreHelper::clone($this->instance);
    }
}
