<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\TerminalProduct;
use AdyenApIsLib\Models\TerminalProductPrice2;
use Core\Utils\CoreHelper;

/**
 * Builder for model TerminalProduct
 *
 * @see TerminalProduct
 */
class TerminalProductBuilder
{
    /**
     * @var TerminalProduct
     */
    private $instance;

    private function __construct(TerminalProduct $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Terminal Product Builder object.
     */
    public static function init(): self
    {
        return new self(new TerminalProduct());
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets id field.
     *
     * @param string|null $value
     */
    public function id(?string $value): self
    {
        $this->instance->setId($value);
        return $this;
    }

    /**
     * Sets items Included field.
     *
     * @param string[]|null $value
     */
    public function itemsIncluded(?array $value): self
    {
        $this->instance->setItemsIncluded($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets price field.
     *
     * @param TerminalProductPrice2|null $value
     */
    public function price(?TerminalProductPrice2 $value): self
    {
        $this->instance->setPrice($value);
        return $this;
    }

    /**
     * Initializes a new Terminal Product object.
     */
    public function build(): TerminalProduct
    {
        return CoreHelper::clone($this->instance);
    }
}
