<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\TerminalConnectivityEthernet;
use Core\Utils\CoreHelper;

/**
 * Builder for model TerminalConnectivityEthernet
 *
 * @see TerminalConnectivityEthernet
 */
class TerminalConnectivityEthernetBuilder
{
    /**
     * @var TerminalConnectivityEthernet
     */
    private $instance;

    private function __construct(TerminalConnectivityEthernet $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Terminal Connectivity Ethernet Builder object.
     */
    public static function init(): self
    {
        return new self(new TerminalConnectivityEthernet());
    }

    /**
     * Sets ip Address field.
     *
     * @param string|null $value
     */
    public function ipAddress(?string $value): self
    {
        $this->instance->setIpAddress($value);
        return $this;
    }

    /**
     * Sets link Negotiation field.
     *
     * @param string|null $value
     */
    public function linkNegotiation(?string $value): self
    {
        $this->instance->setLinkNegotiation($value);
        return $this;
    }

    /**
     * Sets mac Address field.
     *
     * @param string|null $value
     */
    public function macAddress(?string $value): self
    {
        $this->instance->setMacAddress($value);
        return $this;
    }

    /**
     * Initializes a new Terminal Connectivity Ethernet object.
     */
    public function build(): TerminalConnectivityEthernet
    {
        return CoreHelper::clone($this->instance);
    }
}
