<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\TransactionDescriptionInfo;
use Core\Utils\CoreHelper;

/**
 * Builder for model TransactionDescriptionInfo
 *
 * @see TransactionDescriptionInfo
 */
class TransactionDescriptionInfoBuilder
{
    /**
     * @var TransactionDescriptionInfo
     */
    private $instance;

    private function __construct(TransactionDescriptionInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Transaction Description Info Builder object.
     */
    public static function init(): self
    {
        return new self(new TransactionDescriptionInfo());
    }

    /**
     * Sets doing Business As Name field.
     *
     * @param string|null $value
     */
    public function doingBusinessAsName(?string $value): self
    {
        $this->instance->setDoingBusinessAsName($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Initializes a new Transaction Description Info object.
     */
    public function build(): TransactionDescriptionInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
