<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\UninstallAndroidCertificateDetails;
use Core\Utils\CoreHelper;

/**
 * Builder for model UninstallAndroidCertificateDetails
 *
 * @see UninstallAndroidCertificateDetails
 */
class UninstallAndroidCertificateDetailsBuilder
{
    /**
     * @var UninstallAndroidCertificateDetails
     */
    private $instance;

    private function __construct(UninstallAndroidCertificateDetails $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Uninstall Android Certificate Details Builder object.
     */
    public static function init(): self
    {
        return new self(new UninstallAndroidCertificateDetails());
    }

    /**
     * Sets certificate Id field.
     *
     * @param string|null $value
     */
    public function certificateId(?string $value): self
    {
        $this->instance->setCertificateId($value);
        return $this;
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Uninstall Android Certificate Details object.
     */
    public function build(): UninstallAndroidCertificateDetails
    {
        return CoreHelper::clone($this->instance);
    }
}
