<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\UpdatableAddress;
use Core\Utils\CoreHelper;

/**
 * Builder for model UpdatableAddress
 *
 * @see UpdatableAddress
 */
class UpdatableAddressBuilder
{
    /**
     * @var UpdatableAddress
     */
    private $instance;

    private function __construct(UpdatableAddress $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Updatable Address Builder object.
     */
    public static function init(): self
    {
        return new self(new UpdatableAddress());
    }

    /**
     * Sets city field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets line 1 field.
     *
     * @param string|null $value
     */
    public function line1(?string $value): self
    {
        $this->instance->setLine1($value);
        return $this;
    }

    /**
     * Sets line 2 field.
     *
     * @param string|null $value
     */
    public function line2(?string $value): self
    {
        $this->instance->setLine2($value);
        return $this;
    }

    /**
     * Sets line 3 field.
     *
     * @param string|null $value
     */
    public function line3(?string $value): self
    {
        $this->instance->setLine3($value);
        return $this;
    }

    /**
     * Sets postal Code field.
     *
     * @param string|null $value
     */
    public function postalCode(?string $value): self
    {
        $this->instance->setPostalCode($value);
        return $this;
    }

    /**
     * Sets state Or Province field.
     *
     * @param string|null $value
     */
    public function stateOrProvince(?string $value): self
    {
        $this->instance->setStateOrProvince($value);
        return $this;
    }

    /**
     * Initializes a new Updatable Address object.
     */
    public function build(): UpdatableAddress
    {
        return CoreHelper::clone($this->instance);
    }
}
