<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\AdditionalSettings1;
use AdyenApIsLib\Models\UpdateCompanyWebhookRequest;
use Core\Utils\CoreHelper;

/**
 * Builder for model UpdateCompanyWebhookRequest
 *
 * @see UpdateCompanyWebhookRequest
 */
class UpdateCompanyWebhookRequestBuilder
{
    /**
     * @var UpdateCompanyWebhookRequest
     */
    private $instance;

    private function __construct(UpdateCompanyWebhookRequest $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Company Webhook Request Builder object.
     */
    public static function init(): self
    {
        return new self(new UpdateCompanyWebhookRequest());
    }

    /**
     * Sets accepts Expired Certificate field.
     *
     * @param bool|null $value
     */
    public function acceptsExpiredCertificate(?bool $value): self
    {
        $this->instance->setAcceptsExpiredCertificate($value);
        return $this;
    }

    /**
     * Sets accepts Self Signed Certificate field.
     *
     * @param bool|null $value
     */
    public function acceptsSelfSignedCertificate(?bool $value): self
    {
        $this->instance->setAcceptsSelfSignedCertificate($value);
        return $this;
    }

    /**
     * Sets accepts Untrusted Root Certificate field.
     *
     * @param bool|null $value
     */
    public function acceptsUntrustedRootCertificate(?bool $value): self
    {
        $this->instance->setAcceptsUntrustedRootCertificate($value);
        return $this;
    }

    /**
     * Sets active field.
     *
     * @param bool|null $value
     */
    public function active(?bool $value): self
    {
        $this->instance->setActive($value);
        return $this;
    }

    /**
     * Sets additional Settings field.
     *
     * @param AdditionalSettings1|null $value
     */
    public function additionalSettings(?AdditionalSettings1 $value): self
    {
        $this->instance->setAdditionalSettings($value);
        return $this;
    }

    /**
     * Sets communication Format field.
     *
     * @param string|null $value
     */
    public function communicationFormat(?string $value): self
    {
        $this->instance->setCommunicationFormat($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets encryption Protocol field.
     *
     * @param string|null $value
     */
    public function encryptionProtocol(?string $value): self
    {
        $this->instance->setEncryptionProtocol($value);
        return $this;
    }

    /**
     * Sets filter Merchant Account Type field.
     *
     * @param string|null $value
     */
    public function filterMerchantAccountType(?string $value): self
    {
        $this->instance->setFilterMerchantAccountType($value);
        return $this;
    }

    /**
     * Sets filter Merchant Accounts field.
     *
     * @param string[]|null $value
     */
    public function filterMerchantAccounts(?array $value): self
    {
        $this->instance->setFilterMerchantAccounts($value);
        return $this;
    }

    /**
     * Sets network Type field.
     *
     * @param string|null $value
     */
    public function networkType(?string $value): self
    {
        $this->instance->setNetworkType($value);
        return $this;
    }

    /**
     * Sets password field.
     *
     * @param string|null $value
     */
    public function password(?string $value): self
    {
        $this->instance->setPassword($value);
        return $this;
    }

    /**
     * Sets populate Soap Action Header field.
     *
     * @param bool|null $value
     */
    public function populateSoapActionHeader(?bool $value): self
    {
        $this->instance->setPopulateSoapActionHeader($value);
        return $this;
    }

    /**
     * Sets url field.
     *
     * @param string|null $value
     */
    public function url(?string $value): self
    {
        $this->instance->setUrl($value);
        return $this;
    }

    /**
     * Sets username field.
     *
     * @param string|null $value
     */
    public function username(?string $value): self
    {
        $this->instance->setUsername($value);
        return $this;
    }

    /**
     * Initializes a new Update Company Webhook Request object.
     */
    public function build(): UpdateCompanyWebhookRequest
    {
        return CoreHelper::clone($this->instance);
    }
}
