<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\UpiQr;
use Core\Utils\CoreHelper;

/**
 * Builder for model UpiQr
 *
 * @see UpiQr
 */
class UpiQrBuilder
{
    /**
     * @var UpiQr
     */
    private $instance;

    private function __construct(UpiQr $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Upi Qr Builder object.
     */
    public static function init(): self
    {
        return new self(new UpiQr());
    }

    /**
     * Sets billing Sequence Number field.
     *
     * @param string|null $value
     */
    public function billingSequenceNumber(?string $value): self
    {
        $this->instance->setBillingSequenceNumber($value);
        return $this;
    }

    /**
     * Sets checkout Attempt Id field.
     *
     * @param string|null $value
     */
    public function checkoutAttemptId(?string $value): self
    {
        $this->instance->setCheckoutAttemptId($value);
        return $this;
    }

    /**
     * Sets recurring Detail Reference field.
     *
     * @param string|null $value
     */
    public function recurringDetailReference(?string $value): self
    {
        $this->instance->setRecurringDetailReference($value);
        return $this;
    }

    /**
     * Sets sdk Data field.
     *
     * @param string|null $value
     */
    public function sdkData(?string $value): self
    {
        $this->instance->setSdkData($value);
        return $this;
    }

    /**
     * Sets shopper Notification Reference field.
     *
     * @param string|null $value
     */
    public function shopperNotificationReference(?string $value): self
    {
        $this->instance->setShopperNotificationReference($value);
        return $this;
    }

    /**
     * Sets stored Payment Method Id field.
     *
     * @param string|null $value
     */
    public function storedPaymentMethodId(?string $value): self
    {
        $this->instance->setStoredPaymentMethodId($value);
        return $this;
    }

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function additionalProperty(string $name, $value): self
    {
        $this->instance->addAdditionalProperty($name, $value);
        return $this;
    }

    /**
     * Initializes a new Upi Qr object.
     */
    public function build(): UpiQr
    {
        return CoreHelper::clone($this->instance);
    }
}
