<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\Links1;
use AdyenApIsLib\Models\Name;
use AdyenApIsLib\Models\User;
use Core\Utils\CoreHelper;

/**
 * Builder for model User
 *
 * @see User
 */
class UserBuilder
{
    /**
     * @var User
     */
    private $instance;

    private function __construct(User $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new User Builder object.
     *
     * @param string $email
     * @param string $id
     * @param string[] $roles
     * @param string $timeZoneCode
     * @param string $username
     */
    public static function init(string $email, string $id, array $roles, string $timeZoneCode, string $username): self
    {
        return new self(new User($email, $id, $roles, $timeZoneCode, $username));
    }

    /**
     * Sets links field.
     *
     * @param Links1|null $value
     */
    public function links(?Links1 $value): self
    {
        $this->instance->setLinks($value);
        return $this;
    }

    /**
     * Sets account Groups field.
     *
     * @param string[]|null $value
     */
    public function accountGroups(?array $value): self
    {
        $this->instance->setAccountGroups($value);
        return $this;
    }

    /**
     * Sets active field.
     *
     * @param bool|null $value
     */
    public function active(?bool $value): self
    {
        $this->instance->setActive($value);
        return $this;
    }

    /**
     * Sets apps field.
     *
     * @param string[]|null $value
     */
    public function apps(?array $value): self
    {
        $this->instance->setApps($value);
        return $this;
    }

    /**
     * Sets name field.
     *
     * @param Name|null $value
     */
    public function name(?Name $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Initializes a new User object.
     */
    public function build(): User
    {
        return CoreHelper::clone($this->instance);
    }
}
