<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\UtilityResponse;
use Core\Utils\CoreHelper;

/**
 * Builder for model UtilityResponse
 *
 * @see UtilityResponse
 */
class UtilityResponseBuilder
{
    /**
     * @var UtilityResponse
     */
    private $instance;

    private function __construct(UtilityResponse $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Utility Response Builder object.
     */
    public static function init(): self
    {
        return new self(new UtilityResponse());
    }

    /**
     * Sets origin Keys field.
     *
     * @param array<string,string>|null $value
     */
    public function originKeys(?array $value): self
    {
        $this->instance->setOriginKeys($value);
        return $this;
    }

    /**
     * Initializes a new Utility Response object.
     */
    public function build(): UtilityResponse
    {
        return CoreHelper::clone($this->instance);
    }
}
