<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\ValuelinkInfo;
use Core\Utils\CoreHelper;

/**
 * Builder for model ValuelinkInfo
 *
 * @see ValuelinkInfo
 */
class ValuelinkInfoBuilder
{
    /**
     * @var ValuelinkInfo
     */
    private $instance;

    private function __construct(ValuelinkInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Valuelink Info Builder object.
     *
     * @param string $authorisationMid
     * @param string $pinSupport
     */
    public static function init(string $authorisationMid, string $pinSupport): self
    {
        return new self(new ValuelinkInfo($authorisationMid, $pinSupport));
    }

    /**
     * Sets submitter Id field.
     *
     * @param string|null $value
     */
    public function submitterId(?string $value): self
    {
        $this->instance->setSubmitterId($value);
        return $this;
    }

    /**
     * Sets terminal Id field.
     *
     * @param string|null $value
     */
    public function terminalId(?string $value): self
    {
        $this->instance->setTerminalId($value);
        return $this;
    }

    /**
     * Initializes a new Valuelink Info object.
     */
    public function build(): ValuelinkInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
