<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\WeChatPayPosInfo;
use Core\Utils\CoreHelper;

/**
 * Builder for model WeChatPayPosInfo
 *
 * @see WeChatPayPosInfo
 */
class WeChatPayPosInfoBuilder
{
    /**
     * @var WeChatPayPosInfo
     */
    private $instance;

    private function __construct(WeChatPayPosInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new We Chat Pay Pos Info Builder object.
     *
     * @param string $contactPersonName
     * @param string $email
     */
    public static function init(string $contactPersonName, string $email): self
    {
        return new self(new WeChatPayPosInfo($contactPersonName, $email));
    }

    /**
     * Initializes a new We Chat Pay Pos Info object.
     */
    public function build(): WeChatPayPosInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
