<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models\Builders;

use AdyenApIsLib\Models\WeChatPayInfo;
use Core\Utils\CoreHelper;

/**
 * Builder for model WeChatPayInfo
 *
 * @see WeChatPayInfo
 */
class WeChatPayInfoBuilder
{
    /**
     * @var WeChatPayInfo
     */
    private $instance;

    private function __construct(WeChatPayInfo $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new We Chat Pay Info Builder object.
     *
     * @param string $contactPersonName
     * @param string $email
     */
    public static function init(string $contactPersonName, string $email): self
    {
        return new self(new WeChatPayInfo($contactPersonName, $email));
    }

    /**
     * Initializes a new We Chat Pay Info object.
     */
    public function build(): WeChatPayInfo
    {
        return CoreHelper::clone($this->instance);
    }
}
