<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Exceptions;

use AdyenApIsLib\ApiHelper;

/**
 * Standardized error response following RFC-7807 format
 */
class DefaultErrorResponseEntityException extends ApiException
{
    /**
     * @var string|null
     */
    private $detail;

    /**
     * @var string|null
     */
    private $errorCode;

    /**
     * @var string|null
     */
    private $instance;

    /**
     * @var \AdyenApIsLib\Models\InvalidField[]|null
     */
    private $invalidFields;

    /**
     * @var string|null
     */
    private $requestId;

    /**
     * @var int|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $title;

    /**
     * @var string|null
     */
    private $type;

    /**
     * Returns Detail.
     * A human-readable explanation specific to this occurrence of the problem.
     */
    public function getDetail(): ?string
    {
        return $this->detail;
    }

    /**
     * Sets Detail.
     * A human-readable explanation specific to this occurrence of the problem.
     *
     * @maps detail
     */
    public function setDetail(?string $detail): void
    {
        $this->detail = $detail;
    }

    /**
     * Returns Error Code.
     * Unique business error code.
     */
    public function getErrorCode(): ?string
    {
        return $this->errorCode;
    }

    /**
     * Sets Error Code.
     * Unique business error code.
     *
     * @maps errorCode
     */
    public function setErrorCode(?string $errorCode): void
    {
        $this->errorCode = $errorCode;
    }

    /**
     * Returns Instance.
     * A URI that identifies the specific occurrence of the problem if applicable.
     */
    public function getInstance(): ?string
    {
        return $this->instance;
    }

    /**
     * Sets Instance.
     * A URI that identifies the specific occurrence of the problem if applicable.
     *
     * @maps instance
     */
    public function setInstance(?string $instance): void
    {
        $this->instance = $instance;
    }

    /**
     * Returns Invalid Fields.
     * Array of fields with validation errors when applicable.
     *
     * @return \AdyenApIsLib\Models\InvalidField[]|null
     */
    public function getInvalidFields(): ?array
    {
        return $this->invalidFields;
    }

    /**
     * Sets Invalid Fields.
     * Array of fields with validation errors when applicable.
     *
     * @maps invalidFields
     *
     * @param \AdyenApIsLib\Models\InvalidField[]|null $invalidFields
     */
    public function setInvalidFields(?array $invalidFields): void
    {
        $this->invalidFields = $invalidFields;
    }

    /**
     * Returns Request Id.
     * The unique reference for the request.
     */
    public function getRequestId(): ?string
    {
        return $this->requestId;
    }

    /**
     * Sets Request Id.
     * The unique reference for the request.
     *
     * @maps requestId
     */
    public function setRequestId(?string $requestId): void
    {
        $this->requestId = $requestId;
    }

    /**
     * Returns Status.
     * The HTTP status code.
     */
    public function getStatus(): ?int
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The HTTP status code.
     *
     * @maps status
     */
    public function setStatus(?int $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Title.
     * A short, human-readable summary of the problem type.
     */
    public function getTitle(): ?string
    {
        return $this->title;
    }

    /**
     * Sets Title.
     * A short, human-readable summary of the problem type.
     *
     * @maps title
     */
    public function setTitle(?string $title): void
    {
        $this->title = $title;
    }

    /**
     * Returns Type.
     * A URI that identifies the validation error type. It points to human-readable documentation for the
     * problem type.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * A URI that identifies the validation error type. It points to human-readable documentation for the
     * problem type.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the DefaultErrorResponseEntityException object to a human-readable string representation.
     *
     * @return string The string representation of the DefaultErrorResponseEntityException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'DefaultErrorResponseEntityException',
            [
                'detail' => $this->detail,
                'errorCode' => $this->errorCode,
                'instance' => $this->instance,
                'invalidFields' => $this->invalidFields,
                'requestId' => $this->requestId,
                'status' => $this->status,
                'title' => $this->title,
                'type' => $this->type,
                'additionalProperties' => $this->additionalProperties
            ],
            parent::__toString()
        );
    }

    protected $propertyNames = [
        'detail',
        'errorCode',
        'instance',
        'invalidFields',
        'requestId',
        'status',
        'title',
        'type'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }
}
