<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class AdditionalDataRatepay implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $ratepayInstallmentAmount;

    /**
     * @var string|null
     */
    private $ratepayInterestRate;

    /**
     * @var string|null
     */
    private $ratepayLastInstallmentAmount;

    /**
     * @var string|null
     */
    private $ratepayPaymentFirstday;

    /**
     * @var string|null
     */
    private $ratepaydataDeliveryDate;

    /**
     * @var string|null
     */
    private $ratepaydataDueDate;

    /**
     * @var string|null
     */
    private $ratepaydataInvoiceDate;

    /**
     * @var string|null
     */
    private $ratepaydataInvoiceId;

    /**
     * Returns Ratepay Installment Amount.
     * Amount the customer has to pay each month.
     */
    public function getRatepayInstallmentAmount(): ?string
    {
        return $this->ratepayInstallmentAmount;
    }

    /**
     * Sets Ratepay Installment Amount.
     * Amount the customer has to pay each month.
     *
     * @maps ratepay.installmentAmount
     */
    public function setRatepayInstallmentAmount(?string $ratepayInstallmentAmount): void
    {
        $this->ratepayInstallmentAmount = $ratepayInstallmentAmount;
    }

    /**
     * Returns Ratepay Interest Rate.
     * Interest rate of this installment.
     */
    public function getRatepayInterestRate(): ?string
    {
        return $this->ratepayInterestRate;
    }

    /**
     * Sets Ratepay Interest Rate.
     * Interest rate of this installment.
     *
     * @maps ratepay.interestRate
     */
    public function setRatepayInterestRate(?string $ratepayInterestRate): void
    {
        $this->ratepayInterestRate = $ratepayInterestRate;
    }

    /**
     * Returns Ratepay Last Installment Amount.
     * Amount of the last installment.
     */
    public function getRatepayLastInstallmentAmount(): ?string
    {
        return $this->ratepayLastInstallmentAmount;
    }

    /**
     * Sets Ratepay Last Installment Amount.
     * Amount of the last installment.
     *
     * @maps ratepay.lastInstallmentAmount
     */
    public function setRatepayLastInstallmentAmount(?string $ratepayLastInstallmentAmount): void
    {
        $this->ratepayLastInstallmentAmount = $ratepayLastInstallmentAmount;
    }

    /**
     * Returns Ratepay Payment Firstday.
     * Calendar day of the first payment.
     */
    public function getRatepayPaymentFirstday(): ?string
    {
        return $this->ratepayPaymentFirstday;
    }

    /**
     * Sets Ratepay Payment Firstday.
     * Calendar day of the first payment.
     *
     * @maps ratepay.paymentFirstday
     */
    public function setRatepayPaymentFirstday(?string $ratepayPaymentFirstday): void
    {
        $this->ratepayPaymentFirstday = $ratepayPaymentFirstday;
    }

    /**
     * Returns Ratepaydata Delivery Date.
     * Date the merchant delivered the goods to the customer.
     */
    public function getRatepaydataDeliveryDate(): ?string
    {
        return $this->ratepaydataDeliveryDate;
    }

    /**
     * Sets Ratepaydata Delivery Date.
     * Date the merchant delivered the goods to the customer.
     *
     * @maps ratepaydata.deliveryDate
     */
    public function setRatepaydataDeliveryDate(?string $ratepaydataDeliveryDate): void
    {
        $this->ratepaydataDeliveryDate = $ratepaydataDeliveryDate;
    }

    /**
     * Returns Ratepaydata Due Date.
     * Date by which the customer must settle the payment.
     */
    public function getRatepaydataDueDate(): ?string
    {
        return $this->ratepaydataDueDate;
    }

    /**
     * Sets Ratepaydata Due Date.
     * Date by which the customer must settle the payment.
     *
     * @maps ratepaydata.dueDate
     */
    public function setRatepaydataDueDate(?string $ratepaydataDueDate): void
    {
        $this->ratepaydataDueDate = $ratepaydataDueDate;
    }

    /**
     * Returns Ratepaydata Invoice Date.
     * Invoice date, defined by the merchant. If not included, the invoice date is set to the delivery date.
     */
    public function getRatepaydataInvoiceDate(): ?string
    {
        return $this->ratepaydataInvoiceDate;
    }

    /**
     * Sets Ratepaydata Invoice Date.
     * Invoice date, defined by the merchant. If not included, the invoice date is set to the delivery date.
     *
     * @maps ratepaydata.invoiceDate
     */
    public function setRatepaydataInvoiceDate(?string $ratepaydataInvoiceDate): void
    {
        $this->ratepaydataInvoiceDate = $ratepaydataInvoiceDate;
    }

    /**
     * Returns Ratepaydata Invoice Id.
     * Identification name or number for the invoice, defined by the merchant.
     */
    public function getRatepaydataInvoiceId(): ?string
    {
        return $this->ratepaydataInvoiceId;
    }

    /**
     * Sets Ratepaydata Invoice Id.
     * Identification name or number for the invoice, defined by the merchant.
     *
     * @maps ratepaydata.invoiceId
     */
    public function setRatepaydataInvoiceId(?string $ratepaydataInvoiceId): void
    {
        $this->ratepaydataInvoiceId = $ratepaydataInvoiceId;
    }

    /**
     * Converts the AdditionalDataRatepay object to a human-readable string representation.
     *
     * @return string The string representation of the AdditionalDataRatepay object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AdditionalDataRatepay',
            [
                'ratepayInstallmentAmount' => $this->ratepayInstallmentAmount,
                'ratepayInterestRate' => $this->ratepayInterestRate,
                'ratepayLastInstallmentAmount' => $this->ratepayLastInstallmentAmount,
                'ratepayPaymentFirstday' => $this->ratepayPaymentFirstday,
                'ratepaydataDeliveryDate' => $this->ratepaydataDeliveryDate,
                'ratepaydataDueDate' => $this->ratepaydataDueDate,
                'ratepaydataInvoiceDate' => $this->ratepaydataInvoiceDate,
                'ratepaydataInvoiceId' => $this->ratepaydataInvoiceId
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->ratepayInstallmentAmount)) {
            $json['ratepay.installmentAmount']     = $this->ratepayInstallmentAmount;
        }
        if (isset($this->ratepayInterestRate)) {
            $json['ratepay.interestRate']          = $this->ratepayInterestRate;
        }
        if (isset($this->ratepayLastInstallmentAmount)) {
            $json['ratepay.lastInstallmentAmount'] = $this->ratepayLastInstallmentAmount;
        }
        if (isset($this->ratepayPaymentFirstday)) {
            $json['ratepay.paymentFirstday']       = $this->ratepayPaymentFirstday;
        }
        if (isset($this->ratepaydataDeliveryDate)) {
            $json['ratepaydata.deliveryDate']      = $this->ratepaydataDeliveryDate;
        }
        if (isset($this->ratepaydataDueDate)) {
            $json['ratepaydata.dueDate']           = $this->ratepaydataDueDate;
        }
        if (isset($this->ratepaydataInvoiceDate)) {
            $json['ratepaydata.invoiceDate']       = $this->ratepaydataInvoiceDate;
        }
        if (isset($this->ratepaydataInvoiceId)) {
            $json['ratepaydata.invoiceId']         = $this->ratepaydataInvoiceId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
