<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class AdditionalDataAirline implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $airlineAgencyInvoiceNumber;

    /**
     * @var string|null
     */
    private $airlineAgencyPlanName;

    /**
     * @var string|null
     */
    private $airlineAirlineCode;

    /**
     * @var string|null
     */
    private $airlineAirlineDesignatorCode;

    /**
     * @var string|null
     */
    private $airlineBoardingFee;

    /**
     * @var string|null
     */
    private $airlineComputerizedReservationSystem;

    /**
     * @var string|null
     */
    private $airlineCustomerReferenceNumber;

    /**
     * @var string|null
     */
    private $airlineDocumentType;

    /**
     * @var string|null
     */
    private $airlineFlightDate;

    /**
     * @var string|null
     */
    private $airlineIssueDate;

    /**
     * @var string|null
     */
    private $airlineLegCarrierCode;

    /**
     * @var string|null
     */
    private $airlineLegClassOfTravel;

    /**
     * @var string|null
     */
    private $airlineLegDateOfTravel;

    /**
     * @var string|null
     */
    private $airlineLegDepartAirport;

    /**
     * @var string|null
     */
    private $airlineLegDepartTax;

    /**
     * @var string|null
     */
    private $airlineLegDestinationCode;

    /**
     * @var string|null
     */
    private $airlineLegFareBaseCode;

    /**
     * @var string|null
     */
    private $airlineLegFlightNumber;

    /**
     * @var string|null
     */
    private $airlineLegStopOverCode;

    /**
     * @var string|null
     */
    private $airlinePassengerDateOfBirth;

    /**
     * @var string|null
     */
    private $airlinePassengerFirstName;

    /**
     * @var string|null
     */
    private $airlinePassengerLastName;

    /**
     * @var string|null
     */
    private $airlinePassengerPhoneNumber;

    /**
     * @var string|null
     */
    private $airlinePassengerTravellerType;

    /**
     * @var string
     */
    private $airlinePassengerName;

    /**
     * @var string|null
     */
    private $airlineTicketIssueAddress;

    /**
     * @var string|null
     */
    private $airlineTicketNumber;

    /**
     * @var string|null
     */
    private $airlineTravelAgencyCode;

    /**
     * @var string|null
     */
    private $airlineTravelAgencyName;

    /**
     * @param string $airlinePassengerName
     */
    public function __construct(string $airlinePassengerName)
    {
        $this->airlinePassengerName = $airlinePassengerName;
    }

    /**
     * Returns Airline Agency Invoice Number.
     * The reference number for the invoice, issued by the agency.
     * * Encoding: ASCII
     * * minLength: 1 character
     * * maxLength: 6 characters
     */
    public function getAirlineAgencyInvoiceNumber(): ?string
    {
        return $this->airlineAgencyInvoiceNumber;
    }

    /**
     * Sets Airline Agency Invoice Number.
     * The reference number for the invoice, issued by the agency.
     * * Encoding: ASCII
     * * minLength: 1 character
     * * maxLength: 6 characters
     *
     * @maps airline.agency_invoice_number
     */
    public function setAirlineAgencyInvoiceNumber(?string $airlineAgencyInvoiceNumber): void
    {
        $this->airlineAgencyInvoiceNumber = $airlineAgencyInvoiceNumber;
    }

    /**
     * Returns Airline Agency Plan Name.
     * The two-letter agency plan identifier.
     * * Encoding: ASCII
     * * minLength: 2 characters
     * * maxLength: 2 characters
     */
    public function getAirlineAgencyPlanName(): ?string
    {
        return $this->airlineAgencyPlanName;
    }

    /**
     * Sets Airline Agency Plan Name.
     * The two-letter agency plan identifier.
     * * Encoding: ASCII
     * * minLength: 2 characters
     * * maxLength: 2 characters
     *
     * @maps airline.agency_plan_name
     */
    public function setAirlineAgencyPlanName(?string $airlineAgencyPlanName): void
    {
        $this->airlineAgencyPlanName = $airlineAgencyPlanName;
    }

    /**
     * Returns Airline Airline Code.
     * The [IATA](https://www.iata.org/services/pages/codes.aspx) 3-digit accounting code (PAX) that
     * identifies the carrier.
     * * Format: IATA 3-digit accounting code (PAX)
     * * Example: KLM = 074
     * * minLength: 3 characters
     * * maxLength: 3 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     */
    public function getAirlineAirlineCode(): ?string
    {
        return $this->airlineAirlineCode;
    }

    /**
     * Sets Airline Airline Code.
     * The [IATA](https://www.iata.org/services/pages/codes.aspx) 3-digit accounting code (PAX) that
     * identifies the carrier.
     * * Format: IATA 3-digit accounting code (PAX)
     * * Example: KLM = 074
     * * minLength: 3 characters
     * * maxLength: 3 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     *
     * @maps airline.airline_code
     */
    public function setAirlineAirlineCode(?string $airlineAirlineCode): void
    {
        $this->airlineAirlineCode = $airlineAirlineCode;
    }

    /**
     * Returns Airline Airline Designator Code.
     * The [IATA](https://www.iata.org/services/pages/codes.aspx) 2-letter accounting code (PAX) that
     * identifies the carrier.
     * * Encoding: ASCII
     * * Example: KLM = KL
     * * minLength: 2 characters
     * * maxLength: 2 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     */
    public function getAirlineAirlineDesignatorCode(): ?string
    {
        return $this->airlineAirlineDesignatorCode;
    }

    /**
     * Sets Airline Airline Designator Code.
     * The [IATA](https://www.iata.org/services/pages/codes.aspx) 2-letter accounting code (PAX) that
     * identifies the carrier.
     * * Encoding: ASCII
     * * Example: KLM = KL
     * * minLength: 2 characters
     * * maxLength: 2 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     *
     * @maps airline.airline_designator_code
     */
    public function setAirlineAirlineDesignatorCode(?string $airlineAirlineDesignatorCode): void
    {
        $this->airlineAirlineDesignatorCode = $airlineAirlineDesignatorCode;
    }

    /**
     * Returns Airline Boarding Fee.
     * The amount charged for boarding the plane, in [minor units](https://docs.adyen.com/development-
     * resources/currency-codes).
     * * Encoding: Numeric
     * * minLength: 1 character
     * * maxLength: 18 characters
     */
    public function getAirlineBoardingFee(): ?string
    {
        return $this->airlineBoardingFee;
    }

    /**
     * Sets Airline Boarding Fee.
     * The amount charged for boarding the plane, in [minor units](https://docs.adyen.com/development-
     * resources/currency-codes).
     * * Encoding: Numeric
     * * minLength: 1 character
     * * maxLength: 18 characters
     *
     * @maps airline.boarding_fee
     */
    public function setAirlineBoardingFee(?string $airlineBoardingFee): void
    {
        $this->airlineBoardingFee = $airlineBoardingFee;
    }

    /**
     * Returns Airline Computerized Reservation System.
     * The [CRS](https://en.wikipedia.org/wiki/Computer_reservation_system) used to make the reservation
     * and purchase the ticket.
     * * Encoding: ASCII
     * * minLength: 4 characters
     * * maxLength: 4 characters
     */
    public function getAirlineComputerizedReservationSystem(): ?string
    {
        return $this->airlineComputerizedReservationSystem;
    }

    /**
     * Sets Airline Computerized Reservation System.
     * The [CRS](https://en.wikipedia.org/wiki/Computer_reservation_system) used to make the reservation
     * and purchase the ticket.
     * * Encoding: ASCII
     * * minLength: 4 characters
     * * maxLength: 4 characters
     *
     * @maps airline.computerized_reservation_system
     */
    public function setAirlineComputerizedReservationSystem(?string $airlineComputerizedReservationSystem): void
    {
        $this->airlineComputerizedReservationSystem = $airlineComputerizedReservationSystem;
    }

    /**
     * Returns Airline Customer Reference Number.
     * The alphanumeric customer reference number.
     * * Encoding: ASCII
     * * maxLength: 20 characters
     * * If you send more than 20 characters, the customer reference number is truncated
     * * Must not be all spaces
     */
    public function getAirlineCustomerReferenceNumber(): ?string
    {
        return $this->airlineCustomerReferenceNumber;
    }

    /**
     * Sets Airline Customer Reference Number.
     * The alphanumeric customer reference number.
     * * Encoding: ASCII
     * * maxLength: 20 characters
     * * If you send more than 20 characters, the customer reference number is truncated
     * * Must not be all spaces
     *
     * @maps airline.customer_reference_number
     */
    public function setAirlineCustomerReferenceNumber(?string $airlineCustomerReferenceNumber): void
    {
        $this->airlineCustomerReferenceNumber = $airlineCustomerReferenceNumber;
    }

    /**
     * Returns Airline Document Type.
     * A code that identifies the type of item bought. The description of the code can appear on credit
     * card statements.
     * * Encoding: ASCII
     * * Example: Passenger ticket = 01
     * * minLength: 2 characters
     * * maxLength: 2 characters
     */
    public function getAirlineDocumentType(): ?string
    {
        return $this->airlineDocumentType;
    }

    /**
     * Sets Airline Document Type.
     * A code that identifies the type of item bought. The description of the code can appear on credit
     * card statements.
     * * Encoding: ASCII
     * * Example: Passenger ticket = 01
     * * minLength: 2 characters
     * * maxLength: 2 characters
     *
     * @maps airline.document_type
     */
    public function setAirlineDocumentType(?string $airlineDocumentType): void
    {
        $this->airlineDocumentType = $airlineDocumentType;
    }

    /**
     * Returns Airline Flight Date.
     * The flight departure date. Local time `(HH:mm)` is optional.
     * * Date format: `yyyy-MM-dd`
     * * Date and time format: `yyyy-MM-dd HH:mm`
     * * minLength: 10 characters
     * * maxLength: 16 characters
     */
    public function getAirlineFlightDate(): ?string
    {
        return $this->airlineFlightDate;
    }

    /**
     * Sets Airline Flight Date.
     * The flight departure date. Local time `(HH:mm)` is optional.
     * * Date format: `yyyy-MM-dd`
     * * Date and time format: `yyyy-MM-dd HH:mm`
     * * minLength: 10 characters
     * * maxLength: 16 characters
     *
     * @maps airline.flight_date
     */
    public function setAirlineFlightDate(?string $airlineFlightDate): void
    {
        $this->airlineFlightDate = $airlineFlightDate;
    }

    /**
     * Returns Airline Issue Date.
     * The date that the ticket was issued to the passenger.
     * * minLength: 6 characters
     * * maxLength: 6 characters
     * * Date format: YYMMDD
     */
    public function getAirlineIssueDate(): ?string
    {
        return $this->airlineIssueDate;
    }

    /**
     * Sets Airline Issue Date.
     * The date that the ticket was issued to the passenger.
     * * minLength: 6 characters
     * * maxLength: 6 characters
     * * Date format: YYMMDD
     *
     * @maps airline.issue_date
     */
    public function setAirlineIssueDate(?string $airlineIssueDate): void
    {
        $this->airlineIssueDate = $airlineIssueDate;
    }

    /**
     * Returns Airline Leg Carrier Code.
     * The [IATA](https://www.iata.org/services/pages/codes.aspx) 2-letter accounting code (PAX) that
     * identifies the carrier.
     * This field is required if the airline data includes leg details.
     * * Example: KLM = KL
     * * minLength: 2 characters
     * * maxLength: 2 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     */
    public function getAirlineLegCarrierCode(): ?string
    {
        return $this->airlineLegCarrierCode;
    }

    /**
     * Sets Airline Leg Carrier Code.
     * The [IATA](https://www.iata.org/services/pages/codes.aspx) 2-letter accounting code (PAX) that
     * identifies the carrier.
     * This field is required if the airline data includes leg details.
     * * Example: KLM = KL
     * * minLength: 2 characters
     * * maxLength: 2 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     *
     * @maps airline.leg.carrier_code
     */
    public function setAirlineLegCarrierCode(?string $airlineLegCarrierCode): void
    {
        $this->airlineLegCarrierCode = $airlineLegCarrierCode;
    }

    /**
     * Returns Airline Leg Class of Travel.
     * A one-letter travel class identifier.
     * The following are common:
     * * F: first class
     * * J: business class
     * * Y: economy class
     * * W: premium economy
     *
     * * Encoding: ASCII
     * * minLength: 1 character
     * * maxLength: 1 character
     * * Must not be all spaces
     * * Must not be all zeros.
     */
    public function getAirlineLegClassOfTravel(): ?string
    {
        return $this->airlineLegClassOfTravel;
    }

    /**
     * Sets Airline Leg Class of Travel.
     * A one-letter travel class identifier.
     * The following are common:
     * * F: first class
     * * J: business class
     * * Y: economy class
     * * W: premium economy
     *
     * * Encoding: ASCII
     * * minLength: 1 character
     * * maxLength: 1 character
     * * Must not be all spaces
     * * Must not be all zeros.
     *
     * @maps airline.leg.class_of_travel
     */
    public function setAirlineLegClassOfTravel(?string $airlineLegClassOfTravel): void
    {
        $this->airlineLegClassOfTravel = $airlineLegClassOfTravel;
    }

    /**
     * Returns Airline Leg Date of Travel.
     * Date and time of travel in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format `yyyy-MM-dd HH:
     * mm`.
     * * Encoding: ASCII
     * * minLength: 16 characters
     * * maxLength: 16 characters
     */
    public function getAirlineLegDateOfTravel(): ?string
    {
        return $this->airlineLegDateOfTravel;
    }

    /**
     * Sets Airline Leg Date of Travel.
     * Date and time of travel in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format `yyyy-MM-dd HH:
     * mm`.
     * * Encoding: ASCII
     * * minLength: 16 characters
     * * maxLength: 16 characters
     *
     * @maps airline.leg.date_of_travel
     */
    public function setAirlineLegDateOfTravel(?string $airlineLegDateOfTravel): void
    {
        $this->airlineLegDateOfTravel = $airlineLegDateOfTravel;
    }

    /**
     * Returns Airline Leg Depart Airport.
     * The [IATA](https://www.iata.org/services/pages/codes.aspx) three-letter airport code of the
     * departure airport.
     * This field is required if the airline data includes leg details.
     *
     * * Encoding: ASCII
     * * Example: Amsterdam = AMS
     * * minLength: 3 characters
     * * maxLength: 3 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     */
    public function getAirlineLegDepartAirport(): ?string
    {
        return $this->airlineLegDepartAirport;
    }

    /**
     * Sets Airline Leg Depart Airport.
     * The [IATA](https://www.iata.org/services/pages/codes.aspx) three-letter airport code of the
     * departure airport.
     * This field is required if the airline data includes leg details.
     *
     * * Encoding: ASCII
     * * Example: Amsterdam = AMS
     * * minLength: 3 characters
     * * maxLength: 3 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     *
     * @maps airline.leg.depart_airport
     */
    public function setAirlineLegDepartAirport(?string $airlineLegDepartAirport): void
    {
        $this->airlineLegDepartAirport = $airlineLegDepartAirport;
    }

    /**
     * Returns Airline Leg Depart Tax.
     * The amount of [departure tax](https://en.wikipedia.org/wiki/Departure_tax) charged, in [minor
     * units](https://docs.adyen.com/development-resources/currency-codes).
     * * Encoding: Numeric
     * * minLength: 1
     * * maxLength: 12
     * * Must not be all zeros.
     */
    public function getAirlineLegDepartTax(): ?string
    {
        return $this->airlineLegDepartTax;
    }

    /**
     * Sets Airline Leg Depart Tax.
     * The amount of [departure tax](https://en.wikipedia.org/wiki/Departure_tax) charged, in [minor
     * units](https://docs.adyen.com/development-resources/currency-codes).
     * * Encoding: Numeric
     * * minLength: 1
     * * maxLength: 12
     * * Must not be all zeros.
     *
     * @maps airline.leg.depart_tax
     */
    public function setAirlineLegDepartTax(?string $airlineLegDepartTax): void
    {
        $this->airlineLegDepartTax = $airlineLegDepartTax;
    }

    /**
     * Returns Airline Leg Destination Code.
     * The [IATA](https://www.iata.org/services/pages/codes.aspx) 3-letter airport code of the destination
     * airport.
     * This field is required if the airline data includes leg details.
     * * Example: Amsterdam = AMS
     * * Encoding: ASCII
     * * minLength: 3 characters
     * * maxLength: 3 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     */
    public function getAirlineLegDestinationCode(): ?string
    {
        return $this->airlineLegDestinationCode;
    }

    /**
     * Sets Airline Leg Destination Code.
     * The [IATA](https://www.iata.org/services/pages/codes.aspx) 3-letter airport code of the destination
     * airport.
     * This field is required if the airline data includes leg details.
     * * Example: Amsterdam = AMS
     * * Encoding: ASCII
     * * minLength: 3 characters
     * * maxLength: 3 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     *
     * @maps airline.leg.destination_code
     */
    public function setAirlineLegDestinationCode(?string $airlineLegDestinationCode): void
    {
        $this->airlineLegDestinationCode = $airlineLegDestinationCode;
    }

    /**
     * Returns Airline Leg Fare Base Code.
     * The [fare basis code](https://en.wikipedia.org/wiki/Fare_basis_code), alphanumeric.
     * * minLength: 1 character
     * * maxLength: 15 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     */
    public function getAirlineLegFareBaseCode(): ?string
    {
        return $this->airlineLegFareBaseCode;
    }

    /**
     * Sets Airline Leg Fare Base Code.
     * The [fare basis code](https://en.wikipedia.org/wiki/Fare_basis_code), alphanumeric.
     * * minLength: 1 character
     * * maxLength: 15 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     *
     * @maps airline.leg.fare_base_code
     */
    public function setAirlineLegFareBaseCode(?string $airlineLegFareBaseCode): void
    {
        $this->airlineLegFareBaseCode = $airlineLegFareBaseCode;
    }

    /**
     * Returns Airline Leg Flight Number.
     * The flight identifier.
     * * minLength: 1 character
     * * maxLength: 5 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     */
    public function getAirlineLegFlightNumber(): ?string
    {
        return $this->airlineLegFlightNumber;
    }

    /**
     * Sets Airline Leg Flight Number.
     * The flight identifier.
     * * minLength: 1 character
     * * maxLength: 5 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     *
     * @maps airline.leg.flight_number
     */
    public function setAirlineLegFlightNumber(?string $airlineLegFlightNumber): void
    {
        $this->airlineLegFlightNumber = $airlineLegFlightNumber;
    }

    /**
     * Returns Airline Leg Stop Over Code.
     * A one-letter code that indicates whether the passenger is entitled to make a stopover. Can be a
     * space, O if the passenger is entitled to make a stopover, or X if they are not.
     * * Encoding: ASCII
     * * minLength: 1 character
     * * maxLength: 1 character
     */
    public function getAirlineLegStopOverCode(): ?string
    {
        return $this->airlineLegStopOverCode;
    }

    /**
     * Sets Airline Leg Stop Over Code.
     * A one-letter code that indicates whether the passenger is entitled to make a stopover. Can be a
     * space, O if the passenger is entitled to make a stopover, or X if they are not.
     * * Encoding: ASCII
     * * minLength: 1 character
     * * maxLength: 1 character
     *
     * @maps airline.leg.stop_over_code
     */
    public function setAirlineLegStopOverCode(?string $airlineLegStopOverCode): void
    {
        $this->airlineLegStopOverCode = $airlineLegStopOverCode;
    }

    /**
     * Returns Airline Passenger Date of Birth.
     * The passenger's date of birth.
     *
     * Date format: `yyyy-MM-dd`
     * * minLength: 10
     * * maxLength: 10
     */
    public function getAirlinePassengerDateOfBirth(): ?string
    {
        return $this->airlinePassengerDateOfBirth;
    }

    /**
     * Sets Airline Passenger Date of Birth.
     * The passenger's date of birth.
     *
     * Date format: `yyyy-MM-dd`
     * * minLength: 10
     * * maxLength: 10
     *
     * @maps airline.passenger.date_of_birth
     */
    public function setAirlinePassengerDateOfBirth(?string $airlinePassengerDateOfBirth): void
    {
        $this->airlinePassengerDateOfBirth = $airlinePassengerDateOfBirth;
    }

    /**
     * Returns Airline Passenger First Name.
     * The passenger's first name.
     * > This field is required if the airline data includes passenger details or leg details.
     * * Encoding: ASCII
     */
    public function getAirlinePassengerFirstName(): ?string
    {
        return $this->airlinePassengerFirstName;
    }

    /**
     * Sets Airline Passenger First Name.
     * The passenger's first name.
     * > This field is required if the airline data includes passenger details or leg details.
     * * Encoding: ASCII
     *
     * @maps airline.passenger.first_name
     */
    public function setAirlinePassengerFirstName(?string $airlinePassengerFirstName): void
    {
        $this->airlinePassengerFirstName = $airlinePassengerFirstName;
    }

    /**
     * Returns Airline Passenger Last Name.
     * The passenger's last name.
     * > This field is required if the airline data includes passenger details or leg details.
     * * Encoding: ASCII
     */
    public function getAirlinePassengerLastName(): ?string
    {
        return $this->airlinePassengerLastName;
    }

    /**
     * Sets Airline Passenger Last Name.
     * The passenger's last name.
     * > This field is required if the airline data includes passenger details or leg details.
     * * Encoding: ASCII
     *
     * @maps airline.passenger.last_name
     */
    public function setAirlinePassengerLastName(?string $airlinePassengerLastName): void
    {
        $this->airlinePassengerLastName = $airlinePassengerLastName;
    }

    /**
     * Returns Airline Passenger Phone Number.
     * The passenger's phone number, including country code. This is an alphanumeric field that can include
     * the '+' and '-' signs.
     * * Encoding: ASCII
     * * minLength: 3 characters
     * * maxLength: 30 characters
     */
    public function getAirlinePassengerPhoneNumber(): ?string
    {
        return $this->airlinePassengerPhoneNumber;
    }

    /**
     * Sets Airline Passenger Phone Number.
     * The passenger's phone number, including country code. This is an alphanumeric field that can include
     * the '+' and '-' signs.
     * * Encoding: ASCII
     * * minLength: 3 characters
     * * maxLength: 30 characters
     *
     * @maps airline.passenger.phone_number
     */
    public function setAirlinePassengerPhoneNumber(?string $airlinePassengerPhoneNumber): void
    {
        $this->airlinePassengerPhoneNumber = $airlinePassengerPhoneNumber;
    }

    /**
     * Returns Airline Passenger Traveller Type.
     * The IATA passenger type code (PTC).
     * * Encoding: ASCII
     * * minLength: 3 characters
     * * maxLength: 6 characters
     */
    public function getAirlinePassengerTravellerType(): ?string
    {
        return $this->airlinePassengerTravellerType;
    }

    /**
     * Sets Airline Passenger Traveller Type.
     * The IATA passenger type code (PTC).
     * * Encoding: ASCII
     * * minLength: 3 characters
     * * maxLength: 6 characters
     *
     * @maps airline.passenger.traveller_type
     */
    public function setAirlinePassengerTravellerType(?string $airlinePassengerTravellerType): void
    {
        $this->airlinePassengerTravellerType = $airlinePassengerTravellerType;
    }

    /**
     * Returns Airline Passenger Name.
     * The passenger's name, initials, and title.
     * * Format: last name + first name or initials + title
     * * Example: *FLYER / MARY MS*
     * * minLength: 1 character
     * * maxLength: 20 characters
     * * If you send more than 20 characters, the name is truncated
     * * Must not be all spaces
     * * Must not be all zeros.
     */
    public function getAirlinePassengerName(): string
    {
        return $this->airlinePassengerName;
    }

    /**
     * Sets Airline Passenger Name.
     * The passenger's name, initials, and title.
     * * Format: last name + first name or initials + title
     * * Example: *FLYER / MARY MS*
     * * minLength: 1 character
     * * maxLength: 20 characters
     * * If you send more than 20 characters, the name is truncated
     * * Must not be all spaces
     * * Must not be all zeros.
     *
     * @required
     * @maps airline.passenger_name
     */
    public function setAirlinePassengerName(string $airlinePassengerName): void
    {
        $this->airlinePassengerName = $airlinePassengerName;
    }

    /**
     * Returns Airline Ticket Issue Address.
     * The address of the organization that issued the ticket.
     * * minLength: 0 characters
     * * maxLength: 16 characters
     */
    public function getAirlineTicketIssueAddress(): ?string
    {
        return $this->airlineTicketIssueAddress;
    }

    /**
     * Sets Airline Ticket Issue Address.
     * The address of the organization that issued the ticket.
     * * minLength: 0 characters
     * * maxLength: 16 characters
     *
     * @maps airline.ticket_issue_address
     */
    public function setAirlineTicketIssueAddress(?string $airlineTicketIssueAddress): void
    {
        $this->airlineTicketIssueAddress = $airlineTicketIssueAddress;
    }

    /**
     * Returns Airline Ticket Number.
     * The ticket's unique identifier.
     * * minLength: 1 character
     * * maxLength: 15 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     */
    public function getAirlineTicketNumber(): ?string
    {
        return $this->airlineTicketNumber;
    }

    /**
     * Sets Airline Ticket Number.
     * The ticket's unique identifier.
     * * minLength: 1 character
     * * maxLength: 15 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     *
     * @maps airline.ticket_number
     */
    public function setAirlineTicketNumber(?string $airlineTicketNumber): void
    {
        $this->airlineTicketNumber = $airlineTicketNumber;
    }

    /**
     * Returns Airline Travel Agency Code.
     * The unique identifier from IATA or ARC for the travel agency that issues the ticket.
     * * Encoding: ASCII
     * * minLength: 1 character
     * * maxLength: 8 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     */
    public function getAirlineTravelAgencyCode(): ?string
    {
        return $this->airlineTravelAgencyCode;
    }

    /**
     * Sets Airline Travel Agency Code.
     * The unique identifier from IATA or ARC for the travel agency that issues the ticket.
     * * Encoding: ASCII
     * * minLength: 1 character
     * * maxLength: 8 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     *
     * @maps airline.travel_agency_code
     */
    public function setAirlineTravelAgencyCode(?string $airlineTravelAgencyCode): void
    {
        $this->airlineTravelAgencyCode = $airlineTravelAgencyCode;
    }

    /**
     * Returns Airline Travel Agency Name.
     * The name of the travel agency.
     *
     * * Encoding: ASCII
     * * minLength: 1 character
     * * maxLength: 25 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     */
    public function getAirlineTravelAgencyName(): ?string
    {
        return $this->airlineTravelAgencyName;
    }

    /**
     * Sets Airline Travel Agency Name.
     * The name of the travel agency.
     *
     * * Encoding: ASCII
     * * minLength: 1 character
     * * maxLength: 25 characters
     * * Must not be all spaces
     * * Must not be all zeros.
     *
     * @maps airline.travel_agency_name
     */
    public function setAirlineTravelAgencyName(?string $airlineTravelAgencyName): void
    {
        $this->airlineTravelAgencyName = $airlineTravelAgencyName;
    }

    /**
     * Converts the AdditionalDataAirline object to a human-readable string representation.
     *
     * @return string The string representation of the AdditionalDataAirline object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AdditionalDataAirline',
            [
                'airlineAgencyInvoiceNumber' => $this->airlineAgencyInvoiceNumber,
                'airlineAgencyPlanName' => $this->airlineAgencyPlanName,
                'airlineAirlineCode' => $this->airlineAirlineCode,
                'airlineAirlineDesignatorCode' => $this->airlineAirlineDesignatorCode,
                'airlineBoardingFee' => $this->airlineBoardingFee,
                'airlineComputerizedReservationSystem' => $this->airlineComputerizedReservationSystem,
                'airlineCustomerReferenceNumber' => $this->airlineCustomerReferenceNumber,
                'airlineDocumentType' => $this->airlineDocumentType,
                'airlineFlightDate' => $this->airlineFlightDate,
                'airlineIssueDate' => $this->airlineIssueDate,
                'airlineLegCarrierCode' => $this->airlineLegCarrierCode,
                'airlineLegClassOfTravel' => $this->airlineLegClassOfTravel,
                'airlineLegDateOfTravel' => $this->airlineLegDateOfTravel,
                'airlineLegDepartAirport' => $this->airlineLegDepartAirport,
                'airlineLegDepartTax' => $this->airlineLegDepartTax,
                'airlineLegDestinationCode' => $this->airlineLegDestinationCode,
                'airlineLegFareBaseCode' => $this->airlineLegFareBaseCode,
                'airlineLegFlightNumber' => $this->airlineLegFlightNumber,
                'airlineLegStopOverCode' => $this->airlineLegStopOverCode,
                'airlinePassengerDateOfBirth' => $this->airlinePassengerDateOfBirth,
                'airlinePassengerFirstName' => $this->airlinePassengerFirstName,
                'airlinePassengerLastName' => $this->airlinePassengerLastName,
                'airlinePassengerPhoneNumber' => $this->airlinePassengerPhoneNumber,
                'airlinePassengerTravellerType' => $this->airlinePassengerTravellerType,
                'airlinePassengerName' => $this->airlinePassengerName,
                'airlineTicketIssueAddress' => $this->airlineTicketIssueAddress,
                'airlineTicketNumber' => $this->airlineTicketNumber,
                'airlineTravelAgencyCode' => $this->airlineTravelAgencyCode,
                'airlineTravelAgencyName' => $this->airlineTravelAgencyName
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->airlineAgencyInvoiceNumber)) {
            $json['airline.agency_invoice_number']           = $this->airlineAgencyInvoiceNumber;
        }
        if (isset($this->airlineAgencyPlanName)) {
            $json['airline.agency_plan_name']                = $this->airlineAgencyPlanName;
        }
        if (isset($this->airlineAirlineCode)) {
            $json['airline.airline_code']                    = $this->airlineAirlineCode;
        }
        if (isset($this->airlineAirlineDesignatorCode)) {
            $json['airline.airline_designator_code']         = $this->airlineAirlineDesignatorCode;
        }
        if (isset($this->airlineBoardingFee)) {
            $json['airline.boarding_fee']                    = $this->airlineBoardingFee;
        }
        if (isset($this->airlineComputerizedReservationSystem)) {
            $json['airline.computerized_reservation_system'] = $this->airlineComputerizedReservationSystem;
        }
        if (isset($this->airlineCustomerReferenceNumber)) {
            $json['airline.customer_reference_number']       = $this->airlineCustomerReferenceNumber;
        }
        if (isset($this->airlineDocumentType)) {
            $json['airline.document_type']                   = $this->airlineDocumentType;
        }
        if (isset($this->airlineFlightDate)) {
            $json['airline.flight_date']                     = $this->airlineFlightDate;
        }
        if (isset($this->airlineIssueDate)) {
            $json['airline.issue_date']                      = $this->airlineIssueDate;
        }
        if (isset($this->airlineLegCarrierCode)) {
            $json['airline.leg.carrier_code']                = $this->airlineLegCarrierCode;
        }
        if (isset($this->airlineLegClassOfTravel)) {
            $json['airline.leg.class_of_travel']             = $this->airlineLegClassOfTravel;
        }
        if (isset($this->airlineLegDateOfTravel)) {
            $json['airline.leg.date_of_travel']              = $this->airlineLegDateOfTravel;
        }
        if (isset($this->airlineLegDepartAirport)) {
            $json['airline.leg.depart_airport']              = $this->airlineLegDepartAirport;
        }
        if (isset($this->airlineLegDepartTax)) {
            $json['airline.leg.depart_tax']                  = $this->airlineLegDepartTax;
        }
        if (isset($this->airlineLegDestinationCode)) {
            $json['airline.leg.destination_code']            = $this->airlineLegDestinationCode;
        }
        if (isset($this->airlineLegFareBaseCode)) {
            $json['airline.leg.fare_base_code']              = $this->airlineLegFareBaseCode;
        }
        if (isset($this->airlineLegFlightNumber)) {
            $json['airline.leg.flight_number']               = $this->airlineLegFlightNumber;
        }
        if (isset($this->airlineLegStopOverCode)) {
            $json['airline.leg.stop_over_code']              = $this->airlineLegStopOverCode;
        }
        if (isset($this->airlinePassengerDateOfBirth)) {
            $json['airline.passenger.date_of_birth']         = $this->airlinePassengerDateOfBirth;
        }
        if (isset($this->airlinePassengerFirstName)) {
            $json['airline.passenger.first_name']            = $this->airlinePassengerFirstName;
        }
        if (isset($this->airlinePassengerLastName)) {
            $json['airline.passenger.last_name']             = $this->airlinePassengerLastName;
        }
        if (isset($this->airlinePassengerPhoneNumber)) {
            $json['airline.passenger.phone_number']          = $this->airlinePassengerPhoneNumber;
        }
        if (isset($this->airlinePassengerTravellerType)) {
            $json['airline.passenger.traveller_type']        = $this->airlinePassengerTravellerType;
        }
        $json['airline.passenger_name']                      = $this->airlinePassengerName;
        if (isset($this->airlineTicketIssueAddress)) {
            $json['airline.ticket_issue_address']            = $this->airlineTicketIssueAddress;
        }
        if (isset($this->airlineTicketNumber)) {
            $json['airline.ticket_number']                   = $this->airlineTicketNumber;
        }
        if (isset($this->airlineTravelAgencyCode)) {
            $json['airline.travel_agency_code']              = $this->airlineTravelAgencyCode;
        }
        if (isset($this->airlineTravelAgencyName)) {
            $json['airline.travel_agency_name']              = $this->airlineTravelAgencyName;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
