<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class AdditionalDataOpi implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $opiIncludeTransToken;

    /**
     * Returns Opi Include Trans Token.
     * Optional boolean indicator. Set to **true** if you want an ecommerce transaction to return an `opi.
     * transToken` as additional data in the response.
     *
     * You can store this Oracle Payment Interface token in your Oracle Opera database. For more
     * information and required settings, see [Oracle Opera](https://docs.adyen.com/plugins/oracle-
     * opera#opi-token-ecommerce).
     */
    public function getOpiIncludeTransToken(): ?string
    {
        return $this->opiIncludeTransToken;
    }

    /**
     * Sets Opi Include Trans Token.
     * Optional boolean indicator. Set to **true** if you want an ecommerce transaction to return an `opi.
     * transToken` as additional data in the response.
     *
     * You can store this Oracle Payment Interface token in your Oracle Opera database. For more
     * information and required settings, see [Oracle Opera](https://docs.adyen.com/plugins/oracle-
     * opera#opi-token-ecommerce).
     *
     * @maps opi.includeTransToken
     */
    public function setOpiIncludeTransToken(?string $opiIncludeTransToken): void
    {
        $this->opiIncludeTransToken = $opiIncludeTransToken;
    }

    /**
     * Converts the AdditionalDataOpi object to a human-readable string representation.
     *
     * @return string The string representation of the AdditionalDataOpi object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('AdditionalDataOpi', ['opiIncludeTransToken' => $this->opiIncludeTransToken]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->opiIncludeTransToken)) {
            $json['opi.includeTransToken'] = $this->opiIncludeTransToken;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
