<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class AdditionalCommission implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $balanceAccountId;

    /**
     * @var int|null
     */
    private $fixedAmount;

    /**
     * @var int|null
     */
    private $variablePercentage;

    /**
     * Returns Balance Account Id.
     * Unique identifier of the balance account to which the additional commission is booked.
     */
    public function getBalanceAccountId(): ?string
    {
        return $this->balanceAccountId;
    }

    /**
     * Sets Balance Account Id.
     * Unique identifier of the balance account to which the additional commission is booked.
     *
     * @maps balanceAccountId
     */
    public function setBalanceAccountId(?string $balanceAccountId): void
    {
        $this->balanceAccountId = $balanceAccountId;
    }

    /**
     * Returns Fixed Amount.
     * A fixed commission fee, in minor units.
     */
    public function getFixedAmount(): ?int
    {
        return $this->fixedAmount;
    }

    /**
     * Sets Fixed Amount.
     * A fixed commission fee, in minor units.
     *
     * @maps fixedAmount
     */
    public function setFixedAmount(?int $fixedAmount): void
    {
        $this->fixedAmount = $fixedAmount;
    }

    /**
     * Returns Variable Percentage.
     * A variable commission fee, in basis points.
     */
    public function getVariablePercentage(): ?int
    {
        return $this->variablePercentage;
    }

    /**
     * Sets Variable Percentage.
     * A variable commission fee, in basis points.
     *
     * @maps variablePercentage
     */
    public function setVariablePercentage(?int $variablePercentage): void
    {
        $this->variablePercentage = $variablePercentage;
    }

    /**
     * Converts the AdditionalCommission object to a human-readable string representation.
     *
     * @return string The string representation of the AdditionalCommission object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AdditionalCommission',
            [
                'balanceAccountId' => $this->balanceAccountId,
                'fixedAmount' => $this->fixedAmount,
                'variablePercentage' => $this->variablePercentage
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->balanceAccountId)) {
            $json['balanceAccountId']   = $this->balanceAccountId;
        }
        if (isset($this->fixedAmount)) {
            $json['fixedAmount']        = $this->fixedAmount;
        }
        if (isset($this->variablePercentage)) {
            $json['variablePercentage'] = $this->variablePercentage;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
