<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class AfterpayTouchInfo implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $supportEmail;

    /**
     * @var string
     */
    private $supportUrl;

    /**
     * @param string $supportUrl
     */
    public function __construct(string $supportUrl)
    {
        $this->supportUrl = $supportUrl;
    }

    /**
     * Returns Support Email.
     * Support Email
     */
    public function getSupportEmail(): ?string
    {
        return $this->supportEmail;
    }

    /**
     * Sets Support Email.
     * Support Email
     *
     * @maps supportEmail
     */
    public function setSupportEmail(?string $supportEmail): void
    {
        $this->supportEmail = $supportEmail;
    }

    /**
     * Returns Support Url.
     * Support Url
     */
    public function getSupportUrl(): string
    {
        return $this->supportUrl;
    }

    /**
     * Sets Support Url.
     * Support Url
     *
     * @required
     * @maps supportUrl
     */
    public function setSupportUrl(string $supportUrl): void
    {
        $this->supportUrl = $supportUrl;
    }

    /**
     * Converts the AfterpayTouchInfo object to a human-readable string representation.
     *
     * @return string The string representation of the AfterpayTouchInfo object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AfterpayTouchInfo',
            ['supportEmail' => $this->supportEmail, 'supportUrl' => $this->supportUrl]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->supportEmail)) {
            $json['supportEmail'] = $this->supportEmail;
        }
        $json['supportUrl']       = $this->supportUrl;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
