<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

/**
 * References to resources linked to the API credential.
 */
class ApiCredentialLinks2 implements \JsonSerializable
{
    /**
     * @var LinksElement1|null
     */
    private $allowedOrigins;

    /**
     * @var LinksElement2|null
     */
    private $company;

    /**
     * @var LinksElement3|null
     */
    private $generateApiKey;

    /**
     * @var LinksElement4|null
     */
    private $generateClientKey;

    /**
     * @var LinksElement5|null
     */
    private $merchant;

    /**
     * @var LinksElement6
     */
    private $self;

    /**
     * @param LinksElement6 $self
     */
    public function __construct(LinksElement6 $self)
    {
        $this->self = $self;
    }

    /**
     * Returns Allowed Origins.
     * List of allowed origins.
     */
    public function getAllowedOrigins(): ?LinksElement1
    {
        return $this->allowedOrigins;
    }

    /**
     * Sets Allowed Origins.
     * List of allowed origins.
     *
     * @maps allowedOrigins
     */
    public function setAllowedOrigins(?LinksElement1 $allowedOrigins): void
    {
        $this->allowedOrigins = $allowedOrigins;
    }

    /**
     * Returns Company.
     * Company account that the API credential is linked to. Only present for company-level webhooks.
     */
    public function getCompany(): ?LinksElement2
    {
        return $this->company;
    }

    /**
     * Sets Company.
     * Company account that the API credential is linked to. Only present for company-level webhooks.
     *
     * @maps company
     */
    public function setCompany(?LinksElement2 $company): void
    {
        $this->company = $company;
    }

    /**
     * Returns Generate Api Key.
     * Generates a new API key. When you generate a new one, the existing key remains valid for 24 hours.
     */
    public function getGenerateApiKey(): ?LinksElement3
    {
        return $this->generateApiKey;
    }

    /**
     * Sets Generate Api Key.
     * Generates a new API key. When you generate a new one, the existing key remains valid for 24 hours.
     *
     * @maps generateApiKey
     */
    public function setGenerateApiKey(?LinksElement3 $generateApiKey): void
    {
        $this->generateApiKey = $generateApiKey;
    }

    /**
     * Returns Generate Client Key.
     * Generates a new client key, used to authenticate client-side requests. When you generate a new one,
     * the existing key remains valid for 24 hours.
     */
    public function getGenerateClientKey(): ?LinksElement4
    {
        return $this->generateClientKey;
    }

    /**
     * Sets Generate Client Key.
     * Generates a new client key, used to authenticate client-side requests. When you generate a new one,
     * the existing key remains valid for 24 hours.
     *
     * @maps generateClientKey
     */
    public function setGenerateClientKey(?LinksElement4 $generateClientKey): void
    {
        $this->generateClientKey = $generateClientKey;
    }

    /**
     * Returns Merchant.
     * The merchant account that the API credential is linked to. Only present for merchant-level API
     * credentials.
     */
    public function getMerchant(): ?LinksElement5
    {
        return $this->merchant;
    }

    /**
     * Sets Merchant.
     * The merchant account that the API credential is linked to. Only present for merchant-level API
     * credentials.
     *
     * @maps merchant
     */
    public function setMerchant(?LinksElement5 $merchant): void
    {
        $this->merchant = $merchant;
    }

    /**
     * Returns Self.
     * Link to the resource itself.
     */
    public function getSelf(): LinksElement6
    {
        return $this->self;
    }

    /**
     * Sets Self.
     * Link to the resource itself.
     *
     * @required
     * @maps self
     */
    public function setSelf(LinksElement6 $self): void
    {
        $this->self = $self;
    }

    /**
     * Converts the ApiCredentialLinks2 object to a human-readable string representation.
     *
     * @return string The string representation of the ApiCredentialLinks2 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ApiCredentialLinks2',
            [
                'allowedOrigins' => $this->allowedOrigins,
                'company' => $this->company,
                'generateApiKey' => $this->generateApiKey,
                'generateClientKey' => $this->generateClientKey,
                'merchant' => $this->merchant,
                'self' => $this->self
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->allowedOrigins)) {
            $json['allowedOrigins']    = $this->allowedOrigins;
        }
        if (isset($this->company)) {
            $json['company']           = $this->company;
        }
        if (isset($this->generateApiKey)) {
            $json['generateApiKey']    = $this->generateApiKey;
        }
        if (isset($this->generateClientKey)) {
            $json['generateClientKey'] = $this->generateClientKey;
        }
        if (isset($this->merchant)) {
            $json['merchant']          = $this->merchant;
        }
        $json['self']                  = $this->self;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
