<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

/**
 * Details to provide if `type` is **applepay**.
 */
class ApplePayInfo1 implements \JsonSerializable
{
    /**
     * @var string[]
     */
    private $domains;

    /**
     * @param string[] $domains
     */
    public function __construct(array $domains)
    {
        $this->domains = $domains;
    }

    /**
     * Returns Domains.
     * The list of merchant domains. Maximum: 99 domains per request.
     *
     * For more information, see [Apple Pay documentation](https://docs.adyen.com/payment-methods/apple-
     * pay/web-drop-in?tab=adyen-certificate-live_1#going-live).
     *
     * @return string[]
     */
    public function getDomains(): array
    {
        return $this->domains;
    }

    /**
     * Sets Domains.
     * The list of merchant domains. Maximum: 99 domains per request.
     *
     * For more information, see [Apple Pay documentation](https://docs.adyen.com/payment-methods/apple-
     * pay/web-drop-in?tab=adyen-certificate-live_1#going-live).
     *
     * @required
     * @maps domains
     *
     * @param string[] $domains
     */
    public function setDomains(array $domains): void
    {
        $this->domains = $domains;
    }

    /**
     * Converts the ApplePayInfo1 object to a human-readable string representation.
     *
     * @return string The string representation of the ApplePayInfo1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ApplePayInfo1', ['domains' => $this->domains]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['domains'] = $this->domains;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
