<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

/**
 * Information about your application. For more details, see [Building Adyen solutions](https://docs.
 * adyen.com/development-resources/building-adyen-solutions).
 */
class ApplicationInfo1 implements \JsonSerializable
{
    /**
     * @var CommonField4|null
     */
    private $adyenLibrary;

    /**
     * @var CommonField1|null
     */
    private $adyenPaymentSource;

    /**
     * @var ExternalPlatform2|null
     */
    private $externalPlatform;

    /**
     * @var CommonField2|null
     */
    private $merchantApplication;

    /**
     * @var MerchantDevice2|null
     */
    private $merchantDevice;

    /**
     * @var ShopperInteractionDevice2|null
     */
    private $shopperInteractionDevice;

    /**
     * Returns Adyen Library.
     * Adyen-developed software, such as libraries and plugins, used to interact with the Adyen API. For
     * example, Magento plugin, Java API library, etc.
     */
    public function getAdyenLibrary(): ?CommonField4
    {
        return $this->adyenLibrary;
    }

    /**
     * Sets Adyen Library.
     * Adyen-developed software, such as libraries and plugins, used to interact with the Adyen API. For
     * example, Magento plugin, Java API library, etc.
     *
     * @maps adyenLibrary
     */
    public function setAdyenLibrary(?CommonField4 $adyenLibrary): void
    {
        $this->adyenLibrary = $adyenLibrary;
    }

    /**
     * Returns Adyen Payment Source.
     * Adyen-developed software to get payment details. For example, Checkout SDK, Secured Fields SDK, etc.
     */
    public function getAdyenPaymentSource(): ?CommonField1
    {
        return $this->adyenPaymentSource;
    }

    /**
     * Sets Adyen Payment Source.
     * Adyen-developed software to get payment details. For example, Checkout SDK, Secured Fields SDK, etc.
     *
     * @maps adyenPaymentSource
     */
    public function setAdyenPaymentSource(?CommonField1 $adyenPaymentSource): void
    {
        $this->adyenPaymentSource = $adyenPaymentSource;
    }

    /**
     * Returns External Platform.
     * Third-party developed platform used to initiate payment requests. For example, Magento, Zuora, etc.
     */
    public function getExternalPlatform(): ?ExternalPlatform2
    {
        return $this->externalPlatform;
    }

    /**
     * Sets External Platform.
     * Third-party developed platform used to initiate payment requests. For example, Magento, Zuora, etc.
     *
     * @maps externalPlatform
     */
    public function setExternalPlatform(?ExternalPlatform2 $externalPlatform): void
    {
        $this->externalPlatform = $externalPlatform;
    }

    /**
     * Returns Merchant Application.
     * Merchant developed software, such as cashier application, used to interact with the Adyen API.
     */
    public function getMerchantApplication(): ?CommonField2
    {
        return $this->merchantApplication;
    }

    /**
     * Sets Merchant Application.
     * Merchant developed software, such as cashier application, used to interact with the Adyen API.
     *
     * @maps merchantApplication
     */
    public function setMerchantApplication(?CommonField2 $merchantApplication): void
    {
        $this->merchantApplication = $merchantApplication;
    }

    /**
     * Returns Merchant Device.
     * Merchant device information.
     */
    public function getMerchantDevice(): ?MerchantDevice2
    {
        return $this->merchantDevice;
    }

    /**
     * Sets Merchant Device.
     * Merchant device information.
     *
     * @maps merchantDevice
     */
    public function setMerchantDevice(?MerchantDevice2 $merchantDevice): void
    {
        $this->merchantDevice = $merchantDevice;
    }

    /**
     * Returns Shopper Interaction Device.
     * Shopper interaction device, such as terminal, mobile device or web browser, to initiate payment
     * requests.
     */
    public function getShopperInteractionDevice(): ?ShopperInteractionDevice2
    {
        return $this->shopperInteractionDevice;
    }

    /**
     * Sets Shopper Interaction Device.
     * Shopper interaction device, such as terminal, mobile device or web browser, to initiate payment
     * requests.
     *
     * @maps shopperInteractionDevice
     */
    public function setShopperInteractionDevice(?ShopperInteractionDevice2 $shopperInteractionDevice): void
    {
        $this->shopperInteractionDevice = $shopperInteractionDevice;
    }

    /**
     * Converts the ApplicationInfo1 object to a human-readable string representation.
     *
     * @return string The string representation of the ApplicationInfo1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ApplicationInfo1',
            [
                'adyenLibrary' => $this->adyenLibrary,
                'adyenPaymentSource' => $this->adyenPaymentSource,
                'externalPlatform' => $this->externalPlatform,
                'merchantApplication' => $this->merchantApplication,
                'merchantDevice' => $this->merchantDevice,
                'shopperInteractionDevice' => $this->shopperInteractionDevice
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->adyenLibrary)) {
            $json['adyenLibrary']             = $this->adyenLibrary;
        }
        if (isset($this->adyenPaymentSource)) {
            $json['adyenPaymentSource']       = $this->adyenPaymentSource;
        }
        if (isset($this->externalPlatform)) {
            $json['externalPlatform']         = $this->externalPlatform;
        }
        if (isset($this->merchantApplication)) {
            $json['merchantApplication']      = $this->merchantApplication;
        }
        if (isset($this->merchantDevice)) {
            $json['merchantDevice']           = $this->merchantDevice;
        }
        if (isset($this->shopperInteractionDevice)) {
            $json['shopperInteractionDevice'] = $this->shopperInteractionDevice;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
