<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The rule to specify the period, within which the recurring debit can happen, relative to the mandate
 * recurring date.
 *
 * Possible values:
 *
 * * **on**: On a specific date.
 *
 * * **before**:  Before and on a specific date.
 *
 * * **after**: On and after a specific date.
 */
class BillingAttemptsRule
{
    public const ON = 'on';

    public const BEFORE = 'before';

    public const AFTER = 'after';

    private const _ALL_VALUES = [self::ON, self::BEFORE, self::AFTER];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for BillingAttemptsRule.");
    }
}
