<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class BillingEntitiesResponse implements \JsonSerializable
{
    /**
     * @var BillingEntity[]|null
     */
    private $data;

    /**
     * Returns Data.
     * List of legal entities that can be used for the billing of orders.
     *
     * @return BillingEntity[]|null
     */
    public function getData(): ?array
    {
        return $this->data;
    }

    /**
     * Sets Data.
     * List of legal entities that can be used for the billing of orders.
     *
     * @maps data
     *
     * @param BillingEntity[]|null $data
     */
    public function setData(?array $data): void
    {
        $this->data = $data;
    }

    /**
     * Converts the BillingEntitiesResponse object to a human-readable string representation.
     *
     * @return string The string representation of the BillingEntitiesResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('BillingEntitiesResponse', ['data' => $this->data]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->data)) {
            $json['data'] = $this->data;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
