<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class CheckoutBankTransferAction implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $accountNumber;

    /**
     * @var string|null
     */
    private $bankCode;

    /**
     * @var string|null
     */
    private $beneficiary;

    /**
     * @var string|null
     */
    private $bic;

    /**
     * @var string|null
     */
    private $branchCode;

    /**
     * @var string|null
     */
    private $downloadUrl;

    /**
     * @var string|null
     */
    private $iban;

    /**
     * @var string|null
     */
    private $paymentMethodType;

    /**
     * @var string|null
     */
    private $reference;

    /**
     * @var string|null
     */
    private $routingNumber;

    /**
     * @var string|null
     */
    private $shopperEmail;

    /**
     * @var string|null
     */
    private $sortCode;

    /**
     * @var Amount10|null
     */
    private $totalAmount;

    /**
     * @var string
     */
    private $type;

    /**
     * @var string|null
     */
    private $url;

    /**
     * Returns Account Number.
     * The account number of the bank transfer.
     */
    public function getAccountNumber(): ?string
    {
        return $this->accountNumber;
    }

    /**
     * Sets Account Number.
     * The account number of the bank transfer.
     *
     * @maps accountNumber
     */
    public function setAccountNumber(?string $accountNumber): void
    {
        $this->accountNumber = $accountNumber;
    }

    /**
     * Returns Bank Code.
     * The bank code of the bank transfer.
     */
    public function getBankCode(): ?string
    {
        return $this->bankCode;
    }

    /**
     * Sets Bank Code.
     * The bank code of the bank transfer.
     *
     * @maps bankCode
     */
    public function setBankCode(?string $bankCode): void
    {
        $this->bankCode = $bankCode;
    }

    /**
     * Returns Beneficiary.
     * The name of the account holder.
     */
    public function getBeneficiary(): ?string
    {
        return $this->beneficiary;
    }

    /**
     * Sets Beneficiary.
     * The name of the account holder.
     *
     * @maps beneficiary
     */
    public function setBeneficiary(?string $beneficiary): void
    {
        $this->beneficiary = $beneficiary;
    }

    /**
     * Returns Bic.
     * The BIC of the IBAN.
     */
    public function getBic(): ?string
    {
        return $this->bic;
    }

    /**
     * Sets Bic.
     * The BIC of the IBAN.
     *
     * @maps bic
     */
    public function setBic(?string $bic): void
    {
        $this->bic = $bic;
    }

    /**
     * Returns Branch Code.
     * The branch code of the bank transfer.
     */
    public function getBranchCode(): ?string
    {
        return $this->branchCode;
    }

    /**
     * Sets Branch Code.
     * The branch code of the bank transfer.
     *
     * @maps branchCode
     */
    public function setBranchCode(?string $branchCode): void
    {
        $this->branchCode = $branchCode;
    }

    /**
     * Returns Download Url.
     * The url to download payment details with.
     */
    public function getDownloadUrl(): ?string
    {
        return $this->downloadUrl;
    }

    /**
     * Sets Download Url.
     * The url to download payment details with.
     *
     * @maps downloadUrl
     */
    public function setDownloadUrl(?string $downloadUrl): void
    {
        $this->downloadUrl = $downloadUrl;
    }

    /**
     * Returns Iban.
     * The IBAN of the bank transfer.
     */
    public function getIban(): ?string
    {
        return $this->iban;
    }

    /**
     * Sets Iban.
     * The IBAN of the bank transfer.
     *
     * @maps iban
     */
    public function setIban(?string $iban): void
    {
        $this->iban = $iban;
    }

    /**
     * Returns Payment Method Type.
     * Specifies the payment method.
     */
    public function getPaymentMethodType(): ?string
    {
        return $this->paymentMethodType;
    }

    /**
     * Sets Payment Method Type.
     * Specifies the payment method.
     *
     * @maps paymentMethodType
     */
    public function setPaymentMethodType(?string $paymentMethodType): void
    {
        $this->paymentMethodType = $paymentMethodType;
    }

    /**
     * Returns Reference.
     * The transfer reference.
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     * The transfer reference.
     *
     * @maps reference
     */
    public function setReference(?string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Routing Number.
     * The routing number of the bank transfer.
     */
    public function getRoutingNumber(): ?string
    {
        return $this->routingNumber;
    }

    /**
     * Sets Routing Number.
     * The routing number of the bank transfer.
     *
     * @maps routingNumber
     */
    public function setRoutingNumber(?string $routingNumber): void
    {
        $this->routingNumber = $routingNumber;
    }

    /**
     * Returns Shopper Email.
     * The e-mail of the shopper, included if an e-mail was sent to the shopper.
     */
    public function getShopperEmail(): ?string
    {
        return $this->shopperEmail;
    }

    /**
     * Sets Shopper Email.
     * The e-mail of the shopper, included if an e-mail was sent to the shopper.
     *
     * @maps shopperEmail
     */
    public function setShopperEmail(?string $shopperEmail): void
    {
        $this->shopperEmail = $shopperEmail;
    }

    /**
     * Returns Sort Code.
     * The sort code of the bank transfer.
     */
    public function getSortCode(): ?string
    {
        return $this->sortCode;
    }

    /**
     * Sets Sort Code.
     * The sort code of the bank transfer.
     *
     * @maps sortCode
     */
    public function setSortCode(?string $sortCode): void
    {
        $this->sortCode = $sortCode;
    }

    /**
     * Returns Total Amount.
     * The amount of the bank transfer.
     */
    public function getTotalAmount(): ?Amount10
    {
        return $this->totalAmount;
    }

    /**
     * Sets Total Amount.
     * The amount of the bank transfer.
     *
     * @maps totalAmount
     */
    public function setTotalAmount(?Amount10 $totalAmount): void
    {
        $this->totalAmount = $totalAmount;
    }

    /**
     * Returns Type.
     * The type of the action.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The type of the action.
     *
     * @maps type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Url.
     * Specifies the URL to redirect to.
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     * Specifies the URL to redirect to.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url = $url;
    }

    /**
     * Converts the CheckoutBankTransferAction object to a human-readable string representation.
     *
     * @return string The string representation of the CheckoutBankTransferAction object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CheckoutBankTransferAction',
            [
                'accountNumber' => $this->accountNumber,
                'bankCode' => $this->bankCode,
                'beneficiary' => $this->beneficiary,
                'bic' => $this->bic,
                'branchCode' => $this->branchCode,
                'downloadUrl' => $this->downloadUrl,
                'iban' => $this->iban,
                'paymentMethodType' => $this->paymentMethodType,
                'reference' => $this->reference,
                'routingNumber' => $this->routingNumber,
                'shopperEmail' => $this->shopperEmail,
                'sortCode' => $this->sortCode,
                'totalAmount' => $this->totalAmount,
                'type' => $this->type,
                'url' => $this->url
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->accountNumber)) {
            $json['accountNumber']     = $this->accountNumber;
        }
        if (isset($this->bankCode)) {
            $json['bankCode']          = $this->bankCode;
        }
        if (isset($this->beneficiary)) {
            $json['beneficiary']       = $this->beneficiary;
        }
        if (isset($this->bic)) {
            $json['bic']               = $this->bic;
        }
        if (isset($this->branchCode)) {
            $json['branchCode']        = $this->branchCode;
        }
        if (isset($this->downloadUrl)) {
            $json['downloadUrl']       = $this->downloadUrl;
        }
        if (isset($this->iban)) {
            $json['iban']              = $this->iban;
        }
        if (isset($this->paymentMethodType)) {
            $json['paymentMethodType'] = $this->paymentMethodType;
        }
        if (isset($this->reference)) {
            $json['reference']         = $this->reference;
        }
        if (isset($this->routingNumber)) {
            $json['routingNumber']     = $this->routingNumber;
        }
        if (isset($this->shopperEmail)) {
            $json['shopperEmail']      = $this->shopperEmail;
        }
        if (isset($this->sortCode)) {
            $json['sortCode']          = $this->sortCode;
        }
        if (isset($this->totalAmount)) {
            $json['totalAmount']       = $this->totalAmount;
        }
        $json['type']                  = $this->type;
        if (isset($this->url)) {
            $json['url']               = $this->url;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
