<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class CheckoutForwardResponse implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $merchantReference;

    /**
     * @var string|null
     */
    private $pspReference;

    /**
     * @var CheckoutForwardResponseFromUrl2
     */
    private $response;

    /**
     * @var string|null
     */
    private $storedPaymentMethodId;

    /**
     * @param CheckoutForwardResponseFromUrl2 $response
     */
    public function __construct(CheckoutForwardResponseFromUrl2 $response)
    {
        $this->response = $response;
    }

    /**
     * Returns Merchant Reference.
     * Merchant defined payment reference.
     */
    public function getMerchantReference(): ?string
    {
        return $this->merchantReference;
    }

    /**
     * Sets Merchant Reference.
     * Merchant defined payment reference.
     *
     * @maps merchantReference
     */
    public function setMerchantReference(?string $merchantReference): void
    {
        $this->merchantReference = $merchantReference;
    }

    /**
     * Returns Psp Reference.
     * Adyen's 16-character reference associated with the transaction/request. This value is globally
     * unique. Use this reference when you communicate with us about this request.
     */
    public function getPspReference(): ?string
    {
        return $this->pspReference;
    }

    /**
     * Sets Psp Reference.
     * Adyen's 16-character reference associated with the transaction/request. This value is globally
     * unique. Use this reference when you communicate with us about this request.
     *
     * @maps pspReference
     */
    public function setPspReference(?string $pspReference): void
    {
        $this->pspReference = $pspReference;
    }

    /**
     * Returns Response.
     * The details of the response Adyen received from the third party.
     */
    public function getResponse(): CheckoutForwardResponseFromUrl2
    {
        return $this->response;
    }

    /**
     * Sets Response.
     * The details of the response Adyen received from the third party.
     *
     * @required
     * @maps response
     */
    public function setResponse(CheckoutForwardResponseFromUrl2 $response): void
    {
        $this->response = $response;
    }

    /**
     * Returns Stored Payment Method Id.
     * The unique identifier of the token.
     */
    public function getStoredPaymentMethodId(): ?string
    {
        return $this->storedPaymentMethodId;
    }

    /**
     * Sets Stored Payment Method Id.
     * The unique identifier of the token.
     *
     * @maps storedPaymentMethodId
     */
    public function setStoredPaymentMethodId(?string $storedPaymentMethodId): void
    {
        $this->storedPaymentMethodId = $storedPaymentMethodId;
    }

    /**
     * Converts the CheckoutForwardResponse object to a human-readable string representation.
     *
     * @return string The string representation of the CheckoutForwardResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CheckoutForwardResponse',
            [
                'merchantReference' => $this->merchantReference,
                'pspReference' => $this->pspReference,
                'response' => $this->response,
                'storedPaymentMethodId' => $this->storedPaymentMethodId
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->merchantReference)) {
            $json['merchantReference']     = $this->merchantReference;
        }
        if (isset($this->pspReference)) {
            $json['pspReference']          = $this->pspReference;
        }
        $json['response']                  = $this->response;
        if (isset($this->storedPaymentMethodId)) {
            $json['storedPaymentMethodId'] = $this->storedPaymentMethodId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
