<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class CheckoutAwaitAction implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $paymentData;

    /**
     * @var string|null
     */
    private $paymentMethodType;

    /**
     * @var string
     */
    private $type;

    /**
     * @var string|null
     */
    private $url;

    /**
     * Returns Payment Data.
     * Encoded payment data.
     */
    public function getPaymentData(): ?string
    {
        return $this->paymentData;
    }

    /**
     * Sets Payment Data.
     * Encoded payment data.
     *
     * @maps paymentData
     */
    public function setPaymentData(?string $paymentData): void
    {
        $this->paymentData = $paymentData;
    }

    /**
     * Returns Payment Method Type.
     * Specifies the payment method.
     */
    public function getPaymentMethodType(): ?string
    {
        return $this->paymentMethodType;
    }

    /**
     * Sets Payment Method Type.
     * Specifies the payment method.
     *
     * @maps paymentMethodType
     */
    public function setPaymentMethodType(?string $paymentMethodType): void
    {
        $this->paymentMethodType = $paymentMethodType;
    }

    /**
     * Returns Type.
     * **await**
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * **await**
     *
     * @maps type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Url.
     * Specifies the URL to redirect to.
     */
    public function getUrl(): ?string
    {
        return $this->url;
    }

    /**
     * Sets Url.
     * Specifies the URL to redirect to.
     *
     * @maps url
     */
    public function setUrl(?string $url): void
    {
        $this->url = $url;
    }

    /**
     * Converts the CheckoutAwaitAction object to a human-readable string representation.
     *
     * @return string The string representation of the CheckoutAwaitAction object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CheckoutAwaitAction',
            [
                'paymentData' => $this->paymentData,
                'paymentMethodType' => $this->paymentMethodType,
                'type' => $this->type,
                'url' => $this->url
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->paymentData)) {
            $json['paymentData']       = $this->paymentData;
        }
        if (isset($this->paymentMethodType)) {
            $json['paymentMethodType'] = $this->paymentMethodType;
        }
        $json['type']                  = $this->type;
        if (isset($this->url)) {
            $json['url']               = $this->url;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
