<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

/**
 * Settings for terminal connectivity features.
 */
class Connectivity1 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $simcardStatus;

    /**
     * @var EventUrl3|null
     */
    private $terminalIpAddressUrl;

    /**
     * Returns Simcard Status.
     * Indicates the status of the SIM card in the payment terminal. Can be updated and received only at
     * terminal level, and only for models that support cellular connectivity.
     *
     * Possible values:
     * * **ACTIVATED**: the SIM card is activated. Cellular connectivity may still need to be enabled on
     * the terminal itself, in the **Network** settings.
     * * **INVENTORY**: the SIM card is not activated. The terminal can't use cellular connectivity.
     */
    public function getSimcardStatus(): ?string
    {
        return $this->simcardStatus;
    }

    /**
     * Sets Simcard Status.
     * Indicates the status of the SIM card in the payment terminal. Can be updated and received only at
     * terminal level, and only for models that support cellular connectivity.
     *
     * Possible values:
     * * **ACTIVATED**: the SIM card is activated. Cellular connectivity may still need to be enabled on
     * the terminal itself, in the **Network** settings.
     * * **INVENTORY**: the SIM card is not activated. The terminal can't use cellular connectivity.
     *
     * @maps simcardStatus
     * @factory \AdyenApIsLib\Models\SimcardStatus::checkValue
     */
    public function setSimcardStatus(?string $simcardStatus): void
    {
        $this->simcardStatus = $simcardStatus;
    }

    /**
     * Returns Terminal Ip Address Url.
     * The list of local and public URLs to send notifications to when using local integrations.
     */
    public function getTerminalIpAddressUrl(): ?EventUrl3
    {
        return $this->terminalIpAddressUrl;
    }

    /**
     * Sets Terminal Ip Address Url.
     * The list of local and public URLs to send notifications to when using local integrations.
     *
     * @maps terminalIPAddressURL
     */
    public function setTerminalIpAddressUrl(?EventUrl3 $terminalIpAddressUrl): void
    {
        $this->terminalIpAddressUrl = $terminalIpAddressUrl;
    }

    /**
     * Converts the Connectivity1 object to a human-readable string representation.
     *
     * @return string The string representation of the Connectivity1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Connectivity1',
            ['simcardStatus' => $this->simcardStatus, 'terminalIpAddressUrl' => $this->terminalIpAddressUrl]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->simcardStatus)) {
            $json['simcardStatus']        = SimcardStatus::checkValue($this->simcardStatus);
        }
        if (isset($this->terminalIpAddressUrl)) {
            $json['terminalIPAddressURL'] = $this->terminalIpAddressUrl;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
