<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The type of recurring contract to be used.
 * Possible values:
 * * `ONECLICK` – Payment details can be used to initiate a one-click payment, where the shopper enters
 * the [card security code (CVC/CVV)](https://docs.adyen.com/payments-fundamentals/payment-
 * glossary#card-security-code-cvc-cvv-cid).
 * * `RECURRING` – Payment details can be used without the card security code to initiate [card-not-
 * present transactions](https://docs.adyen.com/payments-fundamentals/payment-glossary#card-not-present-
 * cnp).
 * * `ONECLICK,RECURRING` – Payment details can be used regardless of whether the shopper is on your
 * site or not.
 * * `PAYOUT` – Payment details can be used to [make a payout](https://docs.adyen.com/online-
 * payments/online-payouts).
 * * `EXTERNAL` - Use this when you store payment details and send the raw card number or network token
 * directly in your API request.
 */
class Contract
{
    public const ONECLICK = 'ONECLICK';

    public const ENUM_ONECLICKRECURRING = 'ONECLICK,RECURRING';

    public const RECURRING = 'RECURRING';

    public const PAYOUT = 'PAYOUT';

    public const EXTERNAL = 'EXTERNAL';

    private const _ALL_VALUES =
        [self::ONECLICK, self::ENUM_ONECLICKRECURRING, self::RECURRING, self::PAYOUT, self::EXTERNAL];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for Contract.");
    }
}
