<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class CreateApiCredentialResponse implements \JsonSerializable
{
    /**
     * @var ApiCredentialLinks2|null
     */
    private $links;

    /**
     * @var bool
     */
    private $active;

    /**
     * @var string[]
     */
    private $allowedIpAddresses;

    /**
     * @var AllowedOrigin[]|null
     */
    private $allowedOrigins;

    /**
     * @var string
     */
    private $apiKey;

    /**
     * @var string
     */
    private $clientKey;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string
     */
    private $id;

    /**
     * @var string
     */
    private $password;

    /**
     * @var string[]
     */
    private $roles;

    /**
     * @var string
     */
    private $username;

    /**
     * @param bool $active
     * @param string[] $allowedIpAddresses
     * @param string $apiKey
     * @param string $clientKey
     * @param string $id
     * @param string $password
     * @param string[] $roles
     * @param string $username
     */
    public function __construct(
        bool $active,
        array $allowedIpAddresses,
        string $apiKey,
        string $clientKey,
        string $id,
        string $password,
        array $roles,
        string $username
    ) {
        $this->active = $active;
        $this->allowedIpAddresses = $allowedIpAddresses;
        $this->apiKey = $apiKey;
        $this->clientKey = $clientKey;
        $this->id = $id;
        $this->password = $password;
        $this->roles = $roles;
        $this->username = $username;
    }

    /**
     * Returns Links.
     * References to resources linked to the API credential.
     */
    public function getLinks(): ?ApiCredentialLinks2
    {
        return $this->links;
    }

    /**
     * Sets Links.
     * References to resources linked to the API credential.
     *
     * @maps _links
     */
    public function setLinks(?ApiCredentialLinks2 $links): void
    {
        $this->links = $links;
    }

    /**
     * Returns Active.
     * Indicates if the API credential is enabled. Must be set to **true** to use the credential in your
     * integration.
     */
    public function getActive(): bool
    {
        return $this->active;
    }

    /**
     * Sets Active.
     * Indicates if the API credential is enabled. Must be set to **true** to use the credential in your
     * integration.
     *
     * @required
     * @maps active
     */
    public function setActive(bool $active): void
    {
        $this->active = $active;
    }

    /**
     * Returns Allowed Ip Addresses.
     * List of IP addresses from which your client can make requests.
     *
     * If the list is empty, we allow requests from any IP.
     * If the list is not empty and we get a request from an IP which is not on the list, you get a
     * security error.
     *
     * @return string[]
     */
    public function getAllowedIpAddresses(): array
    {
        return $this->allowedIpAddresses;
    }

    /**
     * Sets Allowed Ip Addresses.
     * List of IP addresses from which your client can make requests.
     *
     * If the list is empty, we allow requests from any IP.
     * If the list is not empty and we get a request from an IP which is not on the list, you get a
     * security error.
     *
     * @required
     * @maps allowedIpAddresses
     *
     * @param string[] $allowedIpAddresses
     */
    public function setAllowedIpAddresses(array $allowedIpAddresses): void
    {
        $this->allowedIpAddresses = $allowedIpAddresses;
    }

    /**
     * Returns Allowed Origins.
     * List containing the [allowed origins](https://docs.adyen.com/development-resources/client-side-
     * authentication#allowed-origins) linked to the API credential.
     *
     * @return AllowedOrigin[]|null
     */
    public function getAllowedOrigins(): ?array
    {
        return $this->allowedOrigins;
    }

    /**
     * Sets Allowed Origins.
     * List containing the [allowed origins](https://docs.adyen.com/development-resources/client-side-
     * authentication#allowed-origins) linked to the API credential.
     *
     * @maps allowedOrigins
     *
     * @param AllowedOrigin[]|null $allowedOrigins
     */
    public function setAllowedOrigins(?array $allowedOrigins): void
    {
        $this->allowedOrigins = $allowedOrigins;
    }

    /**
     * Returns Api Key.
     * The API key for the API credential that was created.
     */
    public function getApiKey(): string
    {
        return $this->apiKey;
    }

    /**
     * Sets Api Key.
     * The API key for the API credential that was created.
     *
     * @required
     * @maps apiKey
     */
    public function setApiKey(string $apiKey): void
    {
        $this->apiKey = $apiKey;
    }

    /**
     * Returns Client Key.
     * Public key used for [client-side authentication](https://docs.adyen.com/development-resources/client-
     * side-authentication). The client key is required for Drop-in and Components integrations.
     */
    public function getClientKey(): string
    {
        return $this->clientKey;
    }

    /**
     * Sets Client Key.
     * Public key used for [client-side authentication](https://docs.adyen.com/development-resources/client-
     * side-authentication). The client key is required for Drop-in and Components integrations.
     *
     * @required
     * @maps clientKey
     */
    public function setClientKey(string $clientKey): void
    {
        $this->clientKey = $clientKey;
    }

    /**
     * Returns Description.
     * Description of the API credential.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Description of the API credential.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Id.
     * Unique identifier of the API credential.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * Unique identifier of the API credential.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Password.
     * The password for the API credential that was created.
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    /**
     * Sets Password.
     * The password for the API credential that was created.
     *
     * @required
     * @maps password
     */
    public function setPassword(string $password): void
    {
        $this->password = $password;
    }

    /**
     * Returns Roles.
     * List of [roles](https://docs.adyen.com/development-resources/api-credentials#roles-1) for the API
     * credential.
     *
     * @return string[]
     */
    public function getRoles(): array
    {
        return $this->roles;
    }

    /**
     * Sets Roles.
     * List of [roles](https://docs.adyen.com/development-resources/api-credentials#roles-1) for the API
     * credential.
     *
     * @required
     * @maps roles
     *
     * @param string[] $roles
     */
    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    /**
     * Returns Username.
     * The name of the [API credential](https://docs.adyen.com/development-resources/api-credentials), for
     * example **ws@Company.TestCompany**.
     */
    public function getUsername(): string
    {
        return $this->username;
    }

    /**
     * Sets Username.
     * The name of the [API credential](https://docs.adyen.com/development-resources/api-credentials), for
     * example **ws@Company.TestCompany**.
     *
     * @required
     * @maps username
     */
    public function setUsername(string $username): void
    {
        $this->username = $username;
    }

    /**
     * Converts the CreateApiCredentialResponse object to a human-readable string representation.
     *
     * @return string The string representation of the CreateApiCredentialResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreateApiCredentialResponse',
            [
                'links' => $this->links,
                'active' => $this->active,
                'allowedIpAddresses' => $this->allowedIpAddresses,
                'allowedOrigins' => $this->allowedOrigins,
                'apiKey' => $this->apiKey,
                'clientKey' => $this->clientKey,
                'description' => $this->description,
                'id' => $this->id,
                'password' => $this->password,
                'roles' => $this->roles,
                'username' => $this->username
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->links)) {
            $json['_links']         = $this->links;
        }
        $json['active']             = $this->active;
        $json['allowedIpAddresses'] = $this->allowedIpAddresses;
        if (isset($this->allowedOrigins)) {
            $json['allowedOrigins'] = $this->allowedOrigins;
        }
        $json['apiKey']             = $this->apiKey;
        $json['clientKey']          = $this->clientKey;
        if (isset($this->description)) {
            $json['description']    = $this->description;
        }
        $json['id']                 = $this->id;
        $json['password']           = $this->password;
        $json['roles']              = $this->roles;
        $json['username']           = $this->username;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
