<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Indicator regarding the delivery address.
 * Allowed values:
 * * `shipToBillingAddress`
 * * `shipToVerifiedAddress`
 * * `shipToNewAddress`
 * * `shipToStore`
 * * `digitalGoods`
 * * `goodsNotShipped`
 * * `other`
 */
class DeliveryAddressIndicator
{
    public const SHIPTOBILLINGADDRESS = 'shipToBillingAddress';

    public const SHIPTOVERIFIEDADDRESS = 'shipToVerifiedAddress';

    public const SHIPTONEWADDRESS = 'shipToNewAddress';

    public const SHIPTOSTORE = 'shipToStore';

    public const DIGITALGOODS = 'digitalGoods';

    public const GOODSNOTSHIPPED = 'goodsNotShipped';

    public const OTHER = 'other';

    private const _ALL_VALUES = [
        self::SHIPTOBILLINGADDRESS,
        self::SHIPTOVERIFIEDADDRESS,
        self::SHIPTONEWADDRESS,
        self::SHIPTOSTORE,
        self::DIGITALGOODS,
        self::GOODSNOTSHIPPED,
        self::OTHER
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for DeliveryAddressIndicator.");
    }
}
