<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class DonationCampaignsResponse implements \JsonSerializable
{
    /**
     * @var DonationCampaign[]|null
     */
    private $donationCampaigns;

    /**
     * Returns Donation Campaigns.
     * List of active donation campaigns for your merchant account.
     *
     * @return DonationCampaign[]|null
     */
    public function getDonationCampaigns(): ?array
    {
        return $this->donationCampaigns;
    }

    /**
     * Sets Donation Campaigns.
     * List of active donation campaigns for your merchant account.
     *
     * @maps donationCampaigns
     *
     * @param DonationCampaign[]|null $donationCampaigns
     */
    public function setDonationCampaigns(?array $donationCampaigns): void
    {
        $this->donationCampaigns = $donationCampaigns;
    }

    /**
     * Converts the DonationCampaignsResponse object to a human-readable string representation.
     *
     * @return string The string representation of the DonationCampaignsResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('DonationCampaignsResponse', ['donationCampaigns' => $this->donationCampaigns]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->donationCampaigns)) {
            $json['donationCampaigns'] = $this->donationCampaigns;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
