<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use AdyenApIsLib\Utils\DateTimeHelper;
use stdClass;

class ExternalTerminalAction implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $actionType;

    /**
     * @var string|null
     */
    private $config;

    /**
     * @var \DateTime|null
     */
    private $confirmedAt;

    /**
     * @var string|null
     */
    private $id;

    /**
     * @var string|null
     */
    private $result;

    /**
     * @var \DateTime|null
     */
    private $scheduledAt;

    /**
     * @var string|null
     */
    private $status;

    /**
     * @var string|null
     */
    private $terminalId;

    /**
     * Returns Action Type.
     * The type of terminal action: **InstallAndroidApp**, **UninstallAndroidApp**,
     * **InstallAndroidCertificate**, or **UninstallAndroidCertificate**.
     */
    public function getActionType(): ?string
    {
        return $this->actionType;
    }

    /**
     * Sets Action Type.
     * The type of terminal action: **InstallAndroidApp**, **UninstallAndroidApp**,
     * **InstallAndroidCertificate**, or **UninstallAndroidCertificate**.
     *
     * @maps actionType
     */
    public function setActionType(?string $actionType): void
    {
        $this->actionType = $actionType;
    }

    /**
     * Returns Config.
     * Technical information about the terminal action.
     */
    public function getConfig(): ?string
    {
        return $this->config;
    }

    /**
     * Sets Config.
     * Technical information about the terminal action.
     *
     * @maps config
     */
    public function setConfig(?string $config): void
    {
        $this->config = $config;
    }

    /**
     * Returns Confirmed At.
     * The date and time when the action was carried out.
     */
    public function getConfirmedAt(): ?\DateTime
    {
        return $this->confirmedAt;
    }

    /**
     * Sets Confirmed At.
     * The date and time when the action was carried out.
     *
     * @maps confirmedAt
     * @factory \AdyenApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setConfirmedAt(?\DateTime $confirmedAt): void
    {
        $this->confirmedAt = $confirmedAt;
    }

    /**
     * Returns Id.
     * The unique ID of the terminal action.
     */
    public function getId(): ?string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The unique ID of the terminal action.
     *
     * @maps id
     */
    public function setId(?string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Result.
     * The result message for the action.
     */
    public function getResult(): ?string
    {
        return $this->result;
    }

    /**
     * Sets Result.
     * The result message for the action.
     *
     * @maps result
     */
    public function setResult(?string $result): void
    {
        $this->result = $result;
    }

    /**
     * Returns Scheduled At.
     * The date and time when the action was scheduled to happen.
     */
    public function getScheduledAt(): ?\DateTime
    {
        return $this->scheduledAt;
    }

    /**
     * Sets Scheduled At.
     * The date and time when the action was scheduled to happen.
     *
     * @maps scheduledAt
     * @factory \AdyenApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setScheduledAt(?\DateTime $scheduledAt): void
    {
        $this->scheduledAt = $scheduledAt;
    }

    /**
     * Returns Status.
     * The status of the terminal action: **pending**, **successful**, **failed**, **cancelled**, or
     * **tryLater**.
     */
    public function getStatus(): ?string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The status of the terminal action: **pending**, **successful**, **failed**, **cancelled**, or
     * **tryLater**.
     *
     * @maps status
     */
    public function setStatus(?string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Terminal Id.
     * The unique ID of the terminal that the action applies to.
     */
    public function getTerminalId(): ?string
    {
        return $this->terminalId;
    }

    /**
     * Sets Terminal Id.
     * The unique ID of the terminal that the action applies to.
     *
     * @maps terminalId
     */
    public function setTerminalId(?string $terminalId): void
    {
        $this->terminalId = $terminalId;
    }

    /**
     * Converts the ExternalTerminalAction object to a human-readable string representation.
     *
     * @return string The string representation of the ExternalTerminalAction object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ExternalTerminalAction',
            [
                'actionType' => $this->actionType,
                'config' => $this->config,
                'confirmedAt' => $this->confirmedAt,
                'id' => $this->id,
                'result' => $this->result,
                'scheduledAt' => $this->scheduledAt,
                'status' => $this->status,
                'terminalId' => $this->terminalId
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->actionType)) {
            $json['actionType']  = $this->actionType;
        }
        if (isset($this->config)) {
            $json['config']      = $this->config;
        }
        if (isset($this->confirmedAt)) {
            $json['confirmedAt'] = DateTimeHelper::toRfc3339DateTime($this->confirmedAt);
        }
        if (isset($this->id)) {
            $json['id']          = $this->id;
        }
        if (isset($this->result)) {
            $json['result']      = $this->result;
        }
        if (isset($this->scheduledAt)) {
            $json['scheduledAt'] = DateTimeHelper::toRfc3339DateTime($this->scheduledAt);
        }
        if (isset($this->status)) {
            $json['status']      = $this->status;
        }
        if (isset($this->terminalId)) {
            $json['terminalId']  = $this->terminalId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
