<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use AdyenApIsLib\Utils\DateTimeHelper;
use stdClass;

class ForexQuote implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $account;

    /**
     * @var string|null
     */
    private $accountType;

    /**
     * @var Amount3|null
     */
    private $baseAmount;

    /**
     * @var int
     */
    private $basePoints;

    /**
     * @var Amount4|null
     */
    private $buy;

    /**
     * @var Amount5|null
     */
    private $interbank;

    /**
     * @var string|null
     */
    private $reference;

    /**
     * @var Amount6|null
     */
    private $sell;

    /**
     * @var string|null
     */
    private $signature;

    /**
     * @var string|null
     */
    private $source;

    /**
     * @var string|null
     */
    private $type;

    /**
     * @var \DateTime
     */
    private $validTill;

    /**
     * @param int $basePoints
     * @param \DateTime $validTill
     */
    public function __construct(int $basePoints, \DateTime $validTill)
    {
        $this->basePoints = $basePoints;
        $this->validTill = $validTill;
    }

    /**
     * Returns Account.
     * The account name.
     */
    public function getAccount(): ?string
    {
        return $this->account;
    }

    /**
     * Sets Account.
     * The account name.
     *
     * @maps account
     */
    public function setAccount(?string $account): void
    {
        $this->account = $account;
    }

    /**
     * Returns Account Type.
     * The account type.
     */
    public function getAccountType(): ?string
    {
        return $this->accountType;
    }

    /**
     * Sets Account Type.
     * The account type.
     *
     * @maps accountType
     */
    public function setAccountType(?string $accountType): void
    {
        $this->accountType = $accountType;
    }

    /**
     * Returns Base Amount.
     * The base amount.
     */
    public function getBaseAmount(): ?Amount3
    {
        return $this->baseAmount;
    }

    /**
     * Sets Base Amount.
     * The base amount.
     *
     * @maps baseAmount
     */
    public function setBaseAmount(?Amount3 $baseAmount): void
    {
        $this->baseAmount = $baseAmount;
    }

    /**
     * Returns Base Points.
     * The base points.
     */
    public function getBasePoints(): int
    {
        return $this->basePoints;
    }

    /**
     * Sets Base Points.
     * The base points.
     *
     * @required
     * @maps basePoints
     */
    public function setBasePoints(int $basePoints): void
    {
        $this->basePoints = $basePoints;
    }

    /**
     * Returns Buy.
     * The buy rate.
     */
    public function getBuy(): ?Amount4
    {
        return $this->buy;
    }

    /**
     * Sets Buy.
     * The buy rate.
     *
     * @maps buy
     */
    public function setBuy(?Amount4 $buy): void
    {
        $this->buy = $buy;
    }

    /**
     * Returns Interbank.
     * The interbank amount.
     */
    public function getInterbank(): ?Amount5
    {
        return $this->interbank;
    }

    /**
     * Sets Interbank.
     * The interbank amount.
     *
     * @maps interbank
     */
    public function setInterbank(?Amount5 $interbank): void
    {
        $this->interbank = $interbank;
    }

    /**
     * Returns Reference.
     * The reference assigned to the forex quote request.
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     * The reference assigned to the forex quote request.
     *
     * @maps reference
     */
    public function setReference(?string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Sell.
     * The sell rate.
     */
    public function getSell(): ?Amount6
    {
        return $this->sell;
    }

    /**
     * Sets Sell.
     * The sell rate.
     *
     * @maps sell
     */
    public function setSell(?Amount6 $sell): void
    {
        $this->sell = $sell;
    }

    /**
     * Returns Signature.
     * The signature to validate the integrity.
     */
    public function getSignature(): ?string
    {
        return $this->signature;
    }

    /**
     * Sets Signature.
     * The signature to validate the integrity.
     *
     * @maps signature
     */
    public function setSignature(?string $signature): void
    {
        $this->signature = $signature;
    }

    /**
     * Returns Source.
     * The source of the forex quote.
     */
    public function getSource(): ?string
    {
        return $this->source;
    }

    /**
     * Sets Source.
     * The source of the forex quote.
     *
     * @maps source
     */
    public function setSource(?string $source): void
    {
        $this->source = $source;
    }

    /**
     * Returns Type.
     * The type of forex.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The type of forex.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Valid Till.
     * The date until which the forex quote is valid.
     */
    public function getValidTill(): \DateTime
    {
        return $this->validTill;
    }

    /**
     * Sets Valid Till.
     * The date until which the forex quote is valid.
     *
     * @required
     * @maps validTill
     * @factory \AdyenApIsLib\Utils\DateTimeHelper::fromRfc3339DateTime
     */
    public function setValidTill(\DateTime $validTill): void
    {
        $this->validTill = $validTill;
    }

    /**
     * Converts the ForexQuote object to a human-readable string representation.
     *
     * @return string The string representation of the ForexQuote object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ForexQuote',
            [
                'account' => $this->account,
                'accountType' => $this->accountType,
                'baseAmount' => $this->baseAmount,
                'basePoints' => $this->basePoints,
                'buy' => $this->buy,
                'interbank' => $this->interbank,
                'reference' => $this->reference,
                'sell' => $this->sell,
                'signature' => $this->signature,
                'source' => $this->source,
                'type' => $this->type,
                'validTill' => $this->validTill
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->account)) {
            $json['account']     = $this->account;
        }
        if (isset($this->accountType)) {
            $json['accountType'] = $this->accountType;
        }
        if (isset($this->baseAmount)) {
            $json['baseAmount']  = $this->baseAmount;
        }
        $json['basePoints']      = $this->basePoints;
        if (isset($this->buy)) {
            $json['buy']         = $this->buy;
        }
        if (isset($this->interbank)) {
            $json['interbank']   = $this->interbank;
        }
        if (isset($this->reference)) {
            $json['reference']   = $this->reference;
        }
        if (isset($this->sell)) {
            $json['sell']        = $this->sell;
        }
        if (isset($this->signature)) {
            $json['signature']   = $this->signature;
        }
        if (isset($this->source)) {
            $json['source']      = $this->source;
        }
        if (isset($this->type)) {
            $json['type']        = $this->type;
        }
        $json['validTill']       = DateTimeHelper::toRfc3339DateTime($this->validTill);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
