<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

/**
 * Details to provide if `type` is **googlepay**.
 */
class GooglePayInfo1 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $merchantId;

    /**
     * @var bool|null
     */
    private $reuseMerchantId;

    /**
     * @param string $merchantId
     */
    public function __construct(string $merchantId)
    {
        $this->merchantId = $merchantId;
    }

    /**
     * Returns Merchant Id.
     * Google Pay [Merchant ID](https://support.google.com/paymentscenter/answer/7163092?hl=en). Character
     * length and limitations: 16 alphanumeric characters or 20 numeric characters.
     */
    public function getMerchantId(): string
    {
        return $this->merchantId;
    }

    /**
     * Sets Merchant Id.
     * Google Pay [Merchant ID](https://support.google.com/paymentscenter/answer/7163092?hl=en). Character
     * length and limitations: 16 alphanumeric characters or 20 numeric characters.
     *
     * @required
     * @maps merchantId
     */
    public function setMerchantId(string $merchantId): void
    {
        $this->merchantId = $merchantId;
    }

    /**
     * Returns Reuse Merchant Id.
     * Indicates whether the Google Pay Merchant ID is used for several merchant accounts. Default value:
     * **false**.
     */
    public function getReuseMerchantId(): ?bool
    {
        return $this->reuseMerchantId;
    }

    /**
     * Sets Reuse Merchant Id.
     * Indicates whether the Google Pay Merchant ID is used for several merchant accounts. Default value:
     * **false**.
     *
     * @maps reuseMerchantId
     */
    public function setReuseMerchantId(?bool $reuseMerchantId): void
    {
        $this->reuseMerchantId = $reuseMerchantId;
    }

    /**
     * Converts the GooglePayInfo1 object to a human-readable string representation.
     *
     * @return string The string representation of the GooglePayInfo1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'GooglePayInfo1',
            ['merchantId' => $this->merchantId, 'reuseMerchantId' => $this->reuseMerchantId]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['merchantId']          = $this->merchantId;
        if (isset($this->reuseMerchantId)) {
            $json['reuseMerchantId'] = $this->reuseMerchantId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
