<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

/**
 * Generates a new API key. When you generate a new one, the existing key remains valid for 24 hours.
 */
class LinksElement3 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $href;

    /**
     * Returns Href.
     */
    public function getHref(): ?string
    {
        return $this->href;
    }

    /**
     * Sets Href.
     *
     * @maps href
     */
    public function setHref(?string $href): void
    {
        $this->href = $href;
    }

    /**
     * Converts the LinksElement3 object to a human-readable string representation.
     *
     * @return string The string representation of the LinksElement3 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('LinksElement3', ['href' => $this->href]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->href)) {
            $json['href'] = $this->href;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
