<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class Logo implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $data;

    /**
     * Returns Data.
     * The image file, converted to a Base64-encoded string, of the logo to be shown on the terminal.
     */
    public function getData(): ?string
    {
        return $this->data;
    }

    /**
     * Sets Data.
     * The image file, converted to a Base64-encoded string, of the logo to be shown on the terminal.
     *
     * @maps data
     */
    public function setData(?string $data): void
    {
        $this->data = $data;
    }

    /**
     * Converts the Logo object to a human-readable string representation.
     *
     * @return string The string representation of the Logo object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Logo', ['data' => $this->data]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->data)) {
            $json['data'] = $this->data;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
