<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

/**
 * Details to provide if `type` is **nyce**.
 */
class NyceInfo1 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $processingType;

    /**
     * @var TransactionDescriptionInfo1|null
     */
    private $transactionDescription;

    /**
     * @param string $processingType
     */
    public function __construct(string $processingType)
    {
        $this->processingType = $processingType;
    }

    /**
     * Returns Processing Type.
     * The type of transactions processed over this payment method.
     * Allowed values:
     * - **pos** for in-person payments.
     * - **billpay** for subscription payments, both the initial payment and the later recurring payments.
     * These transactions have `recurringProcessingModel` **Subscription**.
     * - **ecom** for all other card not present transactions. This includes non-recurring transactions and
     * transactions with `recurringProcessingModel` **CardOnFile** or **UnscheduledCardOnFile**.
     */
    public function getProcessingType(): string
    {
        return $this->processingType;
    }

    /**
     * Sets Processing Type.
     * The type of transactions processed over this payment method.
     * Allowed values:
     * - **pos** for in-person payments.
     * - **billpay** for subscription payments, both the initial payment and the later recurring payments.
     * These transactions have `recurringProcessingModel` **Subscription**.
     * - **ecom** for all other card not present transactions. This includes non-recurring transactions and
     * transactions with `recurringProcessingModel` **CardOnFile** or **UnscheduledCardOnFile**.
     *
     * @required
     * @maps processingType
     * @factory \AdyenApIsLib\Models\ProcessingType::checkValue
     */
    public function setProcessingType(string $processingType): void
    {
        $this->processingType = $processingType;
    }

    /**
     * Returns Transaction Description.
     * Information regarding the transaction description.
     * > You cannot configure the transaction description in the test environment.
     */
    public function getTransactionDescription(): ?TransactionDescriptionInfo1
    {
        return $this->transactionDescription;
    }

    /**
     * Sets Transaction Description.
     * Information regarding the transaction description.
     * > You cannot configure the transaction description in the test environment.
     *
     * @maps transactionDescription
     */
    public function setTransactionDescription(?TransactionDescriptionInfo1 $transactionDescription): void
    {
        $this->transactionDescription = $transactionDescription;
    }

    /**
     * Converts the NyceInfo1 object to a human-readable string representation.
     *
     * @return string The string representation of the NyceInfo1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'NyceInfo1',
            ['processingType' => $this->processingType, 'transactionDescription' => $this->transactionDescription]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['processingType']             = ProcessingType::checkValue($this->processingType);
        if (isset($this->transactionDescription)) {
            $json['transactionDescription'] = $this->transactionDescription;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
