<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

/**
 * Pagination references.
 */
class PaginationLinks1 implements \JsonSerializable
{
    /**
     * @var LinksElement9
     */
    private $first;

    /**
     * @var LinksElement10
     */
    private $last;

    /**
     * @var LinksElement11|null
     */
    private $next;

    /**
     * @var LinksElement12|null
     */
    private $prev;

    /**
     * @var LinksElement13
     */
    private $self;

    /**
     * @param LinksElement9 $first
     * @param LinksElement10 $last
     * @param LinksElement13 $self
     */
    public function __construct(LinksElement9 $first, LinksElement10 $last, LinksElement13 $self)
    {
        $this->first = $first;
        $this->last = $last;
        $this->self = $self;
    }

    /**
     * Returns First.
     * The first page.
     */
    public function getFirst(): LinksElement9
    {
        return $this->first;
    }

    /**
     * Sets First.
     * The first page.
     *
     * @required
     * @maps first
     */
    public function setFirst(LinksElement9 $first): void
    {
        $this->first = $first;
    }

    /**
     * Returns Last.
     * The last page.
     */
    public function getLast(): LinksElement10
    {
        return $this->last;
    }

    /**
     * Sets Last.
     * The last page.
     *
     * @required
     * @maps last
     */
    public function setLast(LinksElement10 $last): void
    {
        $this->last = $last;
    }

    /**
     * Returns Next.
     * The next page. Only present if there is a next page.
     */
    public function getNext(): ?LinksElement11
    {
        return $this->next;
    }

    /**
     * Sets Next.
     * The next page. Only present if there is a next page.
     *
     * @maps next
     */
    public function setNext(?LinksElement11 $next): void
    {
        $this->next = $next;
    }

    /**
     * Returns Prev.
     * The previous page. Only present if there is a previous page.
     */
    public function getPrev(): ?LinksElement12
    {
        return $this->prev;
    }

    /**
     * Sets Prev.
     * The previous page. Only present if there is a previous page.
     *
     * @maps prev
     */
    public function setPrev(?LinksElement12 $prev): void
    {
        $this->prev = $prev;
    }

    /**
     * Returns Self.
     * The current page.
     */
    public function getSelf(): LinksElement13
    {
        return $this->self;
    }

    /**
     * Sets Self.
     * The current page.
     *
     * @required
     * @maps self
     */
    public function setSelf(LinksElement13 $self): void
    {
        $this->self = $self;
    }

    /**
     * Converts the PaginationLinks1 object to a human-readable string representation.
     *
     * @return string The string representation of the PaginationLinks1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PaginationLinks1',
            [
                'first' => $this->first,
                'last' => $this->last,
                'next' => $this->next,
                'prev' => $this->prev,
                'self' => $this->self
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['first']    = $this->first;
        $json['last']     = $this->last;
        if (isset($this->next)) {
            $json['next'] = $this->next;
        }
        if (isset($this->prev)) {
            $json['prev'] = $this->prev;
        }
        $json['self']     = $this->self;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
