<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class PaymentMethod implements \JsonSerializable
{
    /**
     * @var PaymentMethodUpiApps[]|null
     */
    private $apps;

    /**
     * @var string|null
     */
    private $brand;

    /**
     * @var string[]|null
     */
    private $brands;

    /**
     * @var array<string,string>|null
     */
    private $configuration;

    /**
     * @var string|null
     */
    private $fundingSource;

    /**
     * @var PaymentMethodGroup2|null
     */
    private $group;

    /**
     * @var InputDetail[]|null
     */
    private $inputDetails;

    /**
     * @var PaymentMethodIssuer[]|null
     */
    private $issuers;

    /**
     * @var string|null
     */
    private $name;

    /**
     * @var bool|null
     */
    private $promoted;

    /**
     * @var string|null
     */
    private $type;

    /**
     * Returns Apps.
     * A list of apps for this payment method.
     *
     * @return PaymentMethodUpiApps[]|null
     */
    public function getApps(): ?array
    {
        return $this->apps;
    }

    /**
     * Sets Apps.
     * A list of apps for this payment method.
     *
     * @maps apps
     *
     * @param PaymentMethodUpiApps[]|null $apps
     */
    public function setApps(?array $apps): void
    {
        $this->apps = $apps;
    }

    /**
     * Returns Brand.
     * Brand for the selected gift card. For example: plastix, hmclub.
     */
    public function getBrand(): ?string
    {
        return $this->brand;
    }

    /**
     * Sets Brand.
     * Brand for the selected gift card. For example: plastix, hmclub.
     *
     * @maps brand
     */
    public function setBrand(?string $brand): void
    {
        $this->brand = $brand;
    }

    /**
     * Returns Brands.
     * List of possible brands. For example: visa, mc.
     *
     * @return string[]|null
     */
    public function getBrands(): ?array
    {
        return $this->brands;
    }

    /**
     * Sets Brands.
     * List of possible brands. For example: visa, mc.
     *
     * @maps brands
     *
     * @param string[]|null $brands
     */
    public function setBrands(?array $brands): void
    {
        $this->brands = $brands;
    }

    /**
     * Returns Configuration.
     * The configuration of the payment method.
     *
     * @return array<string,string>|null
     */
    public function getConfiguration(): ?array
    {
        return $this->configuration;
    }

    /**
     * Sets Configuration.
     * The configuration of the payment method.
     *
     * @maps configuration
     *
     * @param array<string,string>|null $configuration
     */
    public function setConfiguration(?array $configuration): void
    {
        $this->configuration = $configuration;
    }

    /**
     * Returns Funding Source.
     * The funding source of the payment method.
     */
    public function getFundingSource(): ?string
    {
        return $this->fundingSource;
    }

    /**
     * Sets Funding Source.
     * The funding source of the payment method.
     *
     * @maps fundingSource
     * @factory \AdyenApIsLib\Models\FundingSource9::checkValue
     */
    public function setFundingSource(?string $fundingSource): void
    {
        $this->fundingSource = $fundingSource;
    }

    /**
     * Returns Group.
     * The group where this payment method belongs to.
     */
    public function getGroup(): ?PaymentMethodGroup2
    {
        return $this->group;
    }

    /**
     * Sets Group.
     * The group where this payment method belongs to.
     *
     * @maps group
     */
    public function setGroup(?PaymentMethodGroup2 $group): void
    {
        $this->group = $group;
    }

    /**
     * Returns Input Details.
     * All input details to be provided to complete the payment with this payment method.
     *
     * @return InputDetail[]|null
     */
    public function getInputDetails(): ?array
    {
        return $this->inputDetails;
    }

    /**
     * Sets Input Details.
     * All input details to be provided to complete the payment with this payment method.
     *
     * @maps inputDetails
     *
     * @param InputDetail[]|null $inputDetails
     */
    public function setInputDetails(?array $inputDetails): void
    {
        $this->inputDetails = $inputDetails;
    }

    /**
     * Returns Issuers.
     * A list of issuers for this payment method.
     *
     * @return PaymentMethodIssuer[]|null
     */
    public function getIssuers(): ?array
    {
        return $this->issuers;
    }

    /**
     * Sets Issuers.
     * A list of issuers for this payment method.
     *
     * @maps issuers
     *
     * @param PaymentMethodIssuer[]|null $issuers
     */
    public function setIssuers(?array $issuers): void
    {
        $this->issuers = $issuers;
    }

    /**
     * Returns Name.
     * The displayable name of this payment method.
     */
    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The displayable name of this payment method.
     *
     * @maps name
     */
    public function setName(?string $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Promoted.
     * Indicates whether this payment method should be promoted or not.
     */
    public function getPromoted(): ?bool
    {
        return $this->promoted;
    }

    /**
     * Sets Promoted.
     * Indicates whether this payment method should be promoted or not.
     *
     * @maps promoted
     */
    public function setPromoted(?bool $promoted): void
    {
        $this->promoted = $promoted;
    }

    /**
     * Returns Type.
     * The unique payment method code.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The unique payment method code.
     *
     * @maps type
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the PaymentMethod object to a human-readable string representation.
     *
     * @return string The string representation of the PaymentMethod object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PaymentMethod',
            [
                'apps' => $this->apps,
                'brand' => $this->brand,
                'brands' => $this->brands,
                'configuration' => $this->configuration,
                'fundingSource' => $this->fundingSource,
                'group' => $this->group,
                'inputDetails' => $this->inputDetails,
                'issuers' => $this->issuers,
                'name' => $this->name,
                'promoted' => $this->promoted,
                'type' => $this->type
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->apps)) {
            $json['apps']          = $this->apps;
        }
        if (isset($this->brand)) {
            $json['brand']         = $this->brand;
        }
        if (isset($this->brands)) {
            $json['brands']        = $this->brands;
        }
        if (isset($this->configuration)) {
            $json['configuration'] = $this->configuration;
        }
        if (isset($this->fundingSource)) {
            $json['fundingSource'] = FundingSource9::checkValue($this->fundingSource);
        }
        if (isset($this->group)) {
            $json['group']         = $this->group;
        }
        if (isset($this->inputDetails)) {
            $json['inputDetails']  = $this->inputDetails;
        }
        if (isset($this->issuers)) {
            $json['issuers']       = $this->issuers;
        }
        if (isset($this->name)) {
            $json['name']          = $this->name;
        }
        if (isset($this->promoted)) {
            $json['promoted']      = $this->promoted;
        }
        if (isset($this->type)) {
            $json['type']          = $this->type;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
