<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class PayTo implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $checkoutAttemptId;

    /**
     * @var string|null
     */
    private $recurringDetailReference;

    /**
     * @var string|null
     */
    private $sdkData;

    /**
     * @var string|null
     */
    private $shopperAccountIdentifier;

    /**
     * @var string|null
     */
    private $storedPaymentMethodId;

    /**
     * @var string|null
     */
    private $type = Type36::PAYTO;

    /**
     * Returns Checkout Attempt Id.
     * The checkout attempt identifier.
     */
    public function getCheckoutAttemptId(): ?string
    {
        return $this->checkoutAttemptId;
    }

    /**
     * Sets Checkout Attempt Id.
     * The checkout attempt identifier.
     *
     * @maps checkoutAttemptId
     */
    public function setCheckoutAttemptId(?string $checkoutAttemptId): void
    {
        $this->checkoutAttemptId = $checkoutAttemptId;
    }

    /**
     * Returns Recurring Detail Reference.
     * This is the `recurringDetailReference` returned in the response when you created the token.
     */
    public function getRecurringDetailReference(): ?string
    {
        return $this->recurringDetailReference;
    }

    /**
     * Sets Recurring Detail Reference.
     * This is the `recurringDetailReference` returned in the response when you created the token.
     *
     * @maps recurringDetailReference
     */
    public function setRecurringDetailReference(?string $recurringDetailReference): void
    {
        $this->recurringDetailReference = $recurringDetailReference;
    }

    /**
     * Returns Sdk Data.
     * Base64-encoded JSON object containing SDK related parameters required by the SDK
     */
    public function getSdkData(): ?string
    {
        return $this->sdkData;
    }

    /**
     * Sets Sdk Data.
     * Base64-encoded JSON object containing SDK related parameters required by the SDK
     *
     * @maps sdkData
     */
    public function setSdkData(?string $sdkData): void
    {
        $this->sdkData = $sdkData;
    }

    /**
     * Returns Shopper Account Identifier.
     * The shopper's banking details or payId reference, used to complete payment.
     */
    public function getShopperAccountIdentifier(): ?string
    {
        return $this->shopperAccountIdentifier;
    }

    /**
     * Sets Shopper Account Identifier.
     * The shopper's banking details or payId reference, used to complete payment.
     *
     * @maps shopperAccountIdentifier
     */
    public function setShopperAccountIdentifier(?string $shopperAccountIdentifier): void
    {
        $this->shopperAccountIdentifier = $shopperAccountIdentifier;
    }

    /**
     * Returns Stored Payment Method Id.
     * This is the `recurringDetailReference` returned in the response when you created the token.
     */
    public function getStoredPaymentMethodId(): ?string
    {
        return $this->storedPaymentMethodId;
    }

    /**
     * Sets Stored Payment Method Id.
     * This is the `recurringDetailReference` returned in the response when you created the token.
     *
     * @maps storedPaymentMethodId
     */
    public function setStoredPaymentMethodId(?string $storedPaymentMethodId): void
    {
        $this->storedPaymentMethodId = $storedPaymentMethodId;
    }

    /**
     * Returns Type.
     * **payto**
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * **payto**
     *
     * @maps type
     * @factory \AdyenApIsLib\Models\Type36::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the PayTo object to a human-readable string representation.
     *
     * @return string The string representation of the PayTo object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'PayTo',
            [
                'checkoutAttemptId' => $this->checkoutAttemptId,
                'recurringDetailReference' => $this->recurringDetailReference,
                'sdkData' => $this->sdkData,
                'shopperAccountIdentifier' => $this->shopperAccountIdentifier,
                'storedPaymentMethodId' => $this->storedPaymentMethodId,
                'type' => $this->type
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->checkoutAttemptId)) {
            $json['checkoutAttemptId']        = $this->checkoutAttemptId;
        }
        if (isset($this->recurringDetailReference)) {
            $json['recurringDetailReference'] = $this->recurringDetailReference;
        }
        if (isset($this->sdkData)) {
            $json['sdkData']                  = $this->sdkData;
        }
        if (isset($this->shopperAccountIdentifier)) {
            $json['shopperAccountIdentifier'] = $this->shopperAccountIdentifier;
        }
        if (isset($this->storedPaymentMethodId)) {
            $json['storedPaymentMethodId']    = $this->storedPaymentMethodId;
        }
        if (isset($this->type)) {
            $json['type']                     = Type36::checkValue($this->type);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
