<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

/**
 * The work phone number provided by the cardholder. The phone number must consist of a country code,
 * followed by the number. If the value you provide does not follow the guidelines, we do not submit it
 * for authentication.
 * > Required for Visa and JCB transactions that require 3D Secure 2 authentication, if you did not
 * include the `shopperEmail`, and did not send the shopper's phone number in `telephoneNumber`.
 */
class Phone2 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $cc;

    /**
     * @var string|null
     */
    private $subscriber;

    /**
     * Returns Cc.
     * Country code. Length: 1–3 digits.
     */
    public function getCc(): ?string
    {
        return $this->cc;
    }

    /**
     * Sets Cc.
     * Country code. Length: 1–3 digits.
     *
     * @maps cc
     */
    public function setCc(?string $cc): void
    {
        $this->cc = $cc;
    }

    /**
     * Returns Subscriber.
     * Subscriber number. Length: 4-15  digits.
     */
    public function getSubscriber(): ?string
    {
        return $this->subscriber;
    }

    /**
     * Sets Subscriber.
     * Subscriber number. Length: 4-15  digits.
     *
     * @maps subscriber
     */
    public function setSubscriber(?string $subscriber): void
    {
        $this->subscriber = $subscriber;
    }

    /**
     * Converts the Phone2 object to a human-readable string representation.
     *
     * @return string The string representation of the Phone2 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('Phone2', ['cc' => $this->cc, 'subscriber' => $this->subscriber]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->cc)) {
            $json['cc']         = $this->cc;
        }
        if (isset($this->subscriber)) {
            $json['subscriber'] = $this->subscriber;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
