<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class ResponseAdditionalDataBillingAddress implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $billingAddressCity;

    /**
     * @var string|null
     */
    private $billingAddressCountry;

    /**
     * @var string|null
     */
    private $billingAddressHouseNumberOrName;

    /**
     * @var string|null
     */
    private $billingAddressPostalCode;

    /**
     * @var string|null
     */
    private $billingAddressStateOrProvince;

    /**
     * @var string|null
     */
    private $billingAddressStreet;

    /**
     * Returns Billing Address City.
     * The billing address city passed in the payment request.
     */
    public function getBillingAddressCity(): ?string
    {
        return $this->billingAddressCity;
    }

    /**
     * Sets Billing Address City.
     * The billing address city passed in the payment request.
     *
     * @maps billingAddress.city
     */
    public function setBillingAddressCity(?string $billingAddressCity): void
    {
        $this->billingAddressCity = $billingAddressCity;
    }

    /**
     * Returns Billing Address Country.
     * The billing address country passed in the payment request.
     *
     * Example: NL
     */
    public function getBillingAddressCountry(): ?string
    {
        return $this->billingAddressCountry;
    }

    /**
     * Sets Billing Address Country.
     * The billing address country passed in the payment request.
     *
     * Example: NL
     *
     * @maps billingAddress.country
     */
    public function setBillingAddressCountry(?string $billingAddressCountry): void
    {
        $this->billingAddressCountry = $billingAddressCountry;
    }

    /**
     * Returns Billing Address House Number or Name.
     * The billing address house number or name passed in the payment request.
     */
    public function getBillingAddressHouseNumberOrName(): ?string
    {
        return $this->billingAddressHouseNumberOrName;
    }

    /**
     * Sets Billing Address House Number or Name.
     * The billing address house number or name passed in the payment request.
     *
     * @maps billingAddress.houseNumberOrName
     */
    public function setBillingAddressHouseNumberOrName(?string $billingAddressHouseNumberOrName): void
    {
        $this->billingAddressHouseNumberOrName = $billingAddressHouseNumberOrName;
    }

    /**
     * Returns Billing Address Postal Code.
     * The billing address postal code passed in the payment request.
     *
     * Example: 1011 DJ
     */
    public function getBillingAddressPostalCode(): ?string
    {
        return $this->billingAddressPostalCode;
    }

    /**
     * Sets Billing Address Postal Code.
     * The billing address postal code passed in the payment request.
     *
     * Example: 1011 DJ
     *
     * @maps billingAddress.postalCode
     */
    public function setBillingAddressPostalCode(?string $billingAddressPostalCode): void
    {
        $this->billingAddressPostalCode = $billingAddressPostalCode;
    }

    /**
     * Returns Billing Address State or Province.
     * The billing address state or province passed in the payment request.
     *
     * Example: NH
     */
    public function getBillingAddressStateOrProvince(): ?string
    {
        return $this->billingAddressStateOrProvince;
    }

    /**
     * Sets Billing Address State or Province.
     * The billing address state or province passed in the payment request.
     *
     * Example: NH
     *
     * @maps billingAddress.stateOrProvince
     */
    public function setBillingAddressStateOrProvince(?string $billingAddressStateOrProvince): void
    {
        $this->billingAddressStateOrProvince = $billingAddressStateOrProvince;
    }

    /**
     * Returns Billing Address Street.
     * The billing address street passed in the payment request.
     */
    public function getBillingAddressStreet(): ?string
    {
        return $this->billingAddressStreet;
    }

    /**
     * Sets Billing Address Street.
     * The billing address street passed in the payment request.
     *
     * @maps billingAddress.street
     */
    public function setBillingAddressStreet(?string $billingAddressStreet): void
    {
        $this->billingAddressStreet = $billingAddressStreet;
    }

    /**
     * Converts the ResponseAdditionalDataBillingAddress object to a human-readable string representation.
     *
     * @return string The string representation of the ResponseAdditionalDataBillingAddress object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ResponseAdditionalDataBillingAddress',
            [
                'billingAddressCity' => $this->billingAddressCity,
                'billingAddressCountry' => $this->billingAddressCountry,
                'billingAddressHouseNumberOrName' => $this->billingAddressHouseNumberOrName,
                'billingAddressPostalCode' => $this->billingAddressPostalCode,
                'billingAddressStateOrProvince' => $this->billingAddressStateOrProvince,
                'billingAddressStreet' => $this->billingAddressStreet
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->billingAddressCity)) {
            $json['billingAddress.city']              = $this->billingAddressCity;
        }
        if (isset($this->billingAddressCountry)) {
            $json['billingAddress.country']           = $this->billingAddressCountry;
        }
        if (isset($this->billingAddressHouseNumberOrName)) {
            $json['billingAddress.houseNumberOrName'] = $this->billingAddressHouseNumberOrName;
        }
        if (isset($this->billingAddressPostalCode)) {
            $json['billingAddress.postalCode']        = $this->billingAddressPostalCode;
        }
        if (isset($this->billingAddressStateOrProvince)) {
            $json['billingAddress.stateOrProvince']   = $this->billingAddressStateOrProvince;
        }
        if (isset($this->billingAddressStreet)) {
            $json['billingAddress.street']            = $this->billingAddressStreet;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
