<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class ResponseAdditionalDataSwish implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $swishPayerAlias;

    /**
     * Returns Swish Payer Alias.
     * A Swish shopper's telephone number.
     */
    public function getSwishPayerAlias(): ?string
    {
        return $this->swishPayerAlias;
    }

    /**
     * Sets Swish Payer Alias.
     * A Swish shopper's telephone number.
     *
     * @maps swish.payerAlias
     */
    public function setSwishPayerAlias(?string $swishPayerAlias): void
    {
        $this->swishPayerAlias = $swishPayerAlias;
    }

    /**
     * Converts the ResponseAdditionalDataSwish object to a human-readable string representation.
     *
     * @return string The string representation of the ResponseAdditionalDataSwish object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ResponseAdditionalDataSwish', ['swishPayerAlias' => $this->swishPayerAlias]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->swishPayerAlias)) {
            $json['swish.payerAlias'] = $this->swishPayerAlias;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
