<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class ResponseAdditionalDataOpi implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $opiTransToken;

    /**
     * Returns Opi Trans Token.
     * Returned in the response if you included `opi.includeTransToken: true` in an ecommerce payment
     * request. This contains an Oracle Payment Interface token that you can store in your Oracle Opera
     * database to identify tokenized ecommerce transactions. For more information and required settings,
     * see [Oracle Opera](https://docs.adyen.com/plugins/oracle-opera#opi-token-ecommerce).
     */
    public function getOpiTransToken(): ?string
    {
        return $this->opiTransToken;
    }

    /**
     * Sets Opi Trans Token.
     * Returned in the response if you included `opi.includeTransToken: true` in an ecommerce payment
     * request. This contains an Oracle Payment Interface token that you can store in your Oracle Opera
     * database to identify tokenized ecommerce transactions. For more information and required settings,
     * see [Oracle Opera](https://docs.adyen.com/plugins/oracle-opera#opi-token-ecommerce).
     *
     * @maps opi.transToken
     */
    public function setOpiTransToken(?string $opiTransToken): void
    {
        $this->opiTransToken = $opiTransToken;
    }

    /**
     * Converts the ResponseAdditionalDataOpi object to a human-readable string representation.
     *
     * @return string The string representation of the ResponseAdditionalDataOpi object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('ResponseAdditionalDataOpi', ['opiTransToken' => $this->opiTransToken]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->opiTransToken)) {
            $json['opi.transToken'] = $this->opiTransToken;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
