<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The result of the cancellation request.
 *
 * Possible values:
 *
 * * **Success** – Indicates that the balance check was successful.
 * * **NotEnoughBalance** – Commonly indicates that the card did not have enough balance to pay the
 * amount in the request, or that the currency of the balance on the card did not match the currency of
 * the requested amount.
 * * **Failed** – Indicates that the balance check failed.
 */
class ResultCode
{
    public const SUCCESS = 'Success';

    public const NOTENOUGHBALANCE = 'NotEnoughBalance';

    public const FAILED = 'Failed';

    private const _ALL_VALUES = [self::SUCCESS, self::NOTENOUGHBALANCE, self::FAILED];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for ResultCode.");
    }
}
