<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class RiskData implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $clientData;

    /**
     * @var array<string,string>|null
     */
    private $customFields;

    /**
     * @var int|null
     */
    private $fraudOffset;

    /**
     * @var string|null
     */
    private $profileReference;

    /**
     * Returns Client Data.
     * Contains client-side data, like the device fingerprint, cookies, and specific browser settings.
     */
    public function getClientData(): ?string
    {
        return $this->clientData;
    }

    /**
     * Sets Client Data.
     * Contains client-side data, like the device fingerprint, cookies, and specific browser settings.
     *
     * @maps clientData
     */
    public function setClientData(?string $clientData): void
    {
        $this->clientData = $clientData;
    }

    /**
     * Returns Custom Fields.
     * Any custom fields used as part of the input to configured risk rules.
     *
     * @return array<string,string>|null
     */
    public function getCustomFields(): ?array
    {
        return $this->customFields;
    }

    /**
     * Sets Custom Fields.
     * Any custom fields used as part of the input to configured risk rules.
     *
     * @maps customFields
     *
     * @param array<string,string>|null $customFields
     */
    public function setCustomFields(?array $customFields): void
    {
        $this->customFields = $customFields;
    }

    /**
     * Returns Fraud Offset.
     * An integer value that is added to the normal fraud score. The value can be either positive or
     * negative.
     */
    public function getFraudOffset(): ?int
    {
        return $this->fraudOffset;
    }

    /**
     * Sets Fraud Offset.
     * An integer value that is added to the normal fraud score. The value can be either positive or
     * negative.
     *
     * @maps fraudOffset
     */
    public function setFraudOffset(?int $fraudOffset): void
    {
        $this->fraudOffset = $fraudOffset;
    }

    /**
     * Returns Profile Reference.
     * The risk profile to assign to this payment. When left empty, the merchant-level account's default
     * risk profile will be applied.
     */
    public function getProfileReference(): ?string
    {
        return $this->profileReference;
    }

    /**
     * Sets Profile Reference.
     * The risk profile to assign to this payment. When left empty, the merchant-level account's default
     * risk profile will be applied.
     *
     * @maps profileReference
     */
    public function setProfileReference(?string $profileReference): void
    {
        $this->profileReference = $profileReference;
    }

    /**
     * Converts the RiskData object to a human-readable string representation.
     *
     * @return string The string representation of the RiskData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RiskData',
            [
                'clientData' => $this->clientData,
                'customFields' => $this->customFields,
                'fraudOffset' => $this->fraudOffset,
                'profileReference' => $this->profileReference
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->clientData)) {
            $json['clientData']       = $this->clientData;
        }
        if (isset($this->customFields)) {
            $json['customFields']     = $this->customFields;
        }
        if (isset($this->fraudOffset)) {
            $json['fraudOffset']      = $this->fraudOffset;
        }
        if (isset($this->profileReference)) {
            $json['profileReference'] = $this->profileReference;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
