<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

/**
 * The tax info of the shopper
 */
class ShopperTaxInfo2 implements \JsonSerializable
{
    /**
     * @var string
     */
    private $taxId;

    /**
     * @var string
     */
    private $taxIdCountryCode;

    /**
     * @param string $taxId
     * @param string $taxIdCountryCode
     */
    public function __construct(string $taxId, string $taxIdCountryCode)
    {
        $this->taxId = $taxId;
        $this->taxIdCountryCode = $taxIdCountryCode;
    }

    /**
     * Returns Tax Id.
     * The tax-id of the shopper doing the transaction.
     */
    public function getTaxId(): string
    {
        return $this->taxId;
    }

    /**
     * Sets Tax Id.
     * The tax-id of the shopper doing the transaction.
     *
     * @required
     * @maps taxId
     */
    public function setTaxId(string $taxId): void
    {
        $this->taxId = $taxId;
    }

    /**
     * Returns Tax Id Country Code.
     * The country to which the tax-id belongs to.
     */
    public function getTaxIdCountryCode(): string
    {
        return $this->taxIdCountryCode;
    }

    /**
     * Sets Tax Id Country Code.
     * The country to which the tax-id belongs to.
     *
     * @required
     * @maps taxIdCountryCode
     */
    public function setTaxIdCountryCode(string $taxIdCountryCode): void
    {
        $this->taxIdCountryCode = $taxIdCountryCode;
    }

    /**
     * Converts the ShopperTaxInfo2 object to a human-readable string representation.
     *
     * @return string The string representation of the ShopperTaxInfo2 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ShopperTaxInfo2',
            ['taxId' => $this->taxId, 'taxIdCountryCode' => $this->taxIdCountryCode]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['taxId']            = $this->taxId;
        $json['taxIdCountryCode'] = $this->taxIdCountryCode;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
