<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Indicates the status of the SIM card in the payment terminal. Can be updated and received only at
 * terminal level, and only for models that support cellular connectivity.
 *
 * Possible values:
 * * **ACTIVATED**: the SIM card is activated. Cellular connectivity may still need to be enabled on
 * the terminal itself, in the **Network** settings.
 * * **INVENTORY**: the SIM card is not activated. The terminal can't use cellular connectivity.
 */
class SimcardStatus
{
    public const ACTIVATED = 'ACTIVATED';

    public const INVENTORY = 'INVENTORY';

    private const _ALL_VALUES = [self::ACTIVATED, self::INVENTORY];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for SimcardStatus.");
    }
}
