<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class Split implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $account;

    /**
     * @var SplitAmount2|null
     */
    private $amount;

    /**
     * @var string|null
     */
    private $description;

    /**
     * @var string|null
     */
    private $reference;

    /**
     * @var string
     */
    private $type;

    /**
     * @param string $type
     */
    public function __construct(string $type)
    {
        $this->type = $type;
    }

    /**
     * Returns Account.
     * The unique identifier of the account to which the split amount is booked. Required if `type` is
     * **MarketPlace** or **BalanceAccount**.
     *
     * * [Classic Platforms integration](https://docs.adyen.com/classic-platforms): The
     * [`accountCode`](https://docs.adyen.com/api-explorer/Account/latest/post/updateAccount#request-
     * accountCode) of the account to which the split amount is booked.
     * * [Balance Platform](https://docs.adyen.com/adyen-for-platforms-model): The
     * [`balanceAccountId`](https://docs.adyen.com/api-
     * explorer/balanceplatform/latest/get/balanceAccounts/_id_#path-id) of the account to which the split
     * amount is booked.
     */
    public function getAccount(): ?string
    {
        return $this->account;
    }

    /**
     * Sets Account.
     * The unique identifier of the account to which the split amount is booked. Required if `type` is
     * **MarketPlace** or **BalanceAccount**.
     *
     * * [Classic Platforms integration](https://docs.adyen.com/classic-platforms): The
     * [`accountCode`](https://docs.adyen.com/api-explorer/Account/latest/post/updateAccount#request-
     * accountCode) of the account to which the split amount is booked.
     * * [Balance Platform](https://docs.adyen.com/adyen-for-platforms-model): The
     * [`balanceAccountId`](https://docs.adyen.com/api-
     * explorer/balanceplatform/latest/get/balanceAccounts/_id_#path-id) of the account to which the split
     * amount is booked.
     *
     * @maps account
     */
    public function setAccount(?string $account): void
    {
        $this->account = $account;
    }

    /**
     * Returns Amount.
     * The amount of the split item.
     *
     * * Required for all split types in the [Classic Platforms integration](https://docs.adyen.com/classic-
     * platforms).
     * * Required if `type` is **BalanceAccount**, **Commission**, **Surcharge**, **Default**, or **VAT**
     * in your [Balance Platform](https://docs.adyen.com/adyen-for-platforms-model) integration.
     */
    public function getAmount(): ?SplitAmount2
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * The amount of the split item.
     *
     * * Required for all split types in the [Classic Platforms integration](https://docs.adyen.com/classic-
     * platforms).
     * * Required if `type` is **BalanceAccount**, **Commission**, **Surcharge**, **Default**, or **VAT**
     * in your [Balance Platform](https://docs.adyen.com/adyen-for-platforms-model) integration.
     *
     * @maps amount
     */
    public function setAmount(?SplitAmount2 $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Description.
     * Your description for the split item.
     */
    public function getDescription(): ?string
    {
        return $this->description;
    }

    /**
     * Sets Description.
     * Your description for the split item.
     *
     * @maps description
     */
    public function setDescription(?string $description): void
    {
        $this->description = $description;
    }

    /**
     * Returns Reference.
     * Your unique reference for the part of the payment booked to the specified `account`.
     *
     * This is required if `type` is **MarketPlace** ([Classic Platforms integration](https://docs.adyen.
     * com/classic-platforms)) or **BalanceAccount** ([Balance Platform](https://docs.adyen.com/adyen-for-
     * platforms-model)).
     *
     * For the other types, we also recommend providing a **unique** reference so you can reconcile the
     * split and the associated payment in the transaction overview and in the reports.
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     * Your unique reference for the part of the payment booked to the specified `account`.
     *
     * This is required if `type` is **MarketPlace** ([Classic Platforms integration](https://docs.adyen.
     * com/classic-platforms)) or **BalanceAccount** ([Balance Platform](https://docs.adyen.com/adyen-for-
     * platforms-model)).
     *
     * For the other types, we also recommend providing a **unique** reference so you can reconcile the
     * split and the associated payment in the transaction overview and in the reports.
     *
     * @maps reference
     */
    public function setReference(?string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Type.
     * The part of the payment you want to book to the specified `account`.
     *
     * Possible values for the [Balance Platform](https://docs.adyen.com/adyen-for-platforms-model):
     * * **BalanceAccount**: Books part of the payment (specified in `amount`) to the specified `account`.
     * * Transaction fees types that you can book to the specified `account`:
     * * **AcquiringFees**: The aggregated amount of the interchange and scheme fees.
     * * **PaymentFee**: The aggregated amount of all transaction fees.
     * * **AdyenFees**: The aggregated amount of Adyen's commission and markup fees.
     * * **AdyenCommission**: The transaction fees due to Adyen under [blended rates](https://www.adyen.
     * com/knowledge-hub/interchange-fees-explained).
     * * **AdyenMarkup**: The transaction fees due to Adyen under [Interchange ++ pricing](https://www.
     * adyen.com/knowledge-hub/interchange-fees-explained).
     * * **Interchange**: The fees paid to the issuer for each payment made with the card network.
     * * **SchemeFee**: The fees paid to the card scheme for using their network.
     * * **Commission**: Your platform's commission on the payment (specified in `amount`), booked to your
     * liable balance account.
     * * **Remainder**: The amount left over after a currency conversion, booked to the specified `account`.
     * * **Surcharge**: The payment acceptance fee imposed by the card scheme or debit network provider,
     * paid by your user's customer.
     * * **TopUp**: Allows you and your users to top up balance accounts using direct debit, card payments,
     * or other payment methods.
     * * **VAT**: The value-added tax charged on the payment, booked to your platforms liable balance
     * account.
     * * **Default**: In very specific use cases, allows you to book the specified `amount` to the
     * specified `account`. For more information, contact Adyen support.
     *
     * Possible values for the [Classic Platforms integration](https://docs.adyen.com/classic-platforms):
     * **Commission**, **Default**, **MarketPlace**, **PaymentFee**, **VAT**.
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * The part of the payment you want to book to the specified `account`.
     *
     * Possible values for the [Balance Platform](https://docs.adyen.com/adyen-for-platforms-model):
     * * **BalanceAccount**: Books part of the payment (specified in `amount`) to the specified `account`.
     * * Transaction fees types that you can book to the specified `account`:
     * * **AcquiringFees**: The aggregated amount of the interchange and scheme fees.
     * * **PaymentFee**: The aggregated amount of all transaction fees.
     * * **AdyenFees**: The aggregated amount of Adyen's commission and markup fees.
     * * **AdyenCommission**: The transaction fees due to Adyen under [blended rates](https://www.adyen.
     * com/knowledge-hub/interchange-fees-explained).
     * * **AdyenMarkup**: The transaction fees due to Adyen under [Interchange ++ pricing](https://www.
     * adyen.com/knowledge-hub/interchange-fees-explained).
     * * **Interchange**: The fees paid to the issuer for each payment made with the card network.
     * * **SchemeFee**: The fees paid to the card scheme for using their network.
     * * **Commission**: Your platform's commission on the payment (specified in `amount`), booked to your
     * liable balance account.
     * * **Remainder**: The amount left over after a currency conversion, booked to the specified `account`.
     * * **Surcharge**: The payment acceptance fee imposed by the card scheme or debit network provider,
     * paid by your user's customer.
     * * **TopUp**: Allows you and your users to top up balance accounts using direct debit, card payments,
     * or other payment methods.
     * * **VAT**: The value-added tax charged on the payment, booked to your platforms liable balance
     * account.
     * * **Default**: In very specific use cases, allows you to book the specified `amount` to the
     * specified `account`. For more information, contact Adyen support.
     *
     * Possible values for the [Classic Platforms integration](https://docs.adyen.com/classic-platforms):
     * **Commission**, **Default**, **MarketPlace**, **PaymentFee**, **VAT**.
     *
     * @required
     * @maps type
     * @factory \AdyenApIsLib\Models\Type9::checkValue
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the Split object to a human-readable string representation.
     *
     * @return string The string representation of the Split object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Split',
            [
                'account' => $this->account,
                'amount' => $this->amount,
                'description' => $this->description,
                'reference' => $this->reference,
                'type' => $this->type
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->account)) {
            $json['account']     = $this->account;
        }
        if (isset($this->amount)) {
            $json['amount']      = $this->amount;
        }
        if (isset($this->description)) {
            $json['description'] = $this->description;
        }
        if (isset($this->reference)) {
            $json['reference']   = $this->reference;
        }
        $json['type']            = Type9::checkValue($this->type);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
