<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class StandalonePaymentCancelRequest implements \JsonSerializable
{
    /**
     * @var ApplicationInfo1|null
     */
    private $applicationInfo;

    /**
     * @var EnhancedSchemeData1|null
     */
    private $enhancedSchemeData;

    /**
     * @var string
     */
    private $merchantAccount;

    /**
     * @var string
     */
    private $paymentReference;

    /**
     * @var string|null
     */
    private $reference;

    /**
     * @param string $merchantAccount
     * @param string $paymentReference
     */
    public function __construct(string $merchantAccount, string $paymentReference)
    {
        $this->merchantAccount = $merchantAccount;
        $this->paymentReference = $paymentReference;
    }

    /**
     * Returns Application Info.
     * Information about your application. For more details, see [Building Adyen solutions](https://docs.
     * adyen.com/development-resources/building-adyen-solutions).
     */
    public function getApplicationInfo(): ?ApplicationInfo1
    {
        return $this->applicationInfo;
    }

    /**
     * Sets Application Info.
     * Information about your application. For more details, see [Building Adyen solutions](https://docs.
     * adyen.com/development-resources/building-adyen-solutions).
     *
     * @maps applicationInfo
     */
    public function setApplicationInfo(?ApplicationInfo1 $applicationInfo): void
    {
        $this->applicationInfo = $applicationInfo;
    }

    /**
     * Returns Enhanced Scheme Data.
     * Enhanced scheme data that may be required for processing the payment. For example, airline
     * information.
     */
    public function getEnhancedSchemeData(): ?EnhancedSchemeData1
    {
        return $this->enhancedSchemeData;
    }

    /**
     * Sets Enhanced Scheme Data.
     * Enhanced scheme data that may be required for processing the payment. For example, airline
     * information.
     *
     * @maps enhancedSchemeData
     */
    public function setEnhancedSchemeData(?EnhancedSchemeData1 $enhancedSchemeData): void
    {
        $this->enhancedSchemeData = $enhancedSchemeData;
    }

    /**
     * Returns Merchant Account.
     * The merchant account that is used to process the payment.
     */
    public function getMerchantAccount(): string
    {
        return $this->merchantAccount;
    }

    /**
     * Sets Merchant Account.
     * The merchant account that is used to process the payment.
     *
     * @required
     * @maps merchantAccount
     */
    public function setMerchantAccount(string $merchantAccount): void
    {
        $this->merchantAccount = $merchantAccount;
    }

    /**
     * Returns Payment Reference.
     * The [`reference`](https://docs.adyen.com/api-
     * explorer/#/CheckoutService/latest/post/payments__reqParam_reference) of the payment that you want to
     * cancel.
     */
    public function getPaymentReference(): string
    {
        return $this->paymentReference;
    }

    /**
     * Sets Payment Reference.
     * The [`reference`](https://docs.adyen.com/api-
     * explorer/#/CheckoutService/latest/post/payments__reqParam_reference) of the payment that you want to
     * cancel.
     *
     * @required
     * @maps paymentReference
     */
    public function setPaymentReference(string $paymentReference): void
    {
        $this->paymentReference = $paymentReference;
    }

    /**
     * Returns Reference.
     * Your reference for the cancel request. Maximum length: 80 characters.
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     * Your reference for the cancel request. Maximum length: 80 characters.
     *
     * @maps reference
     */
    public function setReference(?string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Converts the StandalonePaymentCancelRequest object to a human-readable string representation.
     *
     * @return string The string representation of the StandalonePaymentCancelRequest object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'StandalonePaymentCancelRequest',
            [
                'applicationInfo' => $this->applicationInfo,
                'enhancedSchemeData' => $this->enhancedSchemeData,
                'merchantAccount' => $this->merchantAccount,
                'paymentReference' => $this->paymentReference,
                'reference' => $this->reference
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->applicationInfo)) {
            $json['applicationInfo']    = $this->applicationInfo;
        }
        if (isset($this->enhancedSchemeData)) {
            $json['enhancedSchemeData'] = $this->enhancedSchemeData;
        }
        $json['merchantAccount']        = $this->merchantAccount;
        $json['paymentReference']       = $this->paymentReference;
        if (isset($this->reference)) {
            $json['reference']          = $this->reference;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
