<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class StandalonePaymentCancelResponse implements \JsonSerializable
{
    /**
     * @var string
     */
    private $merchantAccount;

    /**
     * @var string
     */
    private $paymentReference;

    /**
     * @var string
     */
    private $pspReference;

    /**
     * @var string|null
     */
    private $reference;

    /**
     * @var string
     */
    private $status;

    /**
     * @param string $merchantAccount
     * @param string $paymentReference
     * @param string $pspReference
     */
    public function __construct(string $merchantAccount, string $paymentReference, string $pspReference)
    {
        $this->merchantAccount = $merchantAccount;
        $this->paymentReference = $paymentReference;
        $this->pspReference = $pspReference;
    }

    /**
     * Returns Merchant Account.
     * The merchant account that is used to process the payment.
     */
    public function getMerchantAccount(): string
    {
        return $this->merchantAccount;
    }

    /**
     * Sets Merchant Account.
     * The merchant account that is used to process the payment.
     *
     * @required
     * @maps merchantAccount
     */
    public function setMerchantAccount(string $merchantAccount): void
    {
        $this->merchantAccount = $merchantAccount;
    }

    /**
     * Returns Payment Reference.
     * The [`reference`](https://docs.adyen.com/api-
     * explorer/#/CheckoutService/latest/post/payments__reqParam_reference) of the payment to cancel.
     */
    public function getPaymentReference(): string
    {
        return $this->paymentReference;
    }

    /**
     * Sets Payment Reference.
     * The [`reference`](https://docs.adyen.com/api-
     * explorer/#/CheckoutService/latest/post/payments__reqParam_reference) of the payment to cancel.
     *
     * @required
     * @maps paymentReference
     */
    public function setPaymentReference(string $paymentReference): void
    {
        $this->paymentReference = $paymentReference;
    }

    /**
     * Returns Psp Reference.
     * Adyen's 16-character reference associated with the cancel request.
     */
    public function getPspReference(): string
    {
        return $this->pspReference;
    }

    /**
     * Sets Psp Reference.
     * Adyen's 16-character reference associated with the cancel request.
     *
     * @required
     * @maps pspReference
     */
    public function setPspReference(string $pspReference): void
    {
        $this->pspReference = $pspReference;
    }

    /**
     * Returns Reference.
     * Your reference for the cancel request.
     */
    public function getReference(): ?string
    {
        return $this->reference;
    }

    /**
     * Sets Reference.
     * Your reference for the cancel request.
     *
     * @maps reference
     */
    public function setReference(?string $reference): void
    {
        $this->reference = $reference;
    }

    /**
     * Returns Status.
     * The status of your request. This will always have the value **received**.
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The status of your request. This will always have the value **received**.
     *
     * @maps status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Converts the StandalonePaymentCancelResponse object to a human-readable string representation.
     *
     * @return string The string representation of the StandalonePaymentCancelResponse object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'StandalonePaymentCancelResponse',
            [
                'merchantAccount' => $this->merchantAccount,
                'paymentReference' => $this->paymentReference,
                'pspReference' => $this->pspReference,
                'reference' => $this->reference,
                'status' => $this->status
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['merchantAccount']  = $this->merchantAccount;
        $json['paymentReference'] = $this->paymentReference;
        $json['pspReference']     = $this->pspReference;
        if (isset($this->reference)) {
            $json['reference']    = $this->reference;
        }
        $json['status']           = $this->status;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
