<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The status of the store. Possible values are:
 *
 * - **active**. This value is assigned automatically when a store is created.
 * - **inactive**. The terminals under the store are blocked from accepting new transactions, but
 * capturing outstanding transactions is still possible.
 * - **closed**. This status is irreversible. The terminals under the store are reassigned to the
 * merchant inventory.
 */
class Status11
{
    public const ACTIVE = 'active';

    public const CLOSED = 'closed';

    public const INACTIVE = 'inactive';

    private const _ALL_VALUES = [self::ACTIVE, self::CLOSED, self::INACTIVE];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for Status11.");
    }
}
