<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * The status of the reassignment. Possible values:
 * * `reassignmentInProgress`: the terminal was boarded and is now scheduled to remove the
 * configuration. Wait for the terminal to synchronize with the Adyen platform.
 * * `deployed`: the terminal is deployed and reassigned.
 * * `inventory`: the terminal is in inventory and cannot process transactions.
 * * `boarded`: the terminal is boarded to a store, or a merchant account representing a store, and
 * can process transactions.
 */
class Status21
{
    public const BOARDED = 'boarded';

    public const DEPLOYED = 'deployed';

    public const INVENTORY = 'inventory';

    public const REASSIGNMENTINPROGRESS = 'reassignmentInProgress';

    private const _ALL_VALUES = [self::BOARDED, self::DEPLOYED, self::INVENTORY, self::REASSIGNMENTINPROGRESS];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for Status21.");
    }
}
