<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class TerminalConnectivityWifi implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $ipAddress;

    /**
     * @var string|null
     */
    private $macAddress;

    /**
     * @var string|null
     */
    private $ssid;

    /**
     * Returns Ip Address.
     * The terminal's IP address in the Wi-Fi network.
     */
    public function getIpAddress(): ?string
    {
        return $this->ipAddress;
    }

    /**
     * Sets Ip Address.
     * The terminal's IP address in the Wi-Fi network.
     *
     * @maps ipAddress
     */
    public function setIpAddress(?string $ipAddress): void
    {
        $this->ipAddress = $ipAddress;
    }

    /**
     * Returns Mac Address.
     * The terminal's MAC address in the Wi-Fi network.
     */
    public function getMacAddress(): ?string
    {
        return $this->macAddress;
    }

    /**
     * Sets Mac Address.
     * The terminal's MAC address in the Wi-Fi network.
     *
     * @maps macAddress
     */
    public function setMacAddress(?string $macAddress): void
    {
        $this->macAddress = $macAddress;
    }

    /**
     * Returns Ssid.
     * The SSID of the Wi-Fi network that the terminal is connected to.
     */
    public function getSsid(): ?string
    {
        return $this->ssid;
    }

    /**
     * Sets Ssid.
     * The SSID of the Wi-Fi network that the terminal is connected to.
     *
     * @maps ssid
     */
    public function setSsid(?string $ssid): void
    {
        $this->ssid = $ssid;
    }

    /**
     * Converts the TerminalConnectivityWifi object to a human-readable string representation.
     *
     * @return string The string representation of the TerminalConnectivityWifi object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TerminalConnectivityWifi',
            ['ipAddress' => $this->ipAddress, 'macAddress' => $this->macAddress, 'ssid' => $this->ssid]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->ipAddress)) {
            $json['ipAddress']  = $this->ipAddress;
        }
        if (isset($this->macAddress)) {
            $json['macAddress'] = $this->macAddress;
        }
        if (isset($this->ssid)) {
            $json['ssid']       = $this->ssid;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
