<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class TerminalInstructions implements \JsonSerializable
{
    /**
     * @var bool|null
     */
    private $adyenAppRestart;

    /**
     * Returns Adyen App Restart.
     * Indicates whether the Adyen app on the payment terminal restarts automatically when the
     * configuration is updated.
     */
    public function getAdyenAppRestart(): ?bool
    {
        return $this->adyenAppRestart;
    }

    /**
     * Sets Adyen App Restart.
     * Indicates whether the Adyen app on the payment terminal restarts automatically when the
     * configuration is updated.
     *
     * @maps adyenAppRestart
     */
    public function setAdyenAppRestart(?bool $adyenAppRestart): void
    {
        $this->adyenAppRestart = $adyenAppRestart;
    }

    /**
     * Converts the TerminalInstructions object to a human-readable string representation.
     *
     * @return string The string representation of the TerminalInstructions object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('TerminalInstructions', ['adyenAppRestart' => $this->adyenAppRestart]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->adyenAppRestart)) {
            $json['adyenAppRestart'] = $this->adyenAppRestart;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
