<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

/**
 * Result of the 3D Secure 2 authentication.
 */
class ThreeDs2Result1 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $authenticationValue;

    /**
     * @var string|null
     */
    private $cavvAlgorithm;

    /**
     * @var string|null
     */
    private $challengeCancel;

    /**
     * @var string|null
     */
    private $dsTransId;

    /**
     * @var string|null
     */
    private $eci;

    /**
     * @var string|null
     */
    private $exemptionIndicator;

    /**
     * @var string|null
     */
    private $messageVersion;

    /**
     * @var string|null
     */
    private $riskScore;

    /**
     * @var string|null
     */
    private $threeDsRequestorChallengeInd;

    /**
     * @var string|null
     */
    private $threeDsServerTransId;

    /**
     * @var string|null
     */
    private $timestamp;

    /**
     * @var string|null
     */
    private $transStatus;

    /**
     * @var string|null
     */
    private $transStatusReason;

    /**
     * @var string|null
     */
    private $whiteListStatus;

    /**
     * Returns Authentication Value.
     * The `authenticationValue` value as defined in the 3D Secure 2 specification.
     */
    public function getAuthenticationValue(): ?string
    {
        return $this->authenticationValue;
    }

    /**
     * Sets Authentication Value.
     * The `authenticationValue` value as defined in the 3D Secure 2 specification.
     *
     * @maps authenticationValue
     */
    public function setAuthenticationValue(?string $authenticationValue): void
    {
        $this->authenticationValue = $authenticationValue;
    }

    /**
     * Returns Cavv Algorithm.
     * The algorithm used by the ACS to calculate the authentication value, only for Cartes Bancaires
     * integrations.
     */
    public function getCavvAlgorithm(): ?string
    {
        return $this->cavvAlgorithm;
    }

    /**
     * Sets Cavv Algorithm.
     * The algorithm used by the ACS to calculate the authentication value, only for Cartes Bancaires
     * integrations.
     *
     * @maps cavvAlgorithm
     */
    public function setCavvAlgorithm(?string $cavvAlgorithm): void
    {
        $this->cavvAlgorithm = $cavvAlgorithm;
    }

    /**
     * Returns Challenge Cancel.
     * Indicator informing the Access Control Server (ACS) and the Directory Server (DS) that the
     * authentication has been cancelled. For possible values, refer to [3D Secure API reference](https:
     * //docs.adyen.com/online-payments/3d-secure/api-reference#mpidata).
     */
    public function getChallengeCancel(): ?string
    {
        return $this->challengeCancel;
    }

    /**
     * Sets Challenge Cancel.
     * Indicator informing the Access Control Server (ACS) and the Directory Server (DS) that the
     * authentication has been cancelled. For possible values, refer to [3D Secure API reference](https:
     * //docs.adyen.com/online-payments/3d-secure/api-reference#mpidata).
     *
     * @maps challengeCancel
     * @factory \AdyenApIsLib\Models\ChallengeCancel::checkValue
     */
    public function setChallengeCancel(?string $challengeCancel): void
    {
        $this->challengeCancel = $challengeCancel;
    }

    /**
     * Returns Ds Trans Id.
     * The `dsTransID` value as defined in the 3D Secure 2 specification.
     */
    public function getDsTransId(): ?string
    {
        return $this->dsTransId;
    }

    /**
     * Sets Ds Trans Id.
     * The `dsTransID` value as defined in the 3D Secure 2 specification.
     *
     * @maps dsTransID
     */
    public function setDsTransId(?string $dsTransId): void
    {
        $this->dsTransId = $dsTransId;
    }

    /**
     * Returns Eci.
     * The `eci` value as defined in the 3D Secure 2 specification.
     */
    public function getEci(): ?string
    {
        return $this->eci;
    }

    /**
     * Sets Eci.
     * The `eci` value as defined in the 3D Secure 2 specification.
     *
     * @maps eci
     */
    public function setEci(?string $eci): void
    {
        $this->eci = $eci;
    }

    /**
     * Returns Exemption Indicator.
     * Indicates the exemption type that was applied by the issuer to the authentication, if exemption
     * applied.
     * Allowed values:
     * * `lowValue`
     * * `secureCorporate`
     * * `trustedBeneficiary`
     * * `transactionRiskAnalysis`
     */
    public function getExemptionIndicator(): ?string
    {
        return $this->exemptionIndicator;
    }

    /**
     * Sets Exemption Indicator.
     * Indicates the exemption type that was applied by the issuer to the authentication, if exemption
     * applied.
     * Allowed values:
     * * `lowValue`
     * * `secureCorporate`
     * * `trustedBeneficiary`
     * * `transactionRiskAnalysis`
     *
     * @maps exemptionIndicator
     * @factory \AdyenApIsLib\Models\ExemptionIndicator::checkValue
     */
    public function setExemptionIndicator(?string $exemptionIndicator): void
    {
        $this->exemptionIndicator = $exemptionIndicator;
    }

    /**
     * Returns Message Version.
     * The `messageVersion` value as defined in the 3D Secure 2 specification.
     */
    public function getMessageVersion(): ?string
    {
        return $this->messageVersion;
    }

    /**
     * Sets Message Version.
     * The `messageVersion` value as defined in the 3D Secure 2 specification.
     *
     * @maps messageVersion
     */
    public function setMessageVersion(?string $messageVersion): void
    {
        $this->messageVersion = $messageVersion;
    }

    /**
     * Returns Risk Score.
     * Risk score calculated by Cartes Bancaires Directory Server (DS).
     */
    public function getRiskScore(): ?string
    {
        return $this->riskScore;
    }

    /**
     * Sets Risk Score.
     * Risk score calculated by Cartes Bancaires Directory Server (DS).
     *
     * @maps riskScore
     */
    public function setRiskScore(?string $riskScore): void
    {
        $this->riskScore = $riskScore;
    }

    /**
     * Returns Three Ds Requestor Challenge Ind.
     * Indicates whether a challenge is requested for this transaction. Possible values:
     * * **01** — No preference
     * * **02** — No challenge requested
     * * **03** — Challenge requested (3DS Requestor preference)
     * * **04** — Challenge requested (Mandate)
     * * **05** — No challenge (transactional risk analysis is already performed)
     * * **06** — Data Only
     */
    public function getThreeDsRequestorChallengeInd(): ?string
    {
        return $this->threeDsRequestorChallengeInd;
    }

    /**
     * Sets Three Ds Requestor Challenge Ind.
     * Indicates whether a challenge is requested for this transaction. Possible values:
     * * **01** — No preference
     * * **02** — No challenge requested
     * * **03** — Challenge requested (3DS Requestor preference)
     * * **04** — Challenge requested (Mandate)
     * * **05** — No challenge (transactional risk analysis is already performed)
     * * **06** — Data Only
     *
     * @maps threeDSRequestorChallengeInd
     * @factory \AdyenApIsLib\Models\ThreeDsRequestorChallengeInd::checkValue
     */
    public function setThreeDsRequestorChallengeInd(?string $threeDsRequestorChallengeInd): void
    {
        $this->threeDsRequestorChallengeInd = $threeDsRequestorChallengeInd;
    }

    /**
     * Returns Three Ds Server Trans Id.
     * The `threeDSServerTransID` value as defined in the 3D Secure 2 specification.
     */
    public function getThreeDsServerTransId(): ?string
    {
        return $this->threeDsServerTransId;
    }

    /**
     * Sets Three Ds Server Trans Id.
     * The `threeDSServerTransID` value as defined in the 3D Secure 2 specification.
     *
     * @maps threeDSServerTransID
     */
    public function setThreeDsServerTransId(?string $threeDsServerTransId): void
    {
        $this->threeDsServerTransId = $threeDsServerTransId;
    }

    /**
     * Returns Timestamp.
     * The `timestamp` value of the 3D Secure 2 authentication.
     */
    public function getTimestamp(): ?string
    {
        return $this->timestamp;
    }

    /**
     * Sets Timestamp.
     * The `timestamp` value of the 3D Secure 2 authentication.
     *
     * @maps timestamp
     */
    public function setTimestamp(?string $timestamp): void
    {
        $this->timestamp = $timestamp;
    }

    /**
     * Returns Trans Status.
     * The `transStatus` value as defined in the 3D Secure 2 specification.
     */
    public function getTransStatus(): ?string
    {
        return $this->transStatus;
    }

    /**
     * Sets Trans Status.
     * The `transStatus` value as defined in the 3D Secure 2 specification.
     *
     * @maps transStatus
     */
    public function setTransStatus(?string $transStatus): void
    {
        $this->transStatus = $transStatus;
    }

    /**
     * Returns Trans Status Reason.
     * Provides information on why the `transStatus` field has the specified value. For possible values,
     * refer to [our docs](https://docs.adyen.com/online-payments/3d-secure/api-reference#possible-
     * transstatusreason-values).
     */
    public function getTransStatusReason(): ?string
    {
        return $this->transStatusReason;
    }

    /**
     * Sets Trans Status Reason.
     * Provides information on why the `transStatus` field has the specified value. For possible values,
     * refer to [our docs](https://docs.adyen.com/online-payments/3d-secure/api-reference#possible-
     * transstatusreason-values).
     *
     * @maps transStatusReason
     */
    public function setTransStatusReason(?string $transStatusReason): void
    {
        $this->transStatusReason = $transStatusReason;
    }

    /**
     * Returns White List Status.
     * The `whiteListStatus` value as defined in the 3D Secure 2 specification.
     */
    public function getWhiteListStatus(): ?string
    {
        return $this->whiteListStatus;
    }

    /**
     * Sets White List Status.
     * The `whiteListStatus` value as defined in the 3D Secure 2 specification.
     *
     * @maps whiteListStatus
     */
    public function setWhiteListStatus(?string $whiteListStatus): void
    {
        $this->whiteListStatus = $whiteListStatus;
    }

    /**
     * Converts the ThreeDs2Result1 object to a human-readable string representation.
     *
     * @return string The string representation of the ThreeDs2Result1 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ThreeDs2Result1',
            [
                'authenticationValue' => $this->authenticationValue,
                'cavvAlgorithm' => $this->cavvAlgorithm,
                'challengeCancel' => $this->challengeCancel,
                'dsTransId' => $this->dsTransId,
                'eci' => $this->eci,
                'exemptionIndicator' => $this->exemptionIndicator,
                'messageVersion' => $this->messageVersion,
                'riskScore' => $this->riskScore,
                'threeDsRequestorChallengeInd' => $this->threeDsRequestorChallengeInd,
                'threeDsServerTransId' => $this->threeDsServerTransId,
                'timestamp' => $this->timestamp,
                'transStatus' => $this->transStatus,
                'transStatusReason' => $this->transStatusReason,
                'whiteListStatus' => $this->whiteListStatus
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->authenticationValue)) {
            $json['authenticationValue']          = $this->authenticationValue;
        }
        if (isset($this->cavvAlgorithm)) {
            $json['cavvAlgorithm']                = $this->cavvAlgorithm;
        }
        if (isset($this->challengeCancel)) {
            $json['challengeCancel']              = ChallengeCancel::checkValue($this->challengeCancel);
        }
        if (isset($this->dsTransId)) {
            $json['dsTransID']                    = $this->dsTransId;
        }
        if (isset($this->eci)) {
            $json['eci']                          = $this->eci;
        }
        if (isset($this->exemptionIndicator)) {
            $json['exemptionIndicator']           = ExemptionIndicator::checkValue($this->exemptionIndicator);
        }
        if (isset($this->messageVersion)) {
            $json['messageVersion']               = $this->messageVersion;
        }
        if (isset($this->riskScore)) {
            $json['riskScore']                    = $this->riskScore;
        }
        if (isset($this->threeDsRequestorChallengeInd)) {
            $json['threeDSRequestorChallengeInd'] =
                ThreeDsRequestorChallengeInd::checkValue(
                    $this->threeDsRequestorChallengeInd
                );
        }
        if (isset($this->threeDsServerTransId)) {
            $json['threeDSServerTransID']         = $this->threeDsServerTransId;
        }
        if (isset($this->timestamp)) {
            $json['timestamp']                    = $this->timestamp;
        }
        if (isset($this->transStatus)) {
            $json['transStatus']                  = $this->transStatus;
        }
        if (isset($this->transStatusReason)) {
            $json['transStatusReason']            = $this->transStatusReason;
        }
        if (isset($this->whiteListStatus)) {
            $json['whiteListStatus']              = $this->whiteListStatus;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
