<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class ThreeDSecureData implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $authenticationResponse;

    /**
     * @var string|null
     */
    private $cavv;

    /**
     * @var string|null
     */
    private $cavvAlgorithm;

    /**
     * @var string|null
     */
    private $challengeCancel;

    /**
     * @var string|null
     */
    private $directoryResponse;

    /**
     * @var string|null
     */
    private $dsTransId;

    /**
     * @var string|null
     */
    private $eci;

    /**
     * @var string|null
     */
    private $riskScore;

    /**
     * @var string|null
     */
    private $threeDsVersion;

    /**
     * @var string|null
     */
    private $tokenAuthenticationVerificationValue;

    /**
     * @var string|null
     */
    private $transStatusReason;

    /**
     * @var string|null
     */
    private $xid;

    /**
     * Returns Authentication Response.
     * In 3D Secure 2, this is the `transStatus` from the challenge result. If the transaction was
     * frictionless, omit this parameter.
     */
    public function getAuthenticationResponse(): ?string
    {
        return $this->authenticationResponse;
    }

    /**
     * Sets Authentication Response.
     * In 3D Secure 2, this is the `transStatus` from the challenge result. If the transaction was
     * frictionless, omit this parameter.
     *
     * @maps authenticationResponse
     * @factory \AdyenApIsLib\Models\AuthenticationResponse::checkValue
     */
    public function setAuthenticationResponse(?string $authenticationResponse): void
    {
        $this->authenticationResponse = $authenticationResponse;
    }

    /**
     * Returns Cavv.
     * The cardholder authentication value (base64 encoded, 20 bytes in a decoded form).
     */
    public function getCavv(): ?string
    {
        return $this->cavv;
    }

    /**
     * Sets Cavv.
     * The cardholder authentication value (base64 encoded, 20 bytes in a decoded form).
     *
     * @maps cavv
     */
    public function setCavv(?string $cavv): void
    {
        $this->cavv = $cavv;
    }

    /**
     * Returns Cavv Algorithm.
     * The CAVV algorithm used. Include this only for 3D Secure 1.
     */
    public function getCavvAlgorithm(): ?string
    {
        return $this->cavvAlgorithm;
    }

    /**
     * Sets Cavv Algorithm.
     * The CAVV algorithm used. Include this only for 3D Secure 1.
     *
     * @maps cavvAlgorithm
     */
    public function setCavvAlgorithm(?string $cavvAlgorithm): void
    {
        $this->cavvAlgorithm = $cavvAlgorithm;
    }

    /**
     * Returns Challenge Cancel.
     * Indicator informing the Access Control Server (ACS) and the Directory Server (DS) that the
     * authentication has been cancelled. For possible values, refer to [3D Secure API reference](https:
     * //docs.adyen.com/online-payments/3d-secure/api-reference#mpidata).
     */
    public function getChallengeCancel(): ?string
    {
        return $this->challengeCancel;
    }

    /**
     * Sets Challenge Cancel.
     * Indicator informing the Access Control Server (ACS) and the Directory Server (DS) that the
     * authentication has been cancelled. For possible values, refer to [3D Secure API reference](https:
     * //docs.adyen.com/online-payments/3d-secure/api-reference#mpidata).
     *
     * @maps challengeCancel
     * @factory \AdyenApIsLib\Models\ChallengeCancel::checkValue
     */
    public function setChallengeCancel(?string $challengeCancel): void
    {
        $this->challengeCancel = $challengeCancel;
    }

    /**
     * Returns Directory Response.
     * In 3D Secure 2, this is the `transStatus` from the `ARes`.
     */
    public function getDirectoryResponse(): ?string
    {
        return $this->directoryResponse;
    }

    /**
     * Sets Directory Response.
     * In 3D Secure 2, this is the `transStatus` from the `ARes`.
     *
     * @maps directoryResponse
     * @factory \AdyenApIsLib\Models\DirectoryResponse::checkValue
     */
    public function setDirectoryResponse(?string $directoryResponse): void
    {
        $this->directoryResponse = $directoryResponse;
    }

    /**
     * Returns Ds Trans Id.
     * Supported for 3D Secure 2. The unique transaction identifier assigned by the Directory Server (DS)
     * to identify a single transaction.
     */
    public function getDsTransId(): ?string
    {
        return $this->dsTransId;
    }

    /**
     * Sets Ds Trans Id.
     * Supported for 3D Secure 2. The unique transaction identifier assigned by the Directory Server (DS)
     * to identify a single transaction.
     *
     * @maps dsTransID
     */
    public function setDsTransId(?string $dsTransId): void
    {
        $this->dsTransId = $dsTransId;
    }

    /**
     * Returns Eci.
     * The electronic commerce indicator.
     */
    public function getEci(): ?string
    {
        return $this->eci;
    }

    /**
     * Sets Eci.
     * The electronic commerce indicator.
     *
     * @maps eci
     */
    public function setEci(?string $eci): void
    {
        $this->eci = $eci;
    }

    /**
     * Returns Risk Score.
     * Risk score calculated by Directory Server (DS). Required for Cartes Bancaires integrations.
     */
    public function getRiskScore(): ?string
    {
        return $this->riskScore;
    }

    /**
     * Sets Risk Score.
     * Risk score calculated by Directory Server (DS). Required for Cartes Bancaires integrations.
     *
     * @maps riskScore
     */
    public function setRiskScore(?string $riskScore): void
    {
        $this->riskScore = $riskScore;
    }

    /**
     * Returns Three Ds Version.
     * The version of the 3D Secure protocol.
     */
    public function getThreeDsVersion(): ?string
    {
        return $this->threeDsVersion;
    }

    /**
     * Sets Three Ds Version.
     * The version of the 3D Secure protocol.
     *
     * @maps threeDSVersion
     */
    public function setThreeDsVersion(?string $threeDsVersion): void
    {
        $this->threeDsVersion = $threeDsVersion;
    }

    /**
     * Returns Token Authentication Verification Value.
     * Network token authentication verification value (TAVV). The network token cryptogram.
     */
    public function getTokenAuthenticationVerificationValue(): ?string
    {
        return $this->tokenAuthenticationVerificationValue;
    }

    /**
     * Sets Token Authentication Verification Value.
     * Network token authentication verification value (TAVV). The network token cryptogram.
     *
     * @maps tokenAuthenticationVerificationValue
     */
    public function setTokenAuthenticationVerificationValue(?string $tokenAuthenticationVerificationValue): void
    {
        $this->tokenAuthenticationVerificationValue = $tokenAuthenticationVerificationValue;
    }

    /**
     * Returns Trans Status Reason.
     * Provides information on why the `transStatus` field has the specified value. For possible values,
     * refer to [our docs](https://docs.adyen.com/online-payments/3d-secure/api-reference#possible-
     * transstatusreason-values).
     */
    public function getTransStatusReason(): ?string
    {
        return $this->transStatusReason;
    }

    /**
     * Sets Trans Status Reason.
     * Provides information on why the `transStatus` field has the specified value. For possible values,
     * refer to [our docs](https://docs.adyen.com/online-payments/3d-secure/api-reference#possible-
     * transstatusreason-values).
     *
     * @maps transStatusReason
     */
    public function setTransStatusReason(?string $transStatusReason): void
    {
        $this->transStatusReason = $transStatusReason;
    }

    /**
     * Returns Xid.
     * Supported for 3D Secure 1. The transaction identifier (Base64-encoded, 20 bytes in a decoded form).
     */
    public function getXid(): ?string
    {
        return $this->xid;
    }

    /**
     * Sets Xid.
     * Supported for 3D Secure 1. The transaction identifier (Base64-encoded, 20 bytes in a decoded form).
     *
     * @maps xid
     */
    public function setXid(?string $xid): void
    {
        $this->xid = $xid;
    }

    /**
     * Converts the ThreeDSecureData object to a human-readable string representation.
     *
     * @return string The string representation of the ThreeDSecureData object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ThreeDSecureData',
            [
                'authenticationResponse' => $this->authenticationResponse,
                'cavv' => $this->cavv,
                'cavvAlgorithm' => $this->cavvAlgorithm,
                'challengeCancel' => $this->challengeCancel,
                'directoryResponse' => $this->directoryResponse,
                'dsTransId' => $this->dsTransId,
                'eci' => $this->eci,
                'riskScore' => $this->riskScore,
                'threeDsVersion' => $this->threeDsVersion,
                'tokenAuthenticationVerificationValue' => $this->tokenAuthenticationVerificationValue,
                'transStatusReason' => $this->transStatusReason,
                'xid' => $this->xid
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->authenticationResponse)) {
            $json['authenticationResponse']               =
                AuthenticationResponse::checkValue(
                    $this->authenticationResponse
                );
        }
        if (isset($this->cavv)) {
            $json['cavv']                                 = $this->cavv;
        }
        if (isset($this->cavvAlgorithm)) {
            $json['cavvAlgorithm']                        = $this->cavvAlgorithm;
        }
        if (isset($this->challengeCancel)) {
            $json['challengeCancel']                      = ChallengeCancel::checkValue($this->challengeCancel);
        }
        if (isset($this->directoryResponse)) {
            $json['directoryResponse']                    = DirectoryResponse::checkValue($this->directoryResponse);
        }
        if (isset($this->dsTransId)) {
            $json['dsTransID']                            = $this->dsTransId;
        }
        if (isset($this->eci)) {
            $json['eci']                                  = $this->eci;
        }
        if (isset($this->riskScore)) {
            $json['riskScore']                            = $this->riskScore;
        }
        if (isset($this->threeDsVersion)) {
            $json['threeDSVersion']                       = $this->threeDsVersion;
        }
        if (isset($this->tokenAuthenticationVerificationValue)) {
            $json['tokenAuthenticationVerificationValue'] = $this->tokenAuthenticationVerificationValue;
        }
        if (isset($this->transStatusReason)) {
            $json['transStatusReason']                    = $this->transStatusReason;
        }
        if (isset($this->xid)) {
            $json['xid']                                  = $this->xid;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
