<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class ThreeDs2RequestFields implements \JsonSerializable
{
    /**
     * @var AcctInfo1|null
     */
    private $acctInfo;

    /**
     * @var string|null
     */
    private $acctType;

    /**
     * @var string|null
     */
    private $acquirerBin;

    /**
     * @var string|null
     */
    private $acquirerMerchantId;

    /**
     * @var string|null
     */
    private $addrMatch;

    /**
     * @var bool|null
     */
    private $authenticationOnly = false;

    /**
     * @var string|null
     */
    private $challengeIndicator;

    /**
     * @var DeviceRenderOptions2|null
     */
    private $deviceRenderOptions;

    /**
     * @var Phone3|null
     */
    private $homePhone;

    /**
     * @var string|null
     */
    private $mcc;

    /**
     * @var string|null
     */
    private $merchantName;

    /**
     * @var string|null
     */
    private $messageVersion;

    /**
     * @var Phone1|null
     */
    private $mobilePhone;

    /**
     * @var string|null
     */
    private $notificationUrl;

    /**
     * @var bool|null
     */
    private $payTokenInd;

    /**
     * @var string|null
     */
    private $paymentAuthenticationUseCase;

    /**
     * @var string|null
     */
    private $purchaseInstalData;

    /**
     * @var string|null
     */
    private $recurringExpiry;

    /**
     * @var string|null
     */
    private $recurringFrequency;

    /**
     * @var string|null
     */
    private $sdkAppId;

    /**
     * @var SdkEphemPubKey1|null
     */
    private $sdkEphemPubKey;

    /**
     * @var int|null
     */
    private $sdkMaxTimeout = 60;

    /**
     * @var string|null
     */
    private $sdkReferenceNumber;

    /**
     * @var string|null
     */
    private $sdkTransId;

    /**
     * @var string|null
     */
    private $threeDsCompInd;

    /**
     * @var string|null
     */
    private $threeDsRequestorAuthenticationInd;

    /**
     * @var ThreeDsRequestorAuthenticationInfo1|null
     */
    private $threeDsRequestorAuthenticationInfo;

    /**
     * @var string|null
     */
    private $threeDsRequestorChallengeInd;

    /**
     * @var string|null
     */
    private $threeDsRequestorId;

    /**
     * @var string|null
     */
    private $threeDsRequestorName;

    /**
     * @var ThreeDsRequestorPriorAuthenticationInfo1|null
     */
    private $threeDsRequestorPriorAuthenticationInfo;

    /**
     * @var string|null
     */
    private $threeDsRequestorUrl;

    /**
     * @var string|null
     */
    private $transType;

    /**
     * @var string|null
     */
    private $transactionType;

    /**
     * @var string|null
     */
    private $whiteListStatus;

    /**
     * @var Phone2|null
     */
    private $workPhone;

    /**
     * Returns Acct Info.
     * Additional information about the cardholder’s account provided by the 3DS Requestor.
     */
    public function getAcctInfo(): ?AcctInfo1
    {
        return $this->acctInfo;
    }

    /**
     * Sets Acct Info.
     * Additional information about the cardholder’s account provided by the 3DS Requestor.
     *
     * @maps acctInfo
     */
    public function setAcctInfo(?AcctInfo1 $acctInfo): void
    {
        $this->acctInfo = $acctInfo;
    }

    /**
     * Returns Acct Type.
     * Indicates the type of account. For example, for a multi-account card product. Length: 2 characters.
     * Allowed values:
     * * **01** — Not applicable
     * * **02** — Credit
     * * **03** — Debit
     */
    public function getAcctType(): ?string
    {
        return $this->acctType;
    }

    /**
     * Sets Acct Type.
     * Indicates the type of account. For example, for a multi-account card product. Length: 2 characters.
     * Allowed values:
     * * **01** — Not applicable
     * * **02** — Credit
     * * **03** — Debit
     *
     * @maps acctType
     * @factory \AdyenApIsLib\Models\AcctType::checkValue
     */
    public function setAcctType(?string $acctType): void
    {
        $this->acctType = $acctType;
    }

    /**
     * Returns Acquirer Bin.
     * Required for [authentication-only integration](https://docs.adyen.com/online-payments/3d-
     * secure/other-3ds-flows/authentication-only). The acquiring BIN enrolled for 3D Secure 2. This string
     * should match the value that you will use in the authorisation. Use 123456 on the Test platform.
     */
    public function getAcquirerBin(): ?string
    {
        return $this->acquirerBin;
    }

    /**
     * Sets Acquirer Bin.
     * Required for [authentication-only integration](https://docs.adyen.com/online-payments/3d-
     * secure/other-3ds-flows/authentication-only). The acquiring BIN enrolled for 3D Secure 2. This string
     * should match the value that you will use in the authorisation. Use 123456 on the Test platform.
     *
     * @maps acquirerBIN
     */
    public function setAcquirerBin(?string $acquirerBin): void
    {
        $this->acquirerBin = $acquirerBin;
    }

    /**
     * Returns Acquirer Merchant Id.
     * Required for [authentication-only integration](https://docs.adyen.com/online-payments/3d-
     * secure/other-3ds-flows/authentication-only). The merchantId that is enrolled for 3D Secure 2 by the
     * merchant's acquirer. This string should match the value that you will use in the authorisation. Use
     * 123456 on the Test platform.
     */
    public function getAcquirerMerchantId(): ?string
    {
        return $this->acquirerMerchantId;
    }

    /**
     * Sets Acquirer Merchant Id.
     * Required for [authentication-only integration](https://docs.adyen.com/online-payments/3d-
     * secure/other-3ds-flows/authentication-only). The merchantId that is enrolled for 3D Secure 2 by the
     * merchant's acquirer. This string should match the value that you will use in the authorisation. Use
     * 123456 on the Test platform.
     *
     * @maps acquirerMerchantID
     */
    public function setAcquirerMerchantId(?string $acquirerMerchantId): void
    {
        $this->acquirerMerchantId = $acquirerMerchantId;
    }

    /**
     * Returns Addr Match.
     * Indicates whether the cardholder shipping Address and cardholder billing address are the same.
     * Allowed values:
     * * **Y** — Shipping Address matches Billing Address.
     * * **N** — Shipping Address does not match Billing Address.
     */
    public function getAddrMatch(): ?string
    {
        return $this->addrMatch;
    }

    /**
     * Sets Addr Match.
     * Indicates whether the cardholder shipping Address and cardholder billing address are the same.
     * Allowed values:
     * * **Y** — Shipping Address matches Billing Address.
     * * **N** — Shipping Address does not match Billing Address.
     *
     * @maps addrMatch
     * @factory \AdyenApIsLib\Models\AddrMatch1::checkValue
     */
    public function setAddrMatch(?string $addrMatch): void
    {
        $this->addrMatch = $addrMatch;
    }

    /**
     * Returns Authentication Only.
     * If set to true, you will only perform the [3D Secure 2 authentication](https://docs.adyen.com/online-
     * payments/3d-secure/other-3ds-flows/authentication-only), and not the payment authorisation.
     */
    public function getAuthenticationOnly(): ?bool
    {
        return $this->authenticationOnly;
    }

    /**
     * Sets Authentication Only.
     * If set to true, you will only perform the [3D Secure 2 authentication](https://docs.adyen.com/online-
     * payments/3d-secure/other-3ds-flows/authentication-only), and not the payment authorisation.
     *
     * @maps authenticationOnly
     */
    public function setAuthenticationOnly(?bool $authenticationOnly): void
    {
        $this->authenticationOnly = $authenticationOnly;
    }

    /**
     * Returns Challenge Indicator.
     * Possibility to specify a preference for receiving a challenge from the issuer.
     * Allowed values:
     * * `noPreference`
     * * `requestNoChallenge`
     * * `requestChallenge`
     * * `requestChallengeAsMandate`
     */
    public function getChallengeIndicator(): ?string
    {
        return $this->challengeIndicator;
    }

    /**
     * Sets Challenge Indicator.
     * Possibility to specify a preference for receiving a challenge from the issuer.
     * Allowed values:
     * * `noPreference`
     * * `requestNoChallenge`
     * * `requestChallenge`
     * * `requestChallengeAsMandate`
     *
     * @maps challengeIndicator
     * @factory \AdyenApIsLib\Models\ChallengeIndicator::checkValue
     */
    public function setChallengeIndicator(?string $challengeIndicator): void
    {
        $this->challengeIndicator = $challengeIndicator;
    }

    /**
     * Returns Device Render Options.
     * Display options for the 3D Secure 2 SDK.
     * Optional and only for `deviceChannel` **app**.
     */
    public function getDeviceRenderOptions(): ?DeviceRenderOptions2
    {
        return $this->deviceRenderOptions;
    }

    /**
     * Sets Device Render Options.
     * Display options for the 3D Secure 2 SDK.
     * Optional and only for `deviceChannel` **app**.
     *
     * @maps deviceRenderOptions
     */
    public function setDeviceRenderOptions(?DeviceRenderOptions2 $deviceRenderOptions): void
    {
        $this->deviceRenderOptions = $deviceRenderOptions;
    }

    /**
     * Returns Home Phone.
     * The home phone number provided by the cardholder. The phone number must consist of a country code,
     * followed by the number. If the value you provide does not follow the guidelines, we do not submit it
     * for authentication.
     * > Required for Visa and JCB transactions that require 3D Secure 2 authentication, if you did not
     * include the `shopperEmail`, and did not send the shopper's phone number in `telephoneNumber`.
     */
    public function getHomePhone(): ?Phone3
    {
        return $this->homePhone;
    }

    /**
     * Sets Home Phone.
     * The home phone number provided by the cardholder. The phone number must consist of a country code,
     * followed by the number. If the value you provide does not follow the guidelines, we do not submit it
     * for authentication.
     * > Required for Visa and JCB transactions that require 3D Secure 2 authentication, if you did not
     * include the `shopperEmail`, and did not send the shopper's phone number in `telephoneNumber`.
     *
     * @maps homePhone
     */
    public function setHomePhone(?Phone3 $homePhone): void
    {
        $this->homePhone = $homePhone;
    }

    /**
     * Returns Mcc.
     * Required for merchants that have been enrolled for 3D Secure 2 by another party than Adyen, mostly
     * [authentication-only integrations](https://docs.adyen.com/online-payments/3d-secure/other-3ds-
     * flows/authentication-only). The `mcc` is a four-digit code with which the previously given
     * `acquirerMerchantID` is registered at the scheme.
     */
    public function getMcc(): ?string
    {
        return $this->mcc;
    }

    /**
     * Sets Mcc.
     * Required for merchants that have been enrolled for 3D Secure 2 by another party than Adyen, mostly
     * [authentication-only integrations](https://docs.adyen.com/online-payments/3d-secure/other-3ds-
     * flows/authentication-only). The `mcc` is a four-digit code with which the previously given
     * `acquirerMerchantID` is registered at the scheme.
     *
     * @maps mcc
     */
    public function setMcc(?string $mcc): void
    {
        $this->mcc = $mcc;
    }

    /**
     * Returns Merchant Name.
     * Required for [authentication-only integration](https://docs.adyen.com/online-payments/3d-
     * secure/other-3ds-flows/authentication-only). The merchant name that the issuer presents to the
     * shopper if they get a challenge. We recommend to use the same value that you will use in the
     * authorization. Maximum length is 40 characters.
     * > Optional for a [full 3D Secure 2 integration](https://docs.adyen.com/online-payments/3d-
     * secure/native-3ds2/api-integration). Use this field if you are enrolled for 3D Secure 2 with us and
     * want to override the merchant name already configured on your account.
     */
    public function getMerchantName(): ?string
    {
        return $this->merchantName;
    }

    /**
     * Sets Merchant Name.
     * Required for [authentication-only integration](https://docs.adyen.com/online-payments/3d-
     * secure/other-3ds-flows/authentication-only). The merchant name that the issuer presents to the
     * shopper if they get a challenge. We recommend to use the same value that you will use in the
     * authorization. Maximum length is 40 characters.
     * > Optional for a [full 3D Secure 2 integration](https://docs.adyen.com/online-payments/3d-
     * secure/native-3ds2/api-integration). Use this field if you are enrolled for 3D Secure 2 with us and
     * want to override the merchant name already configured on your account.
     *
     * @maps merchantName
     */
    public function setMerchantName(?string $merchantName): void
    {
        $this->merchantName = $merchantName;
    }

    /**
     * Returns Message Version.
     * The `messageVersion` value indicating the 3D Secure 2 protocol version.
     */
    public function getMessageVersion(): ?string
    {
        return $this->messageVersion;
    }

    /**
     * Sets Message Version.
     * The `messageVersion` value indicating the 3D Secure 2 protocol version.
     *
     * @maps messageVersion
     */
    public function setMessageVersion(?string $messageVersion): void
    {
        $this->messageVersion = $messageVersion;
    }

    /**
     * Returns Mobile Phone.
     * The mobile phone number provided by the cardholder. The phone number must consist of a country code,
     * followed by the number. If the value you provide does not follow the guidelines, we do not submit it
     * for authentication.
     * > Required for Visa and JCB transactions that require 3D Secure 2 authentication, if you did not
     * include the `shopperEmail`, and did not send the shopper's phone number in `telephoneNumber`.
     */
    public function getMobilePhone(): ?Phone1
    {
        return $this->mobilePhone;
    }

    /**
     * Sets Mobile Phone.
     * The mobile phone number provided by the cardholder. The phone number must consist of a country code,
     * followed by the number. If the value you provide does not follow the guidelines, we do not submit it
     * for authentication.
     * > Required for Visa and JCB transactions that require 3D Secure 2 authentication, if you did not
     * include the `shopperEmail`, and did not send the shopper's phone number in `telephoneNumber`.
     *
     * @maps mobilePhone
     */
    public function setMobilePhone(?Phone1 $mobilePhone): void
    {
        $this->mobilePhone = $mobilePhone;
    }

    /**
     * Returns Notification Url.
     * URL to where the issuer should send the `CRes`. Required if you are not using components for
     * `channel` **Web** or if you are using classic integration `deviceChannel` **browser**.
     */
    public function getNotificationUrl(): ?string
    {
        return $this->notificationUrl;
    }

    /**
     * Sets Notification Url.
     * URL to where the issuer should send the `CRes`. Required if you are not using components for
     * `channel` **Web** or if you are using classic integration `deviceChannel` **browser**.
     *
     * @maps notificationURL
     */
    public function setNotificationUrl(?string $notificationUrl): void
    {
        $this->notificationUrl = $notificationUrl;
    }

    /**
     * Returns Pay Token Ind.
     * Value **true** indicates that the transaction was de-tokenised prior to being received by the ACS.
     */
    public function getPayTokenInd(): ?bool
    {
        return $this->payTokenInd;
    }

    /**
     * Sets Pay Token Ind.
     * Value **true** indicates that the transaction was de-tokenised prior to being received by the ACS.
     *
     * @maps payTokenInd
     */
    public function setPayTokenInd(?bool $payTokenInd): void
    {
        $this->payTokenInd = $payTokenInd;
    }

    /**
     * Returns Payment Authentication Use Case.
     * Indicates the type of payment for which an authentication is requested (message extension)
     */
    public function getPaymentAuthenticationUseCase(): ?string
    {
        return $this->paymentAuthenticationUseCase;
    }

    /**
     * Sets Payment Authentication Use Case.
     * Indicates the type of payment for which an authentication is requested (message extension)
     *
     * @maps paymentAuthenticationUseCase
     */
    public function setPaymentAuthenticationUseCase(?string $paymentAuthenticationUseCase): void
    {
        $this->paymentAuthenticationUseCase = $paymentAuthenticationUseCase;
    }

    /**
     * Returns Purchase Instal Data.
     * Indicates the maximum number of authorisations permitted for instalment payments. Length: 1–3
     * characters.
     */
    public function getPurchaseInstalData(): ?string
    {
        return $this->purchaseInstalData;
    }

    /**
     * Sets Purchase Instal Data.
     * Indicates the maximum number of authorisations permitted for instalment payments. Length: 1–3
     * characters.
     *
     * @maps purchaseInstalData
     */
    public function setPurchaseInstalData(?string $purchaseInstalData): void
    {
        $this->purchaseInstalData = $purchaseInstalData;
    }

    /**
     * Returns Recurring Expiry.
     * Date after which no further authorisations shall be performed. Format: YYYYMMDD
     */
    public function getRecurringExpiry(): ?string
    {
        return $this->recurringExpiry;
    }

    /**
     * Sets Recurring Expiry.
     * Date after which no further authorisations shall be performed. Format: YYYYMMDD
     *
     * @maps recurringExpiry
     */
    public function setRecurringExpiry(?string $recurringExpiry): void
    {
        $this->recurringExpiry = $recurringExpiry;
    }

    /**
     * Returns Recurring Frequency.
     * Indicates the minimum number of days between authorisations. Maximum length: 4 characters.
     */
    public function getRecurringFrequency(): ?string
    {
        return $this->recurringFrequency;
    }

    /**
     * Sets Recurring Frequency.
     * Indicates the minimum number of days between authorisations. Maximum length: 4 characters.
     *
     * @maps recurringFrequency
     */
    public function setRecurringFrequency(?string $recurringFrequency): void
    {
        $this->recurringFrequency = $recurringFrequency;
    }

    /**
     * Returns Sdk App Id.
     * The `sdkAppID` value as received from the 3D Secure 2 SDK.
     */
    public function getSdkAppId(): ?string
    {
        return $this->sdkAppId;
    }

    /**
     * Sets Sdk App Id.
     * The `sdkAppID` value as received from the 3D Secure 2 SDK.
     *
     * @maps sdkAppID
     */
    public function setSdkAppId(?string $sdkAppId): void
    {
        $this->sdkAppId = $sdkAppId;
    }

    /**
     * Returns Sdk Ephem Pub Key.
     * The `sdkEphemPubKey` value as received from the 3D Secure 2 SDK.
     */
    public function getSdkEphemPubKey(): ?SdkEphemPubKey1
    {
        return $this->sdkEphemPubKey;
    }

    /**
     * Sets Sdk Ephem Pub Key.
     * The `sdkEphemPubKey` value as received from the 3D Secure 2 SDK.
     *
     * @maps sdkEphemPubKey
     */
    public function setSdkEphemPubKey(?SdkEphemPubKey1 $sdkEphemPubKey): void
    {
        $this->sdkEphemPubKey = $sdkEphemPubKey;
    }

    /**
     * Returns Sdk Max Timeout.
     * The maximum amount of time in minutes for the 3D Secure 2 authentication process.
     * Optional and only for `deviceChannel` set to **app**. Defaults to **60** minutes.
     */
    public function getSdkMaxTimeout(): ?int
    {
        return $this->sdkMaxTimeout;
    }

    /**
     * Sets Sdk Max Timeout.
     * The maximum amount of time in minutes for the 3D Secure 2 authentication process.
     * Optional and only for `deviceChannel` set to **app**. Defaults to **60** minutes.
     *
     * @maps sdkMaxTimeout
     */
    public function setSdkMaxTimeout(?int $sdkMaxTimeout): void
    {
        $this->sdkMaxTimeout = $sdkMaxTimeout;
    }

    /**
     * Returns Sdk Reference Number.
     * The `sdkReferenceNumber` value as received from the 3D Secure 2 SDK.
     */
    public function getSdkReferenceNumber(): ?string
    {
        return $this->sdkReferenceNumber;
    }

    /**
     * Sets Sdk Reference Number.
     * The `sdkReferenceNumber` value as received from the 3D Secure 2 SDK.
     *
     * @maps sdkReferenceNumber
     */
    public function setSdkReferenceNumber(?string $sdkReferenceNumber): void
    {
        $this->sdkReferenceNumber = $sdkReferenceNumber;
    }

    /**
     * Returns Sdk Trans Id.
     * The `sdkTransID` value as received from the 3D Secure 2 SDK.
     */
    public function getSdkTransId(): ?string
    {
        return $this->sdkTransId;
    }

    /**
     * Sets Sdk Trans Id.
     * The `sdkTransID` value as received from the 3D Secure 2 SDK.
     *
     * @maps sdkTransID
     */
    public function setSdkTransId(?string $sdkTransId): void
    {
        $this->sdkTransId = $sdkTransId;
    }

    /**
     * Returns Three Ds Comp Ind.
     * Completion indicator for the device fingerprinting.
     */
    public function getThreeDsCompInd(): ?string
    {
        return $this->threeDsCompInd;
    }

    /**
     * Sets Three Ds Comp Ind.
     * Completion indicator for the device fingerprinting.
     *
     * @maps threeDSCompInd
     */
    public function setThreeDsCompInd(?string $threeDsCompInd): void
    {
        $this->threeDsCompInd = $threeDsCompInd;
    }

    /**
     * Returns Three Ds Requestor Authentication Ind.
     * Indicates the type of Authentication request.
     */
    public function getThreeDsRequestorAuthenticationInd(): ?string
    {
        return $this->threeDsRequestorAuthenticationInd;
    }

    /**
     * Sets Three Ds Requestor Authentication Ind.
     * Indicates the type of Authentication request.
     *
     * @maps threeDSRequestorAuthenticationInd
     */
    public function setThreeDsRequestorAuthenticationInd(?string $threeDsRequestorAuthenticationInd): void
    {
        $this->threeDsRequestorAuthenticationInd = $threeDsRequestorAuthenticationInd;
    }

    /**
     * Returns Three Ds Requestor Authentication Info.
     * Information about how the 3DS Requestor authenticated the cardholder before or during the
     * transaction
     */
    public function getThreeDsRequestorAuthenticationInfo(): ?ThreeDsRequestorAuthenticationInfo1
    {
        return $this->threeDsRequestorAuthenticationInfo;
    }

    /**
     * Sets Three Ds Requestor Authentication Info.
     * Information about how the 3DS Requestor authenticated the cardholder before or during the
     * transaction
     *
     * @maps threeDSRequestorAuthenticationInfo
     */
    public function setThreeDsRequestorAuthenticationInfo(
        ?ThreeDsRequestorAuthenticationInfo1 $threeDsRequestorAuthenticationInfo
    ): void {
        $this->threeDsRequestorAuthenticationInfo = $threeDsRequestorAuthenticationInfo;
    }

    /**
     * Returns Three Ds Requestor Challenge Ind.
     * Indicates whether a challenge is requested for this transaction. Possible values:
     * * **01** — No preference
     * * **02** — No challenge requested
     * * **03** — Challenge requested (3DS Requestor preference)
     * * **04** — Challenge requested (Mandate)
     * * **05** — No challenge (transactional risk analysis is already performed)
     * * **06** — Data Only
     */
    public function getThreeDsRequestorChallengeInd(): ?string
    {
        return $this->threeDsRequestorChallengeInd;
    }

    /**
     * Sets Three Ds Requestor Challenge Ind.
     * Indicates whether a challenge is requested for this transaction. Possible values:
     * * **01** — No preference
     * * **02** — No challenge requested
     * * **03** — Challenge requested (3DS Requestor preference)
     * * **04** — Challenge requested (Mandate)
     * * **05** — No challenge (transactional risk analysis is already performed)
     * * **06** — Data Only
     *
     * @maps threeDSRequestorChallengeInd
     * @factory \AdyenApIsLib\Models\ThreeDsRequestorChallengeInd::checkValue
     */
    public function setThreeDsRequestorChallengeInd(?string $threeDsRequestorChallengeInd): void
    {
        $this->threeDsRequestorChallengeInd = $threeDsRequestorChallengeInd;
    }

    /**
     * Returns Three Ds Requestor Id.
     * Required for [authentication-only integration](https://docs.adyen.com/online-payments/3d-
     * secure/other-3ds-flows/authentication-only) for Visa. Unique 3D Secure requestor identifier assigned
     * by the Directory Server when you enrol for 3D Secure 2.
     */
    public function getThreeDsRequestorId(): ?string
    {
        return $this->threeDsRequestorId;
    }

    /**
     * Sets Three Ds Requestor Id.
     * Required for [authentication-only integration](https://docs.adyen.com/online-payments/3d-
     * secure/other-3ds-flows/authentication-only) for Visa. Unique 3D Secure requestor identifier assigned
     * by the Directory Server when you enrol for 3D Secure 2.
     *
     * @maps threeDSRequestorID
     */
    public function setThreeDsRequestorId(?string $threeDsRequestorId): void
    {
        $this->threeDsRequestorId = $threeDsRequestorId;
    }

    /**
     * Returns Three Ds Requestor Name.
     * Required for [authentication-only integration](https://docs.adyen.com/online-payments/3d-
     * secure/other-3ds-flows/authentication-only) for Visa. Unique 3D Secure requestor name assigned by
     * the Directory Server when you enrol for 3D Secure 2.
     */
    public function getThreeDsRequestorName(): ?string
    {
        return $this->threeDsRequestorName;
    }

    /**
     * Sets Three Ds Requestor Name.
     * Required for [authentication-only integration](https://docs.adyen.com/online-payments/3d-
     * secure/other-3ds-flows/authentication-only) for Visa. Unique 3D Secure requestor name assigned by
     * the Directory Server when you enrol for 3D Secure 2.
     *
     * @maps threeDSRequestorName
     */
    public function setThreeDsRequestorName(?string $threeDsRequestorName): void
    {
        $this->threeDsRequestorName = $threeDsRequestorName;
    }

    /**
     * Returns Three Ds Requestor Prior Authentication Info.
     * Information about how the 3DS Requestor authenticated the cardholder as part of a previous 3DS
     * transaction.
     */
    public function getThreeDsRequestorPriorAuthenticationInfo(): ?ThreeDsRequestorPriorAuthenticationInfo1
    {
        return $this->threeDsRequestorPriorAuthenticationInfo;
    }

    /**
     * Sets Three Ds Requestor Prior Authentication Info.
     * Information about how the 3DS Requestor authenticated the cardholder as part of a previous 3DS
     * transaction.
     *
     * @maps threeDSRequestorPriorAuthenticationInfo
     */
    public function setThreeDsRequestorPriorAuthenticationInfo(
        ?ThreeDsRequestorPriorAuthenticationInfo1 $threeDsRequestorPriorAuthenticationInfo
    ): void {
        $this->threeDsRequestorPriorAuthenticationInfo = $threeDsRequestorPriorAuthenticationInfo;
    }

    /**
     * Returns Three Ds Requestor Url.
     * URL of the (customer service) website that will be shown to the shopper in case of technical errors
     * during the 3D Secure 2 process.
     */
    public function getThreeDsRequestorUrl(): ?string
    {
        return $this->threeDsRequestorUrl;
    }

    /**
     * Sets Three Ds Requestor Url.
     * URL of the (customer service) website that will be shown to the shopper in case of technical errors
     * during the 3D Secure 2 process.
     *
     * @maps threeDSRequestorURL
     */
    public function setThreeDsRequestorUrl(?string $threeDsRequestorUrl): void
    {
        $this->threeDsRequestorUrl = $threeDsRequestorUrl;
    }

    /**
     * Returns Trans Type.
     * Identifies the type of transaction being authenticated. Length: 2 characters. Allowed values:
     * * **01** — Goods/Service Purchase
     * * **03** — Check Acceptance
     * * **10** — Account Funding
     * * **11** — Quasi-Cash Transaction
     * * **28** — Prepaid Activation and Load
     */
    public function getTransType(): ?string
    {
        return $this->transType;
    }

    /**
     * Sets Trans Type.
     * Identifies the type of transaction being authenticated. Length: 2 characters. Allowed values:
     * * **01** — Goods/Service Purchase
     * * **03** — Check Acceptance
     * * **10** — Account Funding
     * * **11** — Quasi-Cash Transaction
     * * **28** — Prepaid Activation and Load
     *
     * @maps transType
     * @factory \AdyenApIsLib\Models\TransType::checkValue
     */
    public function setTransType(?string $transType): void
    {
        $this->transType = $transType;
    }

    /**
     * Returns Transaction Type.
     * Identify the type of the transaction being authenticated.
     */
    public function getTransactionType(): ?string
    {
        return $this->transactionType;
    }

    /**
     * Sets Transaction Type.
     * Identify the type of the transaction being authenticated.
     *
     * @maps transactionType
     * @factory \AdyenApIsLib\Models\TransactionType::checkValue
     */
    public function setTransactionType(?string $transactionType): void
    {
        $this->transactionType = $transactionType;
    }

    /**
     * Returns White List Status.
     * The `whiteListStatus` value returned from a previous 3D Secure 2 transaction, only applicable for 3D
     * Secure 2 protocol version 2.2.0.
     */
    public function getWhiteListStatus(): ?string
    {
        return $this->whiteListStatus;
    }

    /**
     * Sets White List Status.
     * The `whiteListStatus` value returned from a previous 3D Secure 2 transaction, only applicable for 3D
     * Secure 2 protocol version 2.2.0.
     *
     * @maps whiteListStatus
     */
    public function setWhiteListStatus(?string $whiteListStatus): void
    {
        $this->whiteListStatus = $whiteListStatus;
    }

    /**
     * Returns Work Phone.
     * The work phone number provided by the cardholder. The phone number must consist of a country code,
     * followed by the number. If the value you provide does not follow the guidelines, we do not submit it
     * for authentication.
     * > Required for Visa and JCB transactions that require 3D Secure 2 authentication, if you did not
     * include the `shopperEmail`, and did not send the shopper's phone number in `telephoneNumber`.
     */
    public function getWorkPhone(): ?Phone2
    {
        return $this->workPhone;
    }

    /**
     * Sets Work Phone.
     * The work phone number provided by the cardholder. The phone number must consist of a country code,
     * followed by the number. If the value you provide does not follow the guidelines, we do not submit it
     * for authentication.
     * > Required for Visa and JCB transactions that require 3D Secure 2 authentication, if you did not
     * include the `shopperEmail`, and did not send the shopper's phone number in `telephoneNumber`.
     *
     * @maps workPhone
     */
    public function setWorkPhone(?Phone2 $workPhone): void
    {
        $this->workPhone = $workPhone;
    }

    /**
     * Converts the ThreeDs2RequestFields object to a human-readable string representation.
     *
     * @return string The string representation of the ThreeDs2RequestFields object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'ThreeDs2RequestFields',
            [
                'acctInfo' => $this->acctInfo,
                'acctType' => $this->acctType,
                'acquirerBin' => $this->acquirerBin,
                'acquirerMerchantId' => $this->acquirerMerchantId,
                'addrMatch' => $this->addrMatch,
                'authenticationOnly' => $this->authenticationOnly,
                'challengeIndicator' => $this->challengeIndicator,
                'deviceRenderOptions' => $this->deviceRenderOptions,
                'homePhone' => $this->homePhone,
                'mcc' => $this->mcc,
                'merchantName' => $this->merchantName,
                'messageVersion' => $this->messageVersion,
                'mobilePhone' => $this->mobilePhone,
                'notificationUrl' => $this->notificationUrl,
                'payTokenInd' => $this->payTokenInd,
                'paymentAuthenticationUseCase' => $this->paymentAuthenticationUseCase,
                'purchaseInstalData' => $this->purchaseInstalData,
                'recurringExpiry' => $this->recurringExpiry,
                'recurringFrequency' => $this->recurringFrequency,
                'sdkAppId' => $this->sdkAppId,
                'sdkEphemPubKey' => $this->sdkEphemPubKey,
                'sdkMaxTimeout' => $this->sdkMaxTimeout,
                'sdkReferenceNumber' => $this->sdkReferenceNumber,
                'sdkTransId' => $this->sdkTransId,
                'threeDsCompInd' => $this->threeDsCompInd,
                'threeDsRequestorAuthenticationInd' => $this->threeDsRequestorAuthenticationInd,
                'threeDsRequestorAuthenticationInfo' => $this->threeDsRequestorAuthenticationInfo,
                'threeDsRequestorChallengeInd' => $this->threeDsRequestorChallengeInd,
                'threeDsRequestorId' => $this->threeDsRequestorId,
                'threeDsRequestorName' => $this->threeDsRequestorName,
                'threeDsRequestorPriorAuthenticationInfo' => $this->threeDsRequestorPriorAuthenticationInfo,
                'threeDsRequestorUrl' => $this->threeDsRequestorUrl,
                'transType' => $this->transType,
                'transactionType' => $this->transactionType,
                'whiteListStatus' => $this->whiteListStatus,
                'workPhone' => $this->workPhone
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->acctInfo)) {
            $json['acctInfo']                                = $this->acctInfo;
        }
        if (isset($this->acctType)) {
            $json['acctType']                                = AcctType::checkValue($this->acctType);
        }
        if (isset($this->acquirerBin)) {
            $json['acquirerBIN']                             = $this->acquirerBin;
        }
        if (isset($this->acquirerMerchantId)) {
            $json['acquirerMerchantID']                      = $this->acquirerMerchantId;
        }
        if (isset($this->addrMatch)) {
            $json['addrMatch']                               = AddrMatch1::checkValue($this->addrMatch);
        }
        if (isset($this->authenticationOnly)) {
            $json['authenticationOnly']                      = $this->authenticationOnly;
        }
        if (isset($this->challengeIndicator)) {
            $json['challengeIndicator']                      =
                ChallengeIndicator::checkValue(
                    $this->challengeIndicator
                );
        }
        if (isset($this->deviceRenderOptions)) {
            $json['deviceRenderOptions']                     = $this->deviceRenderOptions;
        }
        if (isset($this->homePhone)) {
            $json['homePhone']                               = $this->homePhone;
        }
        if (isset($this->mcc)) {
            $json['mcc']                                     = $this->mcc;
        }
        if (isset($this->merchantName)) {
            $json['merchantName']                            = $this->merchantName;
        }
        if (isset($this->messageVersion)) {
            $json['messageVersion']                          = $this->messageVersion;
        }
        if (isset($this->mobilePhone)) {
            $json['mobilePhone']                             = $this->mobilePhone;
        }
        if (isset($this->notificationUrl)) {
            $json['notificationURL']                         = $this->notificationUrl;
        }
        if (isset($this->payTokenInd)) {
            $json['payTokenInd']                             = $this->payTokenInd;
        }
        if (isset($this->paymentAuthenticationUseCase)) {
            $json['paymentAuthenticationUseCase']            = $this->paymentAuthenticationUseCase;
        }
        if (isset($this->purchaseInstalData)) {
            $json['purchaseInstalData']                      = $this->purchaseInstalData;
        }
        if (isset($this->recurringExpiry)) {
            $json['recurringExpiry']                         = $this->recurringExpiry;
        }
        if (isset($this->recurringFrequency)) {
            $json['recurringFrequency']                      = $this->recurringFrequency;
        }
        if (isset($this->sdkAppId)) {
            $json['sdkAppID']                                = $this->sdkAppId;
        }
        if (isset($this->sdkEphemPubKey)) {
            $json['sdkEphemPubKey']                          = $this->sdkEphemPubKey;
        }
        if (isset($this->sdkMaxTimeout)) {
            $json['sdkMaxTimeout']                           = $this->sdkMaxTimeout;
        }
        if (isset($this->sdkReferenceNumber)) {
            $json['sdkReferenceNumber']                      = $this->sdkReferenceNumber;
        }
        if (isset($this->sdkTransId)) {
            $json['sdkTransID']                              = $this->sdkTransId;
        }
        if (isset($this->threeDsCompInd)) {
            $json['threeDSCompInd']                          = $this->threeDsCompInd;
        }
        if (isset($this->threeDsRequestorAuthenticationInd)) {
            $json['threeDSRequestorAuthenticationInd']       = $this->threeDsRequestorAuthenticationInd;
        }
        if (isset($this->threeDsRequestorAuthenticationInfo)) {
            $json['threeDSRequestorAuthenticationInfo']      = $this->threeDsRequestorAuthenticationInfo;
        }
        if (isset($this->threeDsRequestorChallengeInd)) {
            $json['threeDSRequestorChallengeInd']            =
                ThreeDsRequestorChallengeInd::checkValue(
                    $this->threeDsRequestorChallengeInd
                );
        }
        if (isset($this->threeDsRequestorId)) {
            $json['threeDSRequestorID']                      = $this->threeDsRequestorId;
        }
        if (isset($this->threeDsRequestorName)) {
            $json['threeDSRequestorName']                    = $this->threeDsRequestorName;
        }
        if (isset($this->threeDsRequestorPriorAuthenticationInfo)) {
            $json['threeDSRequestorPriorAuthenticationInfo'] = $this->threeDsRequestorPriorAuthenticationInfo;
        }
        if (isset($this->threeDsRequestorUrl)) {
            $json['threeDSRequestorURL']                     = $this->threeDsRequestorUrl;
        }
        if (isset($this->transType)) {
            $json['transType']                               = TransType::checkValue($this->transType);
        }
        if (isset($this->transactionType)) {
            $json['transactionType']                         = TransactionType::checkValue($this->transactionType);
        }
        if (isset($this->whiteListStatus)) {
            $json['whiteListStatus']                         = $this->whiteListStatus;
        }
        if (isset($this->workPhone)) {
            $json['workPhone']                               = $this->workPhone;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
