<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

/**
 * Mandate details for the stored payment method.
 */
class TokenMandate2 implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $accountIdType;

    /**
     * @var string
     */
    private $amount;

    /**
     * @var string|null
     */
    private $amountRule;

    /**
     * @var string|null
     */
    private $billingAttemptsRule;

    /**
     * @var string|null
     */
    private $billingDay;

    /**
     * @var string|null
     */
    private $count;

    /**
     * @var string
     */
    private $currency;

    /**
     * @var string
     */
    private $endsAt;

    /**
     * @var string
     */
    private $frequency;

    /**
     * @var string
     */
    private $mandateId;

    /**
     * @var string|null
     */
    private $maskedAccountId;

    /**
     * @var string
     */
    private $providerId;

    /**
     * @var string|null
     */
    private $remarks;

    /**
     * @var string|null
     */
    private $startsAt;

    /**
     * @var string
     */
    private $status;

    /**
     * @var string
     */
    private $txVariant;

    /**
     * @param string $amount
     * @param string $currency
     * @param string $endsAt
     * @param string $frequency
     * @param string $mandateId
     * @param string $providerId
     * @param string $status
     * @param string $txVariant
     */
    public function __construct(
        string $amount,
        string $currency,
        string $endsAt,
        string $frequency,
        string $mandateId,
        string $providerId,
        string $status,
        string $txVariant
    ) {
        $this->amount = $amount;
        $this->currency = $currency;
        $this->endsAt = $endsAt;
        $this->frequency = $frequency;
        $this->mandateId = $mandateId;
        $this->providerId = $providerId;
        $this->status = $status;
        $this->txVariant = $txVariant;
    }

    /**
     * Returns Account Id Type.
     * The type of account identifier for the masked account number.
     */
    public function getAccountIdType(): ?string
    {
        return $this->accountIdType;
    }

    /**
     * Sets Account Id Type.
     * The type of account identifier for the masked account number.
     *
     * @maps accountIdType
     */
    public function setAccountIdType(?string $accountIdType): void
    {
        $this->accountIdType = $accountIdType;
    }

    /**
     * Returns Amount.
     * The billing amount (in minor units) of the recurring transactions.
     */
    public function getAmount(): string
    {
        return $this->amount;
    }

    /**
     * Sets Amount.
     * The billing amount (in minor units) of the recurring transactions.
     *
     * @required
     * @maps amount
     */
    public function setAmount(string $amount): void
    {
        $this->amount = $amount;
    }

    /**
     * Returns Amount Rule.
     * The limitation rule of the billing amount.
     *
     * Possible values:
     * * **max**: The transaction amount can not exceed the `amount`.
     *
     * * **exact**: The transaction amount should be the same as the `amount`.
     */
    public function getAmountRule(): ?string
    {
        return $this->amountRule;
    }

    /**
     * Sets Amount Rule.
     * The limitation rule of the billing amount.
     *
     * Possible values:
     * * **max**: The transaction amount can not exceed the `amount`.
     *
     * * **exact**: The transaction amount should be the same as the `amount`.
     *
     * @maps amountRule
     * @factory \AdyenApIsLib\Models\AmountRule::checkValue
     */
    public function setAmountRule(?string $amountRule): void
    {
        $this->amountRule = $amountRule;
    }

    /**
     * Returns Billing Attempts Rule.
     * The rule to specify the period, within which the recurring debit can happen, relative to the mandate
     * recurring date.
     *
     * Possible values:
     *
     * * **on**: On a specific date.
     *
     * * **before**:  Before and on a specific date.
     *
     * * **after**: On and after a specific date.
     */
    public function getBillingAttemptsRule(): ?string
    {
        return $this->billingAttemptsRule;
    }

    /**
     * Sets Billing Attempts Rule.
     * The rule to specify the period, within which the recurring debit can happen, relative to the mandate
     * recurring date.
     *
     * Possible values:
     *
     * * **on**: On a specific date.
     *
     * * **before**:  Before and on a specific date.
     *
     * * **after**: On and after a specific date.
     *
     * @maps billingAttemptsRule
     * @factory \AdyenApIsLib\Models\BillingAttemptsRule::checkValue
     */
    public function setBillingAttemptsRule(?string $billingAttemptsRule): void
    {
        $this->billingAttemptsRule = $billingAttemptsRule;
    }

    /**
     * Returns Billing Day.
     * The number of the day, on which the recurring debit can happen. Should be within the same calendar
     * month as the mandate recurring date.
     *
     * Possible values: 1-31 based on the `frequency`.
     */
    public function getBillingDay(): ?string
    {
        return $this->billingDay;
    }

    /**
     * Sets Billing Day.
     * The number of the day, on which the recurring debit can happen. Should be within the same calendar
     * month as the mandate recurring date.
     *
     * Possible values: 1-31 based on the `frequency`.
     *
     * @maps billingDay
     */
    public function setBillingDay(?string $billingDay): void
    {
        $this->billingDay = $billingDay;
    }

    /**
     * Returns Count.
     * The number of transactions that can be performed within the given frequency.
     */
    public function getCount(): ?string
    {
        return $this->count;
    }

    /**
     * Sets Count.
     * The number of transactions that can be performed within the given frequency.
     *
     * @maps count
     */
    public function setCount(?string $count): void
    {
        $this->count = $count;
    }

    /**
     * Returns Currency.
     * The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes).
     */
    public function getCurrency(): string
    {
        return $this->currency;
    }

    /**
     * Sets Currency.
     * The three-character [ISO currency code](https://docs.adyen.com/development-resources/currency-codes).
     *
     * @required
     * @maps currency
     */
    public function setCurrency(string $currency): void
    {
        $this->currency = $currency;
    }

    /**
     * Returns Ends At.
     * End date of the billing plan, in YYYY-MM-DD format.
     */
    public function getEndsAt(): string
    {
        return $this->endsAt;
    }

    /**
     * Sets Ends At.
     * End date of the billing plan, in YYYY-MM-DD format.
     *
     * @required
     * @maps endsAt
     */
    public function setEndsAt(string $endsAt): void
    {
        $this->endsAt = $endsAt;
    }

    /**
     * Returns Frequency.
     * The frequency with which a shopper should be charged.
     *
     * Possible values: **adhoc**, **daily**, **weekly**, **biWeekly**, **monthly**, **quarterly**,
     * **halfYearly**, **yearly**.
     */
    public function getFrequency(): string
    {
        return $this->frequency;
    }

    /**
     * Sets Frequency.
     * The frequency with which a shopper should be charged.
     *
     * Possible values: **adhoc**, **daily**, **weekly**, **biWeekly**, **monthly**, **quarterly**,
     * **halfYearly**, **yearly**.
     *
     * @required
     * @maps frequency
     * @factory \AdyenApIsLib\Models\Frequency::checkValue
     */
    public function setFrequency(string $frequency): void
    {
        $this->frequency = $frequency;
    }

    /**
     * Returns Mandate Id.
     * The unique identifier of the mandate.
     */
    public function getMandateId(): string
    {
        return $this->mandateId;
    }

    /**
     * Sets Mandate Id.
     * The unique identifier of the mandate.
     *
     * @required
     * @maps mandateId
     */
    public function setMandateId(string $mandateId): void
    {
        $this->mandateId = $mandateId;
    }

    /**
     * Returns Masked Account Id.
     * The masked account number associated with the mandate.
     */
    public function getMaskedAccountId(): ?string
    {
        return $this->maskedAccountId;
    }

    /**
     * Sets Masked Account Id.
     * The masked account number associated with the mandate.
     *
     * @maps maskedAccountId
     */
    public function setMaskedAccountId(?string $maskedAccountId): void
    {
        $this->maskedAccountId = $maskedAccountId;
    }

    /**
     * Returns Provider Id.
     * The provider-specific identifier for this mandate.
     */
    public function getProviderId(): string
    {
        return $this->providerId;
    }

    /**
     * Sets Provider Id.
     * The provider-specific identifier for this mandate.
     *
     * @required
     * @maps providerId
     */
    public function setProviderId(string $providerId): void
    {
        $this->providerId = $providerId;
    }

    /**
     * Returns Remarks.
     * Additional remarks or notes about the mandate.
     */
    public function getRemarks(): ?string
    {
        return $this->remarks;
    }

    /**
     * Sets Remarks.
     * Additional remarks or notes about the mandate.
     *
     * @maps remarks
     */
    public function setRemarks(?string $remarks): void
    {
        $this->remarks = $remarks;
    }

    /**
     * Returns Starts At.
     * Start date of the billing plan, in YYYY-MM-DD format. By default, the transaction date.
     */
    public function getStartsAt(): ?string
    {
        return $this->startsAt;
    }

    /**
     * Sets Starts At.
     * Start date of the billing plan, in YYYY-MM-DD format. By default, the transaction date.
     *
     * @maps startsAt
     */
    public function setStartsAt(?string $startsAt): void
    {
        $this->startsAt = $startsAt;
    }

    /**
     * Returns Status.
     * The status of the mandate. Examples : active, revoked, completed, expired
     */
    public function getStatus(): string
    {
        return $this->status;
    }

    /**
     * Sets Status.
     * The status of the mandate. Examples : active, revoked, completed, expired
     *
     * @required
     * @maps status
     */
    public function setStatus(string $status): void
    {
        $this->status = $status;
    }

    /**
     * Returns Tx Variant.
     * The transaction variant used for this mandate.
     */
    public function getTxVariant(): string
    {
        return $this->txVariant;
    }

    /**
     * Sets Tx Variant.
     * The transaction variant used for this mandate.
     *
     * @required
     * @maps txVariant
     */
    public function setTxVariant(string $txVariant): void
    {
        $this->txVariant = $txVariant;
    }

    /**
     * Converts the TokenMandate2 object to a human-readable string representation.
     *
     * @return string The string representation of the TokenMandate2 object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'TokenMandate2',
            [
                'accountIdType' => $this->accountIdType,
                'amount' => $this->amount,
                'amountRule' => $this->amountRule,
                'billingAttemptsRule' => $this->billingAttemptsRule,
                'billingDay' => $this->billingDay,
                'count' => $this->count,
                'currency' => $this->currency,
                'endsAt' => $this->endsAt,
                'frequency' => $this->frequency,
                'mandateId' => $this->mandateId,
                'maskedAccountId' => $this->maskedAccountId,
                'providerId' => $this->providerId,
                'remarks' => $this->remarks,
                'startsAt' => $this->startsAt,
                'status' => $this->status,
                'txVariant' => $this->txVariant
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->accountIdType)) {
            $json['accountIdType']       = $this->accountIdType;
        }
        $json['amount']                  = $this->amount;
        if (isset($this->amountRule)) {
            $json['amountRule']          = AmountRule::checkValue($this->amountRule);
        }
        if (isset($this->billingAttemptsRule)) {
            $json['billingAttemptsRule'] = BillingAttemptsRule::checkValue($this->billingAttemptsRule);
        }
        if (isset($this->billingDay)) {
            $json['billingDay']          = $this->billingDay;
        }
        if (isset($this->count)) {
            $json['count']               = $this->count;
        }
        $json['currency']                = $this->currency;
        $json['endsAt']                  = $this->endsAt;
        $json['frequency']               = Frequency::checkValue($this->frequency);
        $json['mandateId']               = $this->mandateId;
        if (isset($this->maskedAccountId)) {
            $json['maskedAccountId']     = $this->maskedAccountId;
        }
        $json['providerId']              = $this->providerId;
        if (isset($this->remarks)) {
            $json['remarks']             = $this->remarks;
        }
        if (isset($this->startsAt)) {
            $json['startsAt']            = $this->startsAt;
        }
        $json['status']                  = $this->status;
        $json['txVariant']               = $this->txVariant;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
