<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class UpiQr implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $billingSequenceNumber;

    /**
     * @var string|null
     */
    private $checkoutAttemptId;

    /**
     * @var string|null
     */
    private $recurringDetailReference;

    /**
     * @var string|null
     */
    private $sdkData;

    /**
     * @var string|null
     */
    private $shopperNotificationReference;

    /**
     * @var string|null
     */
    private $storedPaymentMethodId;

    /**
     * @var string
     */
    private $type;

    /**
     * Returns Billing Sequence Number.
     * The sequence number for the debit. For example, send **2** if this is the second debit for the
     * subscription. The sequence number is included in the notification sent to the shopper.
     */
    public function getBillingSequenceNumber(): ?string
    {
        return $this->billingSequenceNumber;
    }

    /**
     * Sets Billing Sequence Number.
     * The sequence number for the debit. For example, send **2** if this is the second debit for the
     * subscription. The sequence number is included in the notification sent to the shopper.
     *
     * @maps billingSequenceNumber
     */
    public function setBillingSequenceNumber(?string $billingSequenceNumber): void
    {
        $this->billingSequenceNumber = $billingSequenceNumber;
    }

    /**
     * Returns Checkout Attempt Id.
     * The checkout attempt identifier.
     */
    public function getCheckoutAttemptId(): ?string
    {
        return $this->checkoutAttemptId;
    }

    /**
     * Sets Checkout Attempt Id.
     * The checkout attempt identifier.
     *
     * @maps checkoutAttemptId
     */
    public function setCheckoutAttemptId(?string $checkoutAttemptId): void
    {
        $this->checkoutAttemptId = $checkoutAttemptId;
    }

    /**
     * Returns Recurring Detail Reference.
     * This is the `recurringDetailReference` returned in the response when you created the token.
     */
    public function getRecurringDetailReference(): ?string
    {
        return $this->recurringDetailReference;
    }

    /**
     * Sets Recurring Detail Reference.
     * This is the `recurringDetailReference` returned in the response when you created the token.
     *
     * @maps recurringDetailReference
     */
    public function setRecurringDetailReference(?string $recurringDetailReference): void
    {
        $this->recurringDetailReference = $recurringDetailReference;
    }

    /**
     * Returns Sdk Data.
     * Base64-encoded JSON object containing SDK related parameters required by the SDK
     */
    public function getSdkData(): ?string
    {
        return $this->sdkData;
    }

    /**
     * Sets Sdk Data.
     * Base64-encoded JSON object containing SDK related parameters required by the SDK
     *
     * @maps sdkData
     */
    public function setSdkData(?string $sdkData): void
    {
        $this->sdkData = $sdkData;
    }

    /**
     * Returns Shopper Notification Reference.
     * The `shopperNotificationReference` returned in the response when you requested to notify the shopper.
     * Used for recurring payment only.
     */
    public function getShopperNotificationReference(): ?string
    {
        return $this->shopperNotificationReference;
    }

    /**
     * Sets Shopper Notification Reference.
     * The `shopperNotificationReference` returned in the response when you requested to notify the shopper.
     * Used for recurring payment only.
     *
     * @maps shopperNotificationReference
     */
    public function setShopperNotificationReference(?string $shopperNotificationReference): void
    {
        $this->shopperNotificationReference = $shopperNotificationReference;
    }

    /**
     * Returns Stored Payment Method Id.
     * This is the `recurringDetailReference` returned in the response when you created the token.
     */
    public function getStoredPaymentMethodId(): ?string
    {
        return $this->storedPaymentMethodId;
    }

    /**
     * Sets Stored Payment Method Id.
     * This is the `recurringDetailReference` returned in the response when you created the token.
     *
     * @maps storedPaymentMethodId
     */
    public function setStoredPaymentMethodId(?string $storedPaymentMethodId): void
    {
        $this->storedPaymentMethodId = $storedPaymentMethodId;
    }

    /**
     * Returns Type.
     * **upi_qr**
     */
    public function getType(): string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     * **upi_qr**
     *
     * @maps type
     */
    public function setType(string $type): void
    {
        $this->type = $type;
    }

    /**
     * Converts the UpiQr object to a human-readable string representation.
     *
     * @return string The string representation of the UpiQr object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'UpiQr',
            [
                'billingSequenceNumber' => $this->billingSequenceNumber,
                'checkoutAttemptId' => $this->checkoutAttemptId,
                'recurringDetailReference' => $this->recurringDetailReference,
                'sdkData' => $this->sdkData,
                'shopperNotificationReference' => $this->shopperNotificationReference,
                'storedPaymentMethodId' => $this->storedPaymentMethodId,
                'type' => $this->type,
                'additionalProperties' => $this->additionalProperties
            ]
        );
    }

    protected $propertyNames = [
        'billingSequenceNumber',
        'checkoutAttemptId',
        'recurringDetailReference',
        'sdkData',
        'shopperNotificationReference',
        'storedPaymentMethodId',
        'type'
    ];

    private $additionalProperties = [];

    /**
     * Add an additional property to this model.
     *
     * @param string $name Name of property.
     * @param mixed $value Value of property.
     */
    public function addAdditionalProperty(string $name, $value)
    {
        if (in_array($name, $this->propertyNames, true)) {
            throw new \InvalidArgumentException(
                "The additional property key, '$name' conflicts with one of the model's properties"
            );
        }

        $this->additionalProperties[$name] = $value;
    }

    /**
     * Find an additional property by name in this model or false if property does not exist.
     *
     * @param string $name Name of property.
     *
     * @return mixed|false Value of the property.
     */
    public function findAdditionalProperty(string $name)
    {
        if (isset($this->additionalProperties[$name])) {
            return $this->additionalProperties[$name];
        }
        return false;
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->billingSequenceNumber)) {
            $json['billingSequenceNumber']        = $this->billingSequenceNumber;
        }
        if (isset($this->checkoutAttemptId)) {
            $json['checkoutAttemptId']            = $this->checkoutAttemptId;
        }
        if (isset($this->recurringDetailReference)) {
            $json['recurringDetailReference']     = $this->recurringDetailReference;
        }
        if (isset($this->sdkData)) {
            $json['sdkData']                      = $this->sdkData;
        }
        if (isset($this->shopperNotificationReference)) {
            $json['shopperNotificationReference'] = $this->shopperNotificationReference;
        }
        if (isset($this->storedPaymentMethodId)) {
            $json['storedPaymentMethodId']        = $this->storedPaymentMethodId;
        }
        $json['type']                             = $this->type;
        $json = array_merge($json, $this->additionalProperties);

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
