<?php

declare(strict_types=1);

/*
 * AdyenApIsLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace AdyenApIsLib\Models;

use AdyenApIsLib\ApiHelper;
use stdClass;

class User implements \JsonSerializable
{
    /**
     * @var Links1|null
     */
    private $links;

    /**
     * @var string[]|null
     */
    private $accountGroups;

    /**
     * @var bool|null
     */
    private $active;

    /**
     * @var string[]|null
     */
    private $apps;

    /**
     * @var string
     */
    private $email;

    /**
     * @var string
     */
    private $id;

    /**
     * @var Name|null
     */
    private $name;

    /**
     * @var string[]
     */
    private $roles;

    /**
     * @var string
     */
    private $timeZoneCode;

    /**
     * @var string
     */
    private $username;

    /**
     * @param string $email
     * @param string $id
     * @param string[] $roles
     * @param string $timeZoneCode
     * @param string $username
     */
    public function __construct(string $email, string $id, array $roles, string $timeZoneCode, string $username)
    {
        $this->email = $email;
        $this->id = $id;
        $this->roles = $roles;
        $this->timeZoneCode = $timeZoneCode;
        $this->username = $username;
    }

    /**
     * Returns Links.
     * References to resources connected with this user.
     */
    public function getLinks(): ?Links1
    {
        return $this->links;
    }

    /**
     * Sets Links.
     * References to resources connected with this user.
     *
     * @maps _links
     */
    public function setLinks(?Links1 $links): void
    {
        $this->links = $links;
    }

    /**
     * Returns Account Groups.
     * The list of [account groups](https://docs.adyen.com/account/account-structure#account-groups)
     * associated with this user.
     *
     * @return string[]|null
     */
    public function getAccountGroups(): ?array
    {
        return $this->accountGroups;
    }

    /**
     * Sets Account Groups.
     * The list of [account groups](https://docs.adyen.com/account/account-structure#account-groups)
     * associated with this user.
     *
     * @maps accountGroups
     *
     * @param string[]|null $accountGroups
     */
    public function setAccountGroups(?array $accountGroups): void
    {
        $this->accountGroups = $accountGroups;
    }

    /**
     * Returns Active.
     * Indicates whether this user is active.
     */
    public function getActive(): ?bool
    {
        return $this->active;
    }

    /**
     * Sets Active.
     * Indicates whether this user is active.
     *
     * @maps active
     */
    public function setActive(?bool $active): void
    {
        $this->active = $active;
    }

    /**
     * Returns Apps.
     * Set of apps available to this user
     *
     * @return string[]|null
     */
    public function getApps(): ?array
    {
        return $this->apps;
    }

    /**
     * Sets Apps.
     * Set of apps available to this user
     *
     * @maps apps
     *
     * @param string[]|null $apps
     */
    public function setApps(?array $apps): void
    {
        $this->apps = $apps;
    }

    /**
     * Returns Email.
     * The email address of the user.
     */
    public function getEmail(): string
    {
        return $this->email;
    }

    /**
     * Sets Email.
     * The email address of the user.
     *
     * @required
     * @maps email
     */
    public function setEmail(string $email): void
    {
        $this->email = $email;
    }

    /**
     * Returns Id.
     * The unique identifier of the user.
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * Sets Id.
     * The unique identifier of the user.
     *
     * @required
     * @maps id
     */
    public function setId(string $id): void
    {
        $this->id = $id;
    }

    /**
     * Returns Name.
     * The user's full name.
     */
    public function getName(): ?Name
    {
        return $this->name;
    }

    /**
     * Sets Name.
     * The user's full name.
     *
     * @maps name
     */
    public function setName(?Name $name): void
    {
        $this->name = $name;
    }

    /**
     * Returns Roles.
     * The list of [roles](https://docs.adyen.com/account/user-roles) for this user.
     *
     * @return string[]
     */
    public function getRoles(): array
    {
        return $this->roles;
    }

    /**
     * Sets Roles.
     * The list of [roles](https://docs.adyen.com/account/user-roles) for this user.
     *
     * @required
     * @maps roles
     *
     * @param string[] $roles
     */
    public function setRoles(array $roles): void
    {
        $this->roles = $roles;
    }

    /**
     * Returns Time Zone Code.
     * The [tz database name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) of the time
     * zone of the user. For example, **Europe/Amsterdam**.
     */
    public function getTimeZoneCode(): string
    {
        return $this->timeZoneCode;
    }

    /**
     * Sets Time Zone Code.
     * The [tz database name](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones) of the time
     * zone of the user. For example, **Europe/Amsterdam**.
     *
     * @required
     * @maps timeZoneCode
     */
    public function setTimeZoneCode(string $timeZoneCode): void
    {
        $this->timeZoneCode = $timeZoneCode;
    }

    /**
     * Returns Username.
     * The username for this user.
     */
    public function getUsername(): string
    {
        return $this->username;
    }

    /**
     * Sets Username.
     * The username for this user.
     *
     * @required
     * @maps username
     */
    public function setUsername(string $username): void
    {
        $this->username = $username;
    }

    /**
     * Converts the User object to a human-readable string representation.
     *
     * @return string The string representation of the User object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'User',
            [
                'links' => $this->links,
                'accountGroups' => $this->accountGroups,
                'active' => $this->active,
                'apps' => $this->apps,
                'email' => $this->email,
                'id' => $this->id,
                'name' => $this->name,
                'roles' => $this->roles,
                'timeZoneCode' => $this->timeZoneCode,
                'username' => $this->username
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->links)) {
            $json['_links']        = $this->links;
        }
        if (isset($this->accountGroups)) {
            $json['accountGroups'] = $this->accountGroups;
        }
        if (isset($this->active)) {
            $json['active']        = $this->active;
        }
        if (isset($this->apps)) {
            $json['apps']          = $this->apps;
        }
        $json['email']             = $this->email;
        $json['id']                = $this->id;
        if (isset($this->name)) {
            $json['name']          = $this->name;
        }
        $json['roles']             = $this->roles;
        $json['timeZoneCode']      = $this->timeZoneCode;
        $json['username']          = $this->username;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
